### ISSUE TITLE
Can not build the windows installer on macOS Catalina version 10.15

### ISSUE THREAD

**Issue by jianfenkezhan** [electron-userland/electron-builder#4313] opened 2019-10-11 09:44 UTC
⨯ Exit code: ENOENT. spawn prlctl ENOENT  stackTrace=
                                                        Error: Exit code: ENOENT. spawn prlctl ENOENT
                                                            at /Users/mujianguo/amp/desktop_app/node_modules/builder-util/src/util.ts:125:16
                                                            at exithandler (child_process.js:296:5)
                                                            at ChildProcess.errorhandler (child_process.js:308:5)
                                                            at ChildProcess.emit (events.js:182:13)
                                                            at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
                                                            at onErrorNT (internal/child_process.js:407:16)
                                                            at process._tickCallback (internal/process/next_tick.

**Comment by AdrianoFerrari** [comment] 2019-10-11 11:28
This is a duplicate of #4305 
Please search other issues before creating a new one. :slightly_smiling_face:

**Comment by jianfenkezhan** [comment] 2019-10-12 01:26
I am sorry, this problem is very sick, how to fix?

**Comment by AdrianoFerrari** [comment] 2019-10-12 01:48
Sorry, I don't know how to fix it, but check here, maybe you will find a solution:
https://github.com/electron-userland/electron-builder/issues/4305

**Comment by lutzroeder** [comment] 2019-10-21 08:22
Duplicate of #4305

**Comment by lutzroeder** [comment] 2019-12-20 09:16
Duplicate of #4305

**Closed** 2020-02-25 11:30 UTC
Labels: backlog
