### ISSUE TITLE
Cannot build Windows app

### ISSUE THREAD

**Issue by SinanMtl** [electron-userland/electron-builder#5867] opened 2021-05-07 09:01 UTC
* **Version**: 22.11.1
* **Electron Version**: 10.4.5
* **Electron Type (current, beta, nightly)**: current
* **electron-updater**: 4.3.8
* **OS**: MacOS BigSur 11.3.1
* **Target**: Windows, NSIS, x64 & ia32

I have an issue that cannot build Windows app. This issue came with latest version (*22.11.1*). Although i installed latest version but electron-builder version shows as *22.10.5*. This problem is not happen version *22.9.1*. Here is the log of error:

```
• electron-builder  version=22.10.5 os=20.4.0
• writing effective config  file=release/4.8.0-beta.18/builder-effective-config.yaml
• packaging       platform=win32 arch=x64 electron=10.4.5 appOutDir=release/4.8.0-beta.18/win-unpacked
• packaging       platform=win32 arch=ia32 electron=10.4.5 appOutDir=release/4.8.0-beta.18/win-ia32-unpacked
• building        target=nsis file=release/4.8.0-beta.18/Simpra-WebPOS-4.8.0-beta.18-win.exe archs=x64, ia32 oneClick=false perMachine=true
• building        target=nsis file=release/4.8.0-beta.18/Simpra-WebPOS-4.8.0-beta.18-win-x64.exe archs=x64 oneClick=false perMachine=true
• building        target=nsis file=release/4.8.0-beta.18/Simpra-WebPOS-4.8.0-beta.18-win-ia32.exe archs=ia32 oneClick=false perMachine=true
• downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z size=1.3 MB parts=1
• downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-3.0.4.1/nsis-3.0.4.1.7z duration=1.44s
• downloading     url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z size=731 kB parts=1
• downloaded      url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.4.1/nsis-resources-3.4.1.7z duration=1.408s
• packager.vm is used: Cannot read property 'readFileSync' of undefined
ERROR: Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /Users/sinanmutlu/root/web-pos/node_modules/builder-util/src/util.ts:132:18
    at exithandler (child_process.js:315:5)
    at ChildProcess.errorhandler (child_process.js:327:5)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by hieuhtr** [comment] 2021-05-07 11:00
I'm facing the same issue too
- OS: Mac Catalina 10.15.7 (19H2)
- Build to Windows NSIS x64

```
yarn run v1.22.10
$ electron-builder -w --x64
  • electron-builder  version=22.10.5 os=19.6.0
  • cannot check updates  error=TypeError: update_notifier_1.default is not a function
  • loaded configuration  file=package.json ("build" field)
  • loaded parent configuration  preset=react-cra
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=12.0.6 appOutDir=dist/win-unpacked
  • building        target=nsis file=dist/Appxxxx Setup 3.1.4.exe archs=x64 oneClick=false perMachine=true
  • packager.vm is used: Cannot read property 'readFileSync' of undefined
  ⨯ Exit code: ENOENT. spawn prlctl ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn prlctl ENOENT
    at /frontend/Appxxxx-web/node_modules/builder-util/src/util.ts:132:18
    at exithandler (child_process.js:310:5)
    at ChildProcess.errorhandler (child_process.js:322:5)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
error Command failed with exit code 1.
```

Reverted `electron-builder` back to `22.9.1` should work

**Comment by mmaietta** [comment] 2021-05-08 03:35
Duplicate of #5863

**Closed by mmaietta** 2021-05-08 03:35 UTC
