### ISSUE TITLE
can not run on macos 11.3

### ISSUE THREAD

**Issue by tangjfn** [electron-userland/electron-builder#5858] opened 2021-05-05 16:45 UTC
* **Version**: 22.11.1
* node: 16.0.0
* npm: 7.11.2
* macos: 11.3

electron-builder --version

node_modules/errlop/edition-es5/index.js:61
		_this = _super.call(this, input.message || input) || this
                 ^
Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
    at new Errlop (/private/tmp/a/node_modules/errlop/edition-es5/index.js:61:18)
    at Object.errtion (/private/tmp/a/node_modules/editions/edition-es5/util.js:23:14)
    at determineEdition (/private/tmp/a/node_modules/editions/edition-es5/index.js:317:21)
    at solicitEdition (/private/tmp/a/node_modules/editions/edition-es5/index.js:350:16)
    at Object.requirePackage (/private/tmp/a/node_modules/editions/edition-es5/index.js:364:9)

.......

**Comment by ezzatron** [comment] 2021-05-06 01:52
I ran into this, seems to be an issue with Node 16.x - works fine with Node 14.x

**Comment by ezzatron** [comment] 2021-05-06 01:53
Possible duplicate of #5668

**Comment by kimlimjustin** [comment] 2021-05-14 10:02
> I ran into this, seems to be an issue with Node 16.x - works fine with Node 14.x

Same here, you can downgrade the node js version to avoid this error! You can downgrade node js with these steps:
1. Install [n](https://www.npmjs.com/package/n) package by running `sudo npm i -g n` command
2. Run `sudo n <node.js version>` to easily switch between node js version.

**Closed** 2021-07-19 05:50 UTC
Labels: backlog
