### ISSUE TITLE
Regression or breaking change in file patterns

### ISSUE THREAD

**Issue by timfish** [electron-userland/electron-builder#1806] opened 2017-07-07 23:33 UTC
I updated from `19.6.3` to `19.13.0` with no config changes and now some files that I excluded are ending up in builds. 

The `files` section of my `config.yml` looks like this:
```yml
files:
# snip
- "!**/node_modules/**/{*.cc,*.obj,*.pdb}"
- "**/node_modules/node-pre-gyp${/*}"
```

However, I'm still getting tens of MB of `.pdb` and `.ojb` files in my output when they were excluded before for example this file:
```
releases\win-unpacked\resources\app\node_modules\usb-detection\build\Release\detection.pdb
```

**Comment by develar** [comment] 2017-07-08 06:14
Working in this area. Will be checked ASAP.

**Comment by develar** [comment] 2017-07-08 10:32
Why do you need to explicitly bundle `node-pre-gyp`?

**Comment by develar** [comment] 2017-07-08 10:37
Please provide full file spec, because I don't believe that it is full :) (no */** or other app files).

**Comment by timfish** [comment] 2017-07-08 10:45
To be honest I cant remember why I have the `node-pre-gyp` line there. Part of the problem could be specifically including everything and then excluding stuff. 

```
# include all files
- "**/*"
# exclude source/build/etc
- "!src${/*}"
- "!build${/*}"
- "!typings${/*}"
# exclude all files in root directory, apart from the basics required
- "!*.*"
- "index.js"
- "index.html"
- "config.js"
# exclude jspm_packages apart from some basic static resources that we require
- "!jspm_packages${/*}"
- jspm_packages/system.js
- jspm_packages/npm/pdfjs-dist@1.8.493/build/pdf.worker.js
# exclude dist apart from the bundles and splash css
- "!dist${/*}"
- dist/styles/splash.css
- dist/bundle-*.js
# exclude build artifacts but ensure we have the native build output
- "!**/node_modules/*/build${/*}"
- "**/node_modules/*/build/**/*.node"
- "!**/node_modules/*/bin/**/*.node"
- "!**/node_modules/*/deps${/*}"
# exclude some other artifacts which are being picked up in the build
- "!**/node_modules/**/{*.cc,*.obj,*.pdb}"
- "**/node_modules/node-pre-gyp${/*}"
```

I've since changed it to the following but haven't checked the latest version of electron-builder:
```
# exclude all files
- "!**/*"
# include required root files
- "package.json"
- "index.js"
- "index.html"
# include all of static
- "static/**"
# jspm_packages bits we require
- jspm_packages/system.js
- jspm_packages/npm/pdfjs-dist@1.8.493/build/pdf.worker.js
# exclude dist apart from the bundles and splash css
- dist/styles/splash.css
- dist/bundle-*.js
# invlude node_modules but exclude build artifacts while ensuring we have the native build output
- "node_modules/**"
- "!**/node_modules/*/build${/*}"
- "**/node_modules/*/build/**/*.node"
- "!**/node_modules/*/bin/**/*.node"
- "!**/node_modules/*/deps${/*}"
# exclude some other artifacts which are being picked up in the build
- "!**/node_modules/**/{*.cc,*.obj,*.pdb}"
- "**/node_modules/node-pre-gyp${/*}"
```

**Comment by develar** [comment] 2017-07-08 11:46
1. `"!**/*"` not required, please remove
2. `package.json` not required, please remove
3. `"static/**"` if you want to include all files from dir (include subfolders), please use  `"static/**/*"`
4. `"node_modules/**"` not required anymore, please remove
5. `"!**/node_modules/**/{*.cc,*.obj,*.pdb}"` not required anymore, thanks for hint, was added to default excludes.
6. `"**/node_modules/node-pre-gyp${/*}"` node-pre-gyp dep not required for runtime, this dependency (and all sub dependencies) not included anymore.

Please change file patterns according to this note and try next `19.14.0` version. Will be released in 10 minutes.

**Comment by develar** [comment] 2017-07-08 11:55
19.14.0 released. Please note — this version contain some dangerous changes that can lead to some regressions, but your feedback is important to test it.

**Comment by timfish** [comment] 2017-07-08 13:30
Thanks for the tips. I'll report back when I get a chance to try this on my dev machine. I just kept adding lines and checking the output and that the app still ran.

It might also be worth excluding `*.h` as well as `*.cc`. I noticed that ffi or one of its dependencies has a really huge header file.

**Comment by develar** [comment] 2017-07-08 15:36
> worth excluding *.h as well as *.cc

thanks, added (will be released today or tomorrow.

**Comment by timfish** [comment] 2017-07-08 18:49
I updated to `19.14.0` and used the below config with success. I haven't had a chance to try my old config with the latest release, but it had enough issues that I'm happy to close this if you are.

```
files:
# include required root files
- "index.js"
- "index.html"
- "config.js"
# include all of static
- "static/**/*"
# jspm_packages bits we require
- jspm_packages/system.js
- jspm_packages/npm/pdfjs-dist@1.8.493/build/pdf.worker.js
# exclude dist apart from the bundles and splash css
- "!dist${/*}"
- dist/styles/splash.css
- dist/bundle-*.js
# exclude build artifacts while ensuring we have the native build output
- "!**/node_modules/*/build${/*}"
- "**/node_modules/*/build/**/*.node"
- "!**/node_modules/*/bin/**/*.node"
- "!**/node_modules/*/deps${/*}"
```

**Comment by develar** [comment] 2017-07-08 18:55
We cannot use 

```
- "!**/node_modules/*/build${/*}"
- "**/node_modules/*/build/**/*.node"
- "!**/node_modules/*/bin/**/*.node"
- "!**/node_modules/*/deps${/*}"
```

in the default excludes because I am not sure that it will be safe. If you can provide some info or links that it is safe to exclude by default — will be cool.

**Closed by develar** 2017-07-08 18:55 UTC
Labels: reply-needed

**Comment by timfish** [comment] 2017-07-08 20:12
@develar No, I wouldn't exclude those by default. For the native modules we're using, only the *.node` output appears to be required. I cant say for sure that this applies everywhere though. 

For us, those final 4 remove about 1.3MB from the compressed installers and our e2e tests run against the `*-unpacked` output so it all gets tested.
