### ISSUE TITLE
Updater causes uncaught exception in the main process if download interrupted

### ISSUE THREAD

**Issue by JonathanLydall** [electron-userland/electron-builder#2451] opened 2018-01-08 07:42 UTC
* **Version**: 
electron-builder: `19.52.1`
electron-updater: `2.18.2`

* **Target**: 
`platform=win32 arch=x64`

While the updater has a download in progress, have the download interrupted. I was testing locally using the `http-server` npm package, so I just terminated the server, but other interruptions like unplugging your network cable, disconnecting WiFi, putting your computer to sleep, should have the same effect.

The following dialog shows:
![image](https://user-images.githubusercontent.com/1290262/34661713-25863f10-f454-11e7-88da-5db228ec65e4.png)
```
[Window Title]
Error

[Main Instruction]
A JavaScript error occurred in the main process

[Content]
Uncaught Exception:
Error: net::ERR_CONNECTION_RESET

[OK]
```

I have tried to catch the error unsuccessfully through the following methods:
- `updater.downloadUpdate(...).then(...).catch(function(error) { ... }`
- `updater.signals.emitter.addListener("error", function(error) { ... }`

It can be caught by putting `process.on('uncaughtException', function (error) { ... }`, in NodeJS's entry `.js` file, but there is no more context to the error than what you see above, so there is no way to determine that the error came from the updater.
![image](https://user-images.githubusercontent.com/1290262/34662257-ef505e7c-f457-11e7-9982-c4f140a8ea61.png)

**Comment by marceloromaomultilaser** [comment] 2018-01-23 18:17
Same here!!!

**Comment by OsamaAamer** [comment] 2018-01-24 09:30
+1

**Comment by btibarra** [comment] 2018-01-26 12:46
Does someone figured it out how to solve it?

**Comment by JeongJun-Lee** [comment] 2018-07-09 07:43
+1

**Comment by tkleinke** [comment] 2018-10-29 09:48
Same here.

**Comment by amits1995** [comment] 2018-10-29 19:23
+1  
"electron-updater": "^2.21.10"  
Auto updater from Github  
Happened on 2 Mac's but couldn't reproduce using @JonathanLydall steps on my Ubuntu machine

**Comment by jmvallejo** [comment] 2019-01-17 23:34
This happens only on mac for me, I don't seem to be able to catch the error. I have tried using a try/catch block as well as listening to the error event... nothing really works. Anyone has had any luck?
![image](https://user-images.githubusercontent.com/14879937/51355891-81f88b00-1a86-11e9-9bc3-c413cc43e801.png)
This error is intentional, I'm using a bad URL, but I'd like to be able to catch it.

**Comment by alanning** [comment] 2019-03-01 16:19
I believe this issue can be closed now that [this PR](https://github.com/electron-userland/electron-builder/pull/3531) by @vladimiry has been merged and released in electron-updater@4.0.7.

**Comment by andrewchae** [comment] 2019-05-28 22:12
@alanning it doesn't look like that PR actually fixes this issue

**Comment by vladimiry** [comment] 2019-05-28 22:17
> By the way, that PR tweaked only checkForUpdatesAndNotify method but I didn't explore the checkForUpdates method which also might potentially be a problematic one.

https://github.com/electron-userland/electron-builder/issues/2398#issuecomment-482279666

**Comment by vladimiry** [comment] 2019-05-28 22:21
@andrewchae I can only suggest to make sure you are using the most recent electron-updater version which is currently 4.0.11 and if still fails to try switching to 4.0.7.

**Comment by andrewchae** [comment] 2019-05-28 23:14
@vladimiry I just tried 4.0.11 and it still has this issue. I wasn't able to get 4.0.7 working but I believe checkForUpdatesAndNotify() calls checkForUpdates() and the issue is actually deeper in the code.

**Comment by vladimiry** [comment] 2019-05-29 09:52
@andrewchae `checkForUpdatesAndNotify` certainly became working better when I was playing with it but I don't use the `electron-updater` anymore in https://github.com/vladimiry/ElectronMail so, unfortunately, I don't have a capacity for making a second look into the issue.

**Closed** 2019-08-04 10:35 UTC
Labels: backlog

**Comment by patrickmichalina** [comment] 2019-09-27 12:34
Same here.

**Comment by gbodeen** [comment] 2019-11-06 00:05
I ran into the problem today also.  It remains unresolved and I've found no way to catch and handle the error graciously.

**Comment by danielehrhardt** [comment] 2019-12-06 17:51
> I ran into the problem today also. It remains unresolved and I've found no way to catch and handle the error graciously.

Did someone found a Solution?

**Comment by Evilu** [comment] 2020-01-07 14:22
This issue should NOT be closed,
 i ran the exact same issue with`   "electron-updater": "4.2.0".`
if the latest.yml file on my s3 bucket is deleted, all the clients will receive this message.

The only way to avoid this is to listen to the uncaughtException events of node. 
A little risky practice.
