### ISSUE TITLE
electron-updater fails since electron 7.1.3 with error "Redirect was cancelled"

### ISSUE THREAD

**Issue by wartab** [electron-userland/electron-builder#4569] opened 2019-12-31 14:43 UTC
* **Version**: 22.1.0

* **Target**: 4.2.0

Our Electron application fails to update whenever the Electron version of our application is higher than 7.1.2. 

The logs indiciate the following error: "Redirect was cancelled".

This happens on both Windows and Mac OS releases.

This sadly means that everyone who installed the newer version of Electron will need to manually reinstall the application to fix the issue.

This issue was already mentioned [here](https://github.com/electron-userland/electron-builder/issues/4505), but the author closed it, for no apparent reason.

**Comment by s00d** [comment] 2020-01-13 15:08
electron 7.1.8 worked!

**Comment by lutzroeder** [comment] 2020-01-21 07:12
Duplicate of #4505

**Closed** 2020-01-21 07:26 UTC
