### ISSUE TITLE
Can't run app after installing from .dmg

### ISSUE THREAD

**Issue by brrian** [electron-userland/electron-builder#377] opened 2016-05-04 18:28 UTC
I am having issues installing the .dmg after downloading it. Following the instructions, I've been able to build and sign the app without any issues. When installing it locally or physically transferring the .dmg, it can install with no issues.

However, after uploading it and then downloading it from another computer, I get the following error whenever I try to run the application after installing it:
**"MyApp" is damaged and can't be opened. You should move it to the Trash.**

If I set my Gatekeeper settings to allow apps from anywhere, it runs without a hitch. After doing some digging, I think the problem is somehow related how the app is signed.

Running `codesign --verify --verbose "MyApp.app"` I get:
```
MyApp.app/: valid on disk
MyApp.app/: satisfies its Designated Requirement
```

However `codesign --verify --verbose --deep "MyApp.app"` gets me:
```
MyApp.app/: a sealed resource is missing or invalid
In subcomponent: /MyApp.app/Contents/Frameworks/Squirrel.framework
file modified: /MyApp.app/Contents/Frameworks/Squirrel.framework/Versions/Current/Resources/ShipIt
```

`spctl --verbose --assess --type execute -v "MyApp.app"` returns a similar error.

Building the .app with [electron-packager](https://github.com/electron-userland/electron-packager) seems to be okay though:
```
spctl --verbose --assess --type execute -v "MyApp.app"
MyApp.app/: accepted
source=Developer ID
origin=Developer ID Application: Name (xxxxxxxxxx)
```

I am distributing for outside the App Store. So far, I haven't really been able to find any solutions. Am I missing anything? Thanks!

**Comment by develar** [comment] 2016-05-04 18:34
> Building the .app with electron-packager seems to be okay though:

Since 3.14.0 we use the same package to sign app. Please specify electron-builder version.

How do you specify your identity?

**Comment by develar** [comment] 2016-05-04 18:36
FYI: our CI tests pass and my app works. I use [RB App Checker Lite](https://itunes.apple.com/us/app/rb-app-checker-lite/id519421117?mt=12) to verify.

**Comment by brrian** [comment] 2016-05-04 19:40
Thanks for the quick response.

I'm using 3.17.0 and I've tested with both the CSC_NAME and the build.osx.identity.

Using RB App Checker Lite, I get the same error message:
```
Error details: “-67054: a sealed resource is missing or invalid” {
	Error in subcomponent: Contents/Frameworks/Squirrel.framework
	Resources altered: 
		Contents/Frameworks/Squirrel.framework/Versions/Current/Resources/ShipIt
```

I downloaded your app and compared the output of RB App Checker, and it seems that the only difference is in the auxiliary executables:

Yours:
```
11 auxiliary executables have been found. ￼
	4 executables are unsigned. ￼ ￼
	7 executables are signed by  “Apple Root CA”, “Developer ID Application: Vladimir Krivosheev”. ￼
```

Mine:
```
11 auxiliary executables have been found. ￼
	11 executables are signed by  “Apple Root CA”, “Developer ID Application: Brian Wang”. ￼
```

Of the 4 unsigned executables is **Squirrel.framework/Versions/A/ShipIt** which is similar to the resources altered error on **Squirrel.framework/Versions/Current/Resources/ShipIt**.

Oddly though, checking my app built with electron-packager also shows that 11 executables are signed, so maybe that's unrelated to this issue.

**Comment by develar** [comment] 2016-05-04 19:48
Reproduced. Will be fixed tomorrow. Have no idea why tests passed, but real app verification is broken.

Please try version to "3.14.0" as a temp workaround (I guess regression was since 3.15)

**Closed** 2016-05-04 20:49 UTC
Labels: bug, osx

**Comment by brrian** [comment] 2016-05-04 20:50
I just tested with 3.14.0 and it worked perfectly. Thanks for help and quick responses!

**Comment by develar** [comment] 2016-05-04 20:50
v3.17.1 will be in 30 minutes if tests passed. Thanks! Test suite will be modified to catch such errors later (on weekend).
