### ISSUE TITLE
Windows 10 - NSIS one click install as Current User

### ISSUE THREAD

**Issue by FromStoneage** [electron-userland/electron-builder#564] opened 2016-07-04 21:28 UTC
* **5.10.5**: 

* **nsis - windows**: default to one click install

When installing the nsis `.exe` under Windows 7, one click will install for all users. However when installing under Windows 10 environment, regardless (UAC - User Access Control settings) it only install under "Current User". The work around is to run the installer as "Run as Administrator".

Question, is there anyway to avoid right click > "Run as Administrator" to install the app for all User ?

**Comment by develar** [comment] 2016-07-05 07:27
> When installing the nsis .exe under Windows 7, one click will install for all users.

It is bug.

>  is there anyway to avoid right click > "Run as Administrator" to install the app for all User ?

You can disable one-click installer (set `oneClick` to false) and set `perMachine` to false. See https://github.com/electron-userland/electron-builder/wiki/Options#buildnsis

**Comment by FromStoneage** [comment] 2016-07-05 16:10
Thanks @develar yes those flag fixes my issue. No I don't need a one-click installer that installers for all user, as long as there is a mechanism to install for all Users it's a good solution !

**Comment by FromStoneage** [comment] 2016-07-05 16:18
@develar sorry for closing it earlier. I just tried the flag you mentioned. It does prompt user to choose to install between "**Anyone who uses this computer (all users)**" and "**Only for me (current.user)**"

However, when running the installer under Windows 10, without "Run as Administrator" the installer doesn't proceed pass the first prompt and crashes.

**Comment by develar** [comment] 2016-07-05 17:11
Why do you want to install for all users?

**Comment by FromStoneage** [comment] 2016-07-05 17:36
@develar good question, one of the reason is I'm trying to associate a file extension to the electron app. If the app is not installed for all users, the app will not be installed under `C:\Program Files`. As a result if the file extension is not associated with the app, open a file with unknown extension will prompt user to choose from a list of pre-installed apps, this list will **_not_** contain the custom app. Further more, when browse for other apps to open, by default Windows will load an Open with .. dialog that defaults to `C:\Program Files`.

That's why I'd be interested to deploy the app for All user instead of current user.

**Comment by develar** [comment] 2016-07-09 15:15
@FromStoneage Thanks for clear explanation. I will check and support per-machine installation.

> When installing the nsis .exe under Windows 7, one click will install for all users.

Cannot reproduce.

**Comment by develar** [comment] 2016-07-09 15:18
> "Run as Administrator"

Must be in any case installed for current user (default settings). Bug. Will be fixed.

**Comment by develar** [comment] 2016-07-09 17:41
One-click per machine installer will not elevate during install — instead, `RequestExecutionLevel` will be set to `admin`. Boring installer allows to choose install mode, so, it makes sense to elevate during install. But no sense for one-click.

**Comment by develar** [comment] 2016-07-09 18:23
@FromStoneage 5.12.0 — you can now just set `perMachine` to `false` and you will get one-click installer per all users. Exactly as you want. Thanks again for clear explanation.

Issue is not yet closed because boring-installer crashed if per all users selected.

Please note — regardless of user state (admin or not), app will be executed from user normal user, not from admin.

**Comment by FromStoneage** [comment] 2016-07-10 15:03
@develar thanks for clarify and all your time on this issue ! I will give it a try tomorrow !

**Closed** 2016-07-11 09:44 UTC
Labels: bug, nsis, windows

**Comment by develar** [comment] 2016-07-11 10:59
If you use NSIS installer, strongly recommended update to 5.12.1 version.
