### ISSUE TITLE
Build fails on macOS 12.3 due to missing /usr/bin/python

### ISSUE THREAD

**Issue by sprout2000** [electron-userland/electron-builder#6732] opened 2022-03-20 09:25 UTC
* **Electron-Builder Version**: 22.14.13
* **Node Version**: v16.14.2
* **Electron Version**: v17.1.2
* **Electron Type (current, beta, nightly)**: current
* **Target**: darwin aarch64

### What happened

Build fails on macOS 12.3 due to missing `/usr/bin/python`.

```sh
% npx electron-builder build -m
  • electron-builder  version=22.14.13 os=21.4.0
  • writing effective config  file=dist/builder-effective-config.yaml
  • packaging       platform=darwin arch=arm64 electron=17.1.2 appOutDir=dist/mac-arm64
  • default Electron icon is used  reason=application icon is not set
  • skipped macOS application code signing  reason=cannot find valid "Developer ID Application" identity or custom non-Apple code signing certificate, it could cause some undefined behaviour, e.g. macOS localized description not visible, see https://electron.build/code-signing allIdentities=     0 identities found
                                                Valid identities only
     0 valid identities found
  • building        target=macOS zip arch=arm64 file=dist/electron-quick-start-1.0.0-arm64-mac.zip
  • building        target=DMG arch=arm64 file=dist/electron-quick-start-1.0.0-arm64.dmg
  • Detected arm64 process, HFS+ is unavailable. Creating dmg with APFS - supports Mac OSX 10.12+
  • building block map  blockMapFile=dist/electron-quick-start-1.0.0-arm64-mac.zip.blockmap
  ⨯ Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
```

However, as is well known, it is not possible to link to `/usr/bin/python` even with su privileges.

### Reproduction

```sh
% degit electron/electron-quick-start  electron-quick-start
% cd electron-quick-start
% npm i -D electron-builder
% npx electron-builder build -m
```

**Comment by scowalt** [comment] 2022-03-20 14:28
Dupe of #6606 and #6726

**Comment by mmaietta** [comment] 2022-03-20 16:44
Please upgrade to the latest v23.0.3 for macOS 12.3 support.

**Closed by mmaietta** 2022-03-20 16:44 UTC

**Comment by stefan-ysh** [comment] 2022-09-15 14:24
me too

> Exit code: ENOENT. spawn /usr/bin/python ENOENT  failedTask=build stackTrace=Error: Exit code: ENOENT. spawn /usr/bin/python ENOENT
