### ISSUE TITLE
pnpm monorepo  build error

### ISSUE THREAD

**Issue by gjfei** [electron-userland/electron-builder#6933] opened 2022-06-10 06:11 UTC
* **Electron-Builder Version**:  23.0.3

* **Node Version**: 16.13.2

* **Electron Version**: 19.0.4
* **Electron Type (current, beta, nightly)**:

* **Target**: window

![image](https://user-images.githubusercontent.com/33827314/173001752-ee5f97e7-4f59-4dc8-af0f-cd964765ae25.png)

[reproduction](https://github.com/gjfei/electron-terminal)

**Comment by gjfei** [comment] 2022-06-10 06:12
hellp me

**Comment by mmaietta** [comment] 2022-07-04 04:26
Are we sure that is an issue with electron-builder? It seems to be saying your pnpm installation is not a valid win32 application. Can you try node 14 or a newer version of node 16?

**Comment by hipstersmoothie** [comment] 2022-07-27 22:23
This is the same issue as this https://github.com/electron-userland/electron-builder/issues/6289

Which is because of this issue that's been fixed in app-builder https://github.com/develar/app-builder/issues/63

But hasn't been pulled in because:

https://github.com/develar/app-builder/issues/83
https://github.com/electron-userland/electron-builder/pull/6684

**Comment by mmaietta** [comment] 2022-07-28 16:16
Does this workaround work correctly for monorepos?
https://www.electron.build/#note-for-pnpm

**Comment by hipstersmoothie** [comment] 2022-07-28 17:58
Checking on that now. But using any of those options kills most of the usefulness of pnpm. Proper support would be a huge improvement. Is there an issue tracking that?

**Comment by mmaietta** [comment] 2022-07-28 18:32
https://github.com/electron-userland/electron-builder/issues/6933#issuecomment-1197434288
We're blocked from updating by https://github.com/develar/app-builder/issues/83

**Comment by MasterOdin** [comment] 2022-08-12 19:18
I was running into a similar issue (reported as #7029), but with yarn, and had a similar root cause where the `.yarn/releases/yarn-*.cjs` file we had checked into our repo had a `#!/usr/bin/env node` shebang. I found that on changing the shebang to be just `#!node`, I was able to fix my build issues.

Perhaps possible to do a similar hack to `pnpm/bin/pnpm.cjs` file as an immediate workaround, though ideally could update app-builder and have that be fixed there.

**Comment by rafaelpimpa** [comment] 2022-08-22 14:16
Having the same problem, the workaround is calling ``pnpm electron-builder`` instead of a package script.

---

@mmaietta I could make it work without the ``node-linker=hoisted`` option, my ``.npmrc`` currently is:

```
strict-peer-dependencies=false
shamefully-hoist=true
```

I run the build process for the renderer, and then ``pnpm electron-builder`` -- calling it in script throws ``not a valid win32 application``.

I also had to move ``electron-*`` packages (electron-updater, etc.) to deps instead of devDeps.

**Comment by kooriookami** [comment] 2022-11-23 06:11
Still have this problem, I have to use npm build it.

**Comment by ramiel** [comment] 2023-09-22 14:29
Why is this issue still present? The bugfix on app-builder should be deployed already

**Comment by mmaietta** [comment] 2023-09-22 17:21
@ramiel because the dependency update is still broken
See: https://github.com/electron-userland/electron-builder/pull/7774

And comment requesting help from @develar to resolve the issue in app-builder
https://github.com/develar/app-builder/issues/83#issuecomment-1716257591

**Closed** 2024-08-03 06:21 UTC

**Comment by AiHaibara** [comment] 2024-08-15 03:26
for electron-builder 25 or 25.0.4
when i using pnpm and 
`shamefully-hoist=true` in npmrc
sometimes the builded exe, it will show the error `cannot find module 'jsonfile/utils'...`
but using `node-linker=hoisted`  in npmrc is ok
and in 24.13.3 `shamefully-hoist=true` is working.
