### ISSUE TITLE
The folder “app.zip” doesn’t exist.

### ISSUE THREAD

**Issue by iDuuck** [electron-userland/electron-builder#1719] opened 2017-06-21 15:01 UTC
* **Version**: 
Updater: 2.3.1
Builder: 19.5.1

* **Target**: Mac OS X

Users are keep getting the following error:
```
[2017-06-21 16:23:26:0816] [warn] Error: The folder “app.zip” doesn’t exist.: The folder doesn’t exist.
    at Error (native)

[2017-06-21 16:23:26:0816] [error] Error: Error: The folder “app.zip” doesn’t exist.: The folder doesn’t exist.
    at Error (native)
```

What is this? The project is [kreativgebiet/taskana](https://github.com/kreativgebiet/taskana)

**Comment by develar** [comment] 2017-06-21 19:47
Interesting. I will check.

**Comment by iDuuck** [comment] 2017-06-23 20:12
Any update? Need feedback on this :(

**Comment by develar** [comment] 2017-06-23 20:53
MacUpdater doesn't set `Content-Length` and probably Squirrel.Mac confused (well, works correctly during test without it).

It one line fix, but I need to test it manually. So, will be released tomorrow morning CET.

**Comment by iDuuck** [comment] 2017-06-23 20:54
That's awesome, thank you!

**Closed** 2017-06-24 06:52 UTC
Labels: bug, electron-updater

**Comment by Matho** [comment] 2018-03-23 12:47
**Version**
electron-builder: 20.7.1
electron-updater: 2.21.3

**Target:**
Mac OSX High Sierra

I have issue with error message ‘The folder “app.zip” doesn’t exist.’ Seems, that the issue is caused by space in product name. When I manually rename space in file (also in json, yml files)  to another character like ‘-’, it works. This error cause that the update is not installed. Issue is related to #1398, #1607
