### ISSUE TITLE
Azure Trusted Signing Adds Path to Filenames Without Whitespaces

### ISSUE THREAD

**Issue by olivereisenhut** [electron-userland/electron-builder#8612] opened 2024-10-18 12:03 UTC
* **Electron-Builder Version**: 26.0.0-alpha.3

* **Node Version**: v22.9.0

* **Electron Version**: 31.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows

I think we experiencing a side-effect of #8600. 

Our bundle folder (`\dist`) looks somewhat like this:
```
builder-debug.yml
bulder-effective-config.yaml
'${appName} ${appVersion}.msi'
'${appName} Setup ${appVersion}.exe'
'${appName} Setup ${appVersion}.exe.blockmap'
${appName}-${appVersion}-win.zip
latest.yml
```

Before applying the latest alpha (`26.0.0-alpha.3`) the only file that was uploaded was `${appName}-${appVersion}-win.zip`.
Now, after applying `26.0.0-alpha.3`, all the files with spaces in them are uploaded correctly, although the ones that don't have spaces have the absolute path prefixed in the filename.

We now have the following files uploaded to Github:
```
${appName} ${appVersion}.msi -> correct
${appName} Setup ${appVersion}.exe -> correct
${appName} Setup ${appVersion}.exe.blockmap -> correct
D.a.${repoName}.${repoName}.dist.${appName}-${appVersion}-win.zip
D.a.${repoName}.${repoName}.dist.latest.yml
```

Builder output from our CI, this is why I now it's the absolute path:
```
uploading       file=D:\a\${repoName}\${repoName}\dist\${appName}-${appVersion}-win.zip provider=github
```

**Comment by mmaietta** [comment] 2024-10-18 14:50
@olivereisenhut was this working on a previous alpha release of electron-builder? Trying to discern where the issue is coming from and git diff it.

**Comment by olivereisenhut** [comment] 2024-10-18 15:58
I guess not:
- **25.1.8 (stable)** - uploads `${appName}-${appVersion}-win.zip` correctly fails on files with space #8600
- **26.0.0-alpha.1** -  uploads `${appName}-${appVersion}-win.zip` correctly fails on files with space #8600
- **26.0.0-alpha.2** - uploads `${appName}-${appVersion}-win.zip` correctly fails on files with space #8600
- **26.0.0-alpha.3** - uploads all files, files without space are prefixed with absolute path

We're currently using a different signing method and trying to migrate to Azure Trusted Signing, so we've never had it in a working state.

**Comment by mmaietta** [comment] 2024-10-19 15:50
Out of curiosity, @MikeJerred have you run into this issue yet? I'm not sure how PR https://github.com/electron-userland/electron-builder/pull/8606 would cause this to appear as it only changes the `Files` path, no logic in the publisher was changed.

**Comment by MikeJerred** [comment] 2024-10-20 18:04
> Out of curiosity, @MikeJerred have you run into this issue yet? I'm not sure how PR #8606 would cause this to appear as it only changes the `Files` path, no logic in the publisher was changed.

I have not yet tried to publish so didn't run into this (yet)

**Comment by mmaietta** [comment] 2024-10-24 17:30
@olivereisenhut does this issue occur for you when using certificates with signtool? (Even if self-signed cert) Trying to discern if there was a change in the publisher logic versus just the signing file path PR. I don't see this issue occurring in CI tests for signtool, but the CI tests are unable to cover the azure implementation

**Comment by olivereisenhut** [comment] 2024-10-25 08:02
Ahh right, good point. I built with the latest alpha (26.0.0-alpha.3) and signtool and the same thing happens.
Building with the latest stable (25.1.8) works as expected.

I'll try building with the previous alpha versions to narrow it down further.

**Comment by olivereisenhut** [comment] 2024-10-25 12:08
Alright, I built all the alpha version with signtool, here are the results:
26.0.0-alpha.0 -> works
26.0.0-alpha.1 -> works
26.0.0-alpha.2 -> works
26.0.0-alpha.3 -> adds the path as prefix

**Comment by olivereisenhut** [comment] 2024-10-25 13:52
I think I have found the problem. I created a PR for it. #8631

**Comment by mmaietta** [comment] 2024-10-28 17:18
Released in [v26.0.0-alpha.4](https://github.com/electron-userland/electron-builder/releases/tag/v26.0.0-alpha.4)

**Closed by mmaietta** 2024-10-28 17:18 UTC

**Comment by mmaietta** [comment] 2024-10-31 00:27
@olivereisenhut do you happen to have a production azure-trusted-signed exe you could send me? I'd like to see if I can implement signature verification for the auto-update flow, or determine if azure trusted signing even can support that flow.

**Comment by olivereisenhut** [comment] 2024-10-31 17:49
Hey,

We're going to test our current build on Monday.
Though, I quickly checked our `app-update.yml`, which still contains the publisher name. 
We kept the `publisherName` in our build config by accident.

**Comment by mmaietta** [comment] 2024-10-31 22:13
Perfect, thanks for confirming the workaround. Auto-updates should function as expected with publisherName in the build config
