### ISSUE TITLE
Exec must be without quotes in app.desktop file

### ISSUE THREAD

**Issue by 532910** [electron-userland/electron-builder#2759] opened 2018-03-30 08:21 UTC
I'm using riot-web from https://riot.im/packages/debian
It's impossible to run it from menu, as Exec="/opt/Riot/riot-web"
Must be without quotes: Exec=/opt/Riot/riot-web

@t3chguy in https://github.com/vector-im/riot-web/issues/6421  says it's your issue

**Comment by trevj** [comment] 2019-02-14 21:34
FYI, this breaks `setAsDefaultProtocolClient` on Linux, at least with AppImage:
https://electronjs.org/docs/api/app#appsetasdefaultprotocolclientprotocol-path-args

The reason is that **`xdg-settings` cannot handle `.desktop` files with double quotes in the `Exec` line**. Weird, though I think it's legal:
https://standards.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#exec-variables

I put together a minimal app to reproduce:
https://github.com/trevj/setasdefaultprotocolclient-repro

How to run...

* Build:
  * `git clone` the repo
  * `cd` to the repo's root
  * `yarn install`
  * `yarn package`
* Run:
  * add some temp folder to your path, e.g. `mkdir ~/tmp && export PATH=~/tmp:$PATH`
  * copy the AppImage here, e.g. `cp <path to repo>/dist/*.AppImage ~/tmp/`
  * **from a terminal**, run the app and say yes to "integrate with the system"
  * **there will be an error on the terminal: a protocol handler could not be added**
  * edit the app's .desktop file (usually `~/.local/share/applications/appimagekit-setasdefaultprotocolclient-repro.desktop`) and remove the double quotes from the `Exec=` line
  * **run the app again - this time, there should be a message on the terminal confirming that a protocol handler was set**
  * try to open a URL with this custom protocol, e.g. `xdg-open setasdefaultprotocolclient-repro://bob` - after a moment, a "hello!" message should appear on the terminal

That's a lot of steps to reproduce...are you open to a one-liner pull request? :-)

**Comment by hosaka-corp** [comment] 2019-05-29 07:06
It seems like `xdg-mime` doesn't like double-quotes - this apparently happens with our AppImage also.

**Comment by JonnyHaystack** [comment] 2019-05-29 13:44
I've opened an issue with xdg-utils because it seems like this behaviour is bugged on that end https://gitlab.freedesktop.org/xdg/xdg-utils/issues/151

**Comment by develar** [comment] 2019-06-24 08:10
Well, without double quotes, desktop file will be invalid, because spaces must be escaped.

So, if this issue is important for you, consider using snap — it is the most recommended and user-friendly Linix packaging format (as I can say). (also, consider to distribute using [snap store](https://snapcraft.io/store), and not via manual downloading).

**Closed** 2019-06-24 10:15 UTC
Labels: bug, linux

**Comment by develar** [comment] 2019-06-24 10:16
Fixed in 21.0.1

**Comment by 532910** [comment] 2019-11-19 22:09
I confirm it's fixed and works fine.
