### ISSUE TITLE
Multiple license files don't seem to work for dmg

### ISSUE THREAD

**Issue by bingqiao** [electron-userland/electron-builder#1982] opened 2017-08-23 10:40 UTC
* **Version**: 19.24.2
* **Target**: MacOS

Multiple license files don't seem to work. I created two license files license_en.txt and license_de.txt in build resources but still see the English one together with all the buttons and text in English in the License dialog even after I have set the primary language of the Mac to German. All other menu&buttons etc of the OS show German once restarted. But the dmg still is treated as being mounted in an English OS.

I tried another language and got the same English result. Is there anyway to check if the non-English license files have been added to the dmg? Is setting primary Language not enough to trigger the non-English license?

Many thanks

**Comment by develar** [comment] 2017-08-23 10:45
Yes, not supported. First request was awaited :)

**Comment by bingqiao** [comment] 2017-08-23 10:51
Thanks for the response. So this section on dmg is not very accurate then. [Dmg Options](https://github.com/electron-userland/electron-builder/wiki/Options#DmgOptions). Single license does work but multiple don't yet?

**Comment by develar** [comment] 2017-08-23 10:57
No, I am wrong, it should be supported. To investigate.

**Comment by bingqiao** [comment] 2017-08-23 15:59
After looking into the code, it seems that the license template (electron-builder/packages/electron-builder/templates/dmg/license.txt) is hardcoded to only show one language in the license dialog:
`data 'LPic' (5000) {
	$"0000 0002 0000 0000 0000 0000 0004 0000"
};`

Even though the number of entries is set to 2 (this should be dynamically set from the number of license files available), both refer to language code 0 which is English and the second entry refers to resource id 4 which is the French one. This doesn't look right. In order to show the German license, the corresponding LPic should probably look like the following:
`data 'LPic' (5000) {
	$"0000 0002 0000 0000 0000 0003 0001 0000"
};`
The other point I'd like to raise is that based on my limited understanding of dmg, I'm not certain the locale gets switched automatically according to the primary language of the OS. Instead, you will see a dropdown show up to pick the language you want to see the license in:

<img width="669" alt="screen shot 2017-08-23 at 16 55 33" src="https://user-images.githubusercontent.com/26798622/29625672-50292a58-8824-11e7-8613-17a3353cb8fe.png">

**Comment by develar** [comment] 2017-08-23 16:02
@bingqiao Thanks for investigation. I have decided to reuse some python code and it works. Fix will be in 1 hour released.

**Closed** 2017-08-23 17:04 UTC
Labels: bug, investigate

**Comment by develar** [comment] 2017-08-23 17:05
@bingqiao Please try 19.24.4 (`next` release).

**Comment by bingqiao** [comment] 2017-08-23 17:52
@develar thanks so much for the quick fix! It works well and the language dropdown shows available languages. The only issue is when it comes to licenses in unicode/multibyte languages like Chinese which show up wrong (The control texts are still displayed correctly). The workaround is to use rtf instead of txt. I'm wondering if it has anything to do with the use of bytearray.fromhex?

**Comment by develar** [comment] 2017-08-23 17:59
@bingqiao I have the question. https://github.com/al45tair/dmgbuild/issues/6 

Thanks for hint about rtf, I will try.

**Comment by bingqiao** [comment] 2017-08-23 19:53
Another issue I found is that the default selection of language is not always en_US even if en_US is the default language set in the license object passed to the python code. For example, English is selected by default if there are en and fr. But German is selected by default if there are en and de. Is this a limitation of DMG or is there a way to actually set the default selection? Thanks

**Comment by develar** [comment] 2017-08-24 09:26
>  But German is selected by default if there are en and de

Cannot reproduce. Please ensure that English is the first language System "Preferred languages".

**Comment by develar** [comment] 2017-08-24 18:42
Charset for txt is fixed, release will be tomorrow.

**Comment by develar** [comment] 2017-08-25 07:10
19.25.0

**Comment by bingqiao** [comment] 2017-08-25 07:24
Getting this on 19.25.0:
`
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/dmg-builder
npm ERR! 404 
npm ERR! 404  'dmg-builder' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'electron-builder'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

Perhaps something wrong on my setup of node but wanted to report it just in case.

**Comment by develar** [comment] 2017-08-25 07:27
Sorry, 19.25.1

**Comment by develar** [comment] 2017-08-25 07:31
Finally fixed in 19.25.2 (several minutes).
