### ISSUE TITLE
Get request time out error when build exe file on unbuntu 16.04  with electron-builder@18.5.1

### ISSUE THREAD

**Issue by chenyuncai** [electron-userland/electron-builder#1840] opened 2017-07-19 07:12 UTC
* **v18.5.1**: 

none

* **win32 x64**: 

When use build cmd like this in unbuntu 16.04
./node_modules/.bin/build -w --pd releases/TMROBOT-win32-x64 --x64

and about one minute later, I get this error below:

Unhandled rejection Error: Request timed out
    at TLSSocket.socket.setTimeout (/home/work/code/p2p/node_modules/._electron-builder-http@18.5.1@electron-builder-http/src/httpExecutor.ts:184:18)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket.Socket._onTimeout (net.js:351:8)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
From previous event:
    at Promise.longStackTracesCaptureStackTrace [as _captureStackTrace] (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/debuggability.js:397:19)
    at Promise._resolveFromExecutor (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/promise.js:480:10)
    at new Promise (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/promise.js:79:10)
    at CancellationToken.createPromise (/home/work/code/p2p/node_modules/._electron-builder-http@18.5.1@electron-builder-http/src/CancellationToken.ts:51:5)
    at /home/work/code/p2p/node_modules/._electron-builder-util@18.5.1@electron-builder-util/src/nodeHttpExecutor.ts:29:44
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/work/code/p2p/node_modules/._bluebird@3.5.0@bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

What can I do to fix this?
Which address the process is connecting?

I develop my app in mac for a few months, now I need to mv the package script to our server thus we encounter the problem.

I tried to use latest version, but our project have used the version 18.5.1 for a long time. we cannot update to latest. besides there are another errs when I use latest.

Thanks

**Comment by develar** [comment] 2017-07-19 07:14
Duplicate of #1839

**Closed by develar** 2017-07-19 07:14 UTC
