### ISSUE TITLE
Not able to register and unregister .dll file through electron-builder custom NSIS include script

### ISSUE THREAD

**Issue by alokmahor** [electron-userland/electron-builder#5701] opened 2021-03-12 03:39 UTC
* **Version**:  22.10.5

* **Electron Version**: 11.1.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: windows 10

I have created a [electron][1] desktop app and created a installer using [electron-builder][2].

Now I want to add capability of `registering` a `.dll` file at the time of `installation` of my desktop app and `unregistering` it at the time of `uninstallation`.

My `installer.nsh` file is
```
!macro customInstall
  Exec "regsvr32.exe $INSTDIR\resources\app.asar.unpacked\node_modules\obs-studio-node\obs-virtualsource.dll"
!macroend

!macro customUnInstall
  Exec "regsvr32.exe /u $INSTDIR\resources\app.asar.unpacked\node_modules\obs-studio-node\obs-virtualsource.dll"
!macroend
```

My `electron-builder` config is 
```
"build": {
    "nsis": {
      "include": "installer.nsh"
    },
    "mac": {
      "icon": "build/icon.png"
    },
    "win": {
      "icon": "build/icon.png"
    }
  }
```

But this is not working for me. I have tried both `Exec` and `ExecWait` none is working.  
What I am missing to make it working?

  [1]: https://www.electronjs.org
  [2]: https://www.electron.build/

**Comment by mmaietta** [comment] 2021-03-12 20:02
Closing as duplicate of #5704

**Closed by mmaietta** 2021-03-12 20:02 UTC
