### ISSUE TITLE
router失效

### ISSUE THREAD

**Issue by BoxCode7** [electron-userland/electron-builder#7131] opened 2022-09-08 07:49 UTC
在vue.config.js文件配置一下代码后会导致Vue的router失效无法使用路由
```
pluginOptions: {
    electronBuilder: {
      builderOptions: {
        win: {
          target: 'nsis',

        },
        nsis: {
          oneClick: false,
          allowToChangeInstallationDirectory: true,
        }
      },
      nodeIntegration: true,
      contextIsolation: false,
    }
  },
```

**Comment by mmaietta** [comment] 2022-09-08 17:10
Please provide more details as to what the issue is (in English please) so that I can assist.
My best guess is that you're using vue-cli-service and it's using an outdated version of electron-builder.
Closing ticket for now until further details are provided.

**Closed by mmaietta** 2022-09-08 17:10 UTC
Labels: nsis

**Comment by fyzn12** [comment] 2022-09-09 13:33
您好，我也遇到这个问题了，请问一下您是怎么解决的，一旦设置nodeIntegration: true,路由就失效

**Comment by BoxCode7** [comment] 2022-09-13 02:21
> 您好，我也遇到了这个问题，请问您是如何解决的，如果设置nodeIntegration: true,路由就可以了

目前觉得是webpack的问题，正在尝试找出问题

**Comment by BoxCode7** [comment] 2022-09-13 02:37
> 请提供有关问题所在的更多详细信息（请用英文），以便我提供帮助。 我最好的猜测是您正在使用 vue-cli-service 并且它使用的是过时版本的电子生成器。 暂时关闭票，直到提供更多详细信息。

Hello, I used the VUe-Admin-template (2.xx) as the basic template, and then built Electron (20.1.0) with Electron Builder (2.1.1).

1、git clone https://github.com/PanJiaChen/vue-admin-template.git
2、vue add electron-builder
3、package.json files electron、electron-devtools-installer、vue-cli-plugin-electron-builder Change to the latest version
4、vue.config.js 
```
pluginOptions:{
    electronBuilder:{
        nodeIntegration:true,
    }
}
```

**Comment by BoxCode7** [comment] 2022-09-13 02:44
> Please provide more details as to what the issue is (in English please) so that I can assist. My best guess is that you're using vue-cli-service and it's using an outdated version of electron-builder. Closing ticket for now until further details are provided.

Hello, I used the VUe-Admin-template (2.xx) as the basic template, and then built Electron (20.1.0) with Electron Builder (2.1.1).

1、git clone https://github.com/PanJiaChen/vue-admin-template.git
2、vue add electron-builder
3、package.json files electron、electron-devtools-installer、vue-cli-plugin-electron-builder Change to the latest version
4、vue.config.js
```
pluginOptions:{
    electronBuilder:{
        nodeIntegration:true,
    }
}
```

**Comment by mmaietta** [comment] 2022-09-13 16:25
So...what's the issue that is occurring? `nodeIntegration` is unrelated to electron-builder, it's not anything we set internally or logic that we have. That's specific to vue-cli-plugin it seems
