### ISSUE TITLE
Pass --deep param with codesign

### ISSUE THREAD

**Issue by KishanBagaria** [electron-userland/electron-builder#5002] opened 2020-05-22 19:48 UTC
* **Version**: 22.6.1

* **Electron Version**: 9.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: macOS

When I run `electron-builder build -m -c.extraMetadata.main build/mainbundle.js`, the following error is thrown:

```
  • electron-builder  version=22.6.1 os=19.4.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=packaged/builder-effective-config.yaml
  • skipped dependencies rebuild  reason=npmRebuild is set to false
  • packaging       platform=darwin arch=x64 electron=9.0.0 appOutDir=packaged/mac
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
    • signing         file=packaged/mac/foo.app identityName=Apple Development: redacted@gmail.com (redacted) identityHash=redacted provisioningProfile=none
  ⨯ Command failed: codesign --sign redacted --force --timestamp --options runtime --entitlements /Users/kishan/foo/node_modules/app-builder-lib/templates/entitlements.mac.plist /Users/kishan/foo/packaged/mac/foo.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/kishan/foo/packaged/mac/foo.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/kishan/foo/packaged/mac/foo.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
  stackTrace=
 Error: Command failed: codesign --sign redacted --force --timestamp --options runtime --entitlements /Users/kishan/foo/node_modules/app-builder-lib/templates/entitlements.mac.plist /Users/kishan/foo/packaged/mac/foo.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
 /Users/kishan/foo/packaged/mac/foo.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
 In subcomponent: /Users/kishan/foo/packaged/mac/foo.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler

   at ChildProcess.exithandler (child_process.js:303:12)
   at ChildProcess.emit (events.js:315:20)
   at maybeClose (internal/child_process.js:1051:16)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
                           From previous event:
   at processImmediate (internal/timers.js:456:21)
                           From previous event:
   at MacPackager.signApp (/Users/kishan/foo/node_modules/app-builder-lib/src/macPackager.ts:329:27)
   at MacPackager.doPack (/Users/kishan/foo/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
   at MacPackager.pack (/Users/kishan/foo/node_modules/app-builder-lib/src/macPackager.ts:130:7)
   at Packager.doBuild (/Users/kishan/foo/node_modules/app-builder-lib/src/packager.ts:444:9)
   at executeFinally (/Users/kishan/foo/node_modules/builder-util/src/promise.ts:12:14)
   at Packager._build (/Users/kishan/foo/node_modules/app-builder-lib/src/packager.ts:373:31)
   at Packager.build (/Users/kishan/foo/node_modules/app-builder-lib/src/packager.ts:337:12)
   at executeFinally (/Users/kishan/foo/node_modules/builder-util/src/promise.ts:12:14)
```

The issue is resolved if I manually patch `node_modules/app-builder-lib/electron-osx-sign/sign.js` and add `--deep` in this array:
https://github.com/electron-userland/electron-builder/blob/ee59eed4b48eff87786715a30d1865d9186c24d9/packages/app-builder-lib/electron-osx-sign/sign.js#L136-L139

This should either be there by default or we should be allowed to pass arbitrary CLI args to codesign.

**Comment by lutzroeder** [comment] 2020-05-23 02:28
Duplicate of #4969

**Comment by KishanBagaria** [comment] 2020-07-22 10:53
I'm still monkey patching `node_modules/app-builder-lib/electron-osx-sign/sign.js`. I can send a PR including `--deep` by default.

**Closed** 2020-09-27 11:59 UTC
Labels: backlog
