### ISSUE TITLE
SyntaxError: Unexpected token function

### ISSUE THREAD

**Issue by rockyCheung** [electron-userland/electron-builder#2986] opened 2018-06-06 06:08 UTC
* **Version**: 20.15.1

2.21.10

* **Target**: electron app

when I excute this command,then message like this-
$ build -mwl
/usr/local/lib/node_modules/electron-builder/node_modules/_read-config-file@3.0.1@read-config-file/out/main.js:72
async function readConfig(configFile) {
      ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (/usr/local/lib/node_modules/electron-builder/src/cli/cli.ts:10:1)
    at Object.args [as handler] (/usr/local/lib/node_modules/electron-builder/src/cli/cli.ts:45:5)
    at Object.runCommand (/usr/local/lib/node_modules/electron-builder/node_modules/_yargs@11.0.0@yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/electron-builder/node_modules/_yargs@11.0.0@yargs/yargs.js:1042:24)
    at Object.get [as argv] (/usr/local/lib/node_modules/electron-builder/node_modules/_yargs@11.0.0@yargs/yargs.js:957:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron-builder/src/cli/cli.ts:19:1)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)

**Comment by tbarela** [comment] 2018-06-08 17:54
I'm getting the same exact error, and trace output. Also using 20.15.1. 

Running as an npm script, "build --dir --x64" ( copied straight from another app which I built successfully a couple of nights ago )

*shrugs*

**Comment by pronebird** [comment] 2018-06-08 18:07
We have the same issue with node@6 on Travis:
https://travis-ci.org/jschr/electron-react-redux-boilerplate/jobs/389835142

**Comment by periode** [comment] 2018-06-10 16:59
Same issue here :/

Node 6.11 - NPM 3.10 - electron-build 20.15.1

**Comment by impeto** [comment] 2018-06-11 00:41
anyone been able to get this to work? I'm having the same issue...

**Comment by lhoezee** [comment] 2018-06-11 09:46
Same here. This works on one of my Macs and not the other.

**Mac not working**
NPM: 3.10.10
Node: 7.3.0
electron-build: 20.8.1

**Mac working**
NPM: 6.1.0
Node: 8.9.4
electron-build: 20.8.1

**On the Mac not working, I ran the following**
npm install -g npm
brew update
brew upgrade node

I'm now on node version 10.4.0 so it seems like you should have at least Node 8.9.*

I'm not sure what the proper way to upgrade node in Windows. @pronebird I have not had to upgrade node in Travis yet, but doing a quick search, it looks like you should be able to accomplish it.

**Comment by pronebird** [comment] 2018-06-11 10:16
@lhoezee I think it's simply a misconfiguration issue in the `read-config-file` package, which is converted from typescript to JavaScript. 

Since it's a generated source, its profile can be adjusted to expand the `async` keywords which aren't supported in node 6. 

At the same time `electron-builder` does not state a minimum `node` version in its `engines` section of `package.json`, so this would be good to add to set the right expectations.

I raised an issue at https://github.com/develar/read-config-file/issues/4

I am OK with dropping node 6 to be fair.

**Comment by rockyCheung** [comment] 2018-06-13 06:18
@lhoezee Thank you for your reply. I upgraded the Node version. The problem has been solved.

**Comment by pronebird** [comment] 2018-06-30 21:17
This issue has been fixed in `read-config-file`. Please verify with the latest release and close.

**Closed** 2018-07-01 06:17 UTC

**Comment by Celludriel** [comment] 2018-07-23 07:54
At home I had no problem, but when I did a npm install at work I get the following

C:\workspaces\react-electron-poc>npm isntall

> react-electron-poc@0.1.0 postinstall C:\workspaces\react-electron-poc
> install-app-deps

   please use as subcommand: electron-builder install-app-deps
   electron-builder version=20.24.5
SyntaxError: Unexpected token function
C:\workspaces\react-electron-poc\node_modules\read-config-file\out\main.js:72
async function readConfig(configFile) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (C:\workspaces\react-electron-poc\node_modules\app-builder-lib\src\util\config.ts:6:1)
    at C:\workspaces\react-electron-poc\node_modules\app-builder-lib\src\util\config.ts:36:40
    at next (native)
    at undefined.tryCatcher (C:\workspaces\react-electron-poc\node_modules\bluebird\js\release\util.js:16:23)
    at PromiseSpawn._promiseFulfilled (C:\workspaces\react-electron-poc\node_modules\bluebird\js\release\generators.js:97:49)
    at C:\workspaces\react-electron-poc\node_modules\bluebird\js\release\generators.js:201:15
From previous event:
    at getConfig (C:\workspaces\react-electron-poc\node_modules\app-builder-lib\out\util\config.js:182:17)
    at C:\workspaces\react-electron-poc\node_modules\electron-builder\src\cli\install-app-deps.ts:48:24
    at next (native)
From previous event:
    at installAppDeps (C:\workspaces\react-electron-poc\node_modules\electron-builder\out\cli\install-app-deps.js:174:17)
    at main (C:\workspaces\react-electron-poc\node_modules\electron-builder\src\cli\install-app-deps.ts:65:10)
    at Object.<anonymous> (C:\workspaces\react-electron-poc\node_modules\electron-builder\src\cli\install-app-deps.ts:70:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-electron-poc@0.1.0 postinstall: `install-app-deps`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-electron-poc@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kennydesmedt\AppData\Roaming\npm-cache\_logs\2018-07-23T07_51_06_498Z-debug.log

I tried upgrading to 20.24.5, but if it's a local problem is there a way to clean cache or something to get this running again ? Is it still a bug ?

my project setup: https://github.com/Celludriel/react-electron-poc I'm hoping it's reproducable on another machine

**Comment by amolngt** [comment] 2019-02-28 05:13
> Same here. This works on one of my Macs and not the other.
> 
> **Mac not working**
> NPM: 3.10.10
> Node: 7.3.0
> electron-build: 20.8.1
> 
> **Mac working**
> NPM: 6.1.0
> Node: 8.9.4
> electron-build: 20.8.1
> 
> **On the Mac not working, I ran the following**
> npm install -g npm
> brew update
> brew upgrade node
> 
> I'm now on node version 10.4.0 so it seems like you should have at least Node 8.9.*
> 
> I'm not sure what the proper way to upgrade node in Windows. @pronebird I have not had to upgrade node in Travis yet, but doing a quick search, it looks like you should be able to accomplish it.

Hello sir,

I am facing blank white screen  issue.. when electron runs for long time(2-3 days) .... my electron(v1.7.16) app going to run 365 days 24 hours...previously i was using ia32 package on 64bit... now m using x64 on 64 bit
node version v8.11.3
npm version 5.6.0
see following cmd....

electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName="CompanyName" --version-string.FileDescription=CE --win32metadata.requested-execution-level=requireAdministrator --version-string.ProductName="project_name"

i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

blank screen after one day..
Please Help

**Comment by amolngt** [comment] 2019-02-28 05:13
> @lhoezee I think it's simply a misconfiguration issue in the `read-config-file` package, which is converted from typescript to JavaScript.
> 
> Since it's a generated source, its profile can be adjusted to expand the `async` keywords which aren't supported in node 6.
> 
> At the same time `electron-builder` does not state a minimum `node` version in its `engines` section of `package.json`, so this would be good to add to set the right expectations.
> 
> I raised an issue at [develar/read-config-file#4](https://github.com/develar/read-config-file/issues/4)
> 
> I am OK with dropping node 6 to be fair.

> Same here. This works on one of my Macs and not the other.
> 
> **Mac not working**
> NPM: 3.10.10
> Node: 7.3.0
> electron-build: 20.8.1
> 
> **Mac working**
> NPM: 6.1.0
> Node: 8.9.4
> electron-build: 20.8.1
> 
> **On the Mac not working, I ran the following**
> npm install -g npm
> brew update
> brew upgrade node
> 
> I'm now on node version 10.4.0 so it seems like you should have at least Node 8.9.*
> 
> I'm not sure what the proper way to upgrade node in Windows. @pronebird I have not had to upgrade node in Travis yet, but doing a quick search, it looks like you should be able to accomplish it.

Hello sir,

I am facing blank white screen  issue.. when electron runs for long time(2-3 days) .... my electron(v1.7.16) app going to run 365 days 24 hours...previously i was using ia32 package on 64bit... now m using x64 on 64 bit
node version v8.11.3
npm version 5.6.0
see following cmd....

electron-packager . --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/icons/win/icon.ico --prune=true --out=release-builds --version-string.CompanyName="CompanyName" --version-string.FileDescription=CE --win32metadata.requested-execution-level=requireAdministrator --version-string.ProductName="project_name"

i updated electron --- v4.0.6
m using 64bit windows OS
Packaging app for platform win32 x64 using electron v1.7.16-- command while packaging

Please Help

**Comment by pronebird** [comment] 2019-02-28 09:18
@amolngt Hello sir, please open the new issue and stop spamming in the unrelated and closed one. Thank you sir.

**Comment by reZach** [comment] 2019-04-13 14:25
I wanted to also offer a solution, as I have been running in this issue myself. This for me was happening whenever I ran my electron-builder publish for mac (the windows was working every time), and was within Azure DevOps. This is my package.json for my project.

    {
        "name": "my-budget",
        "productName": "MyBudget",
        "version": "1.0.3-beta",
        "description": "Free, open source offline cross-platform budgeting solution built with Electron.",
        "scripts": {
            "build": "concurrently \"yarn build-main\" \"yarn build-renderer\"",
            "package-mac": "yarn build && electron-builder build --mac --publish onTagOrDraft",
            "package-win": "yarn build && electron-builder build --win --x64 --publish onTagOrDraft"
            //....
        }
    }

I found what I needed to add to my mac build pipeline was installing Node version 10 (this wasn't necessary for my windows pipeline, perhaps because the VM image already had it installed?). Here are my working mac/windows build pipelines for reference.

**Mac**

    trigger:
        - master
    
    pool:
        vmImage: 'macOS-10.14'
    
    steps:
    - task: NodeTool@0
        inputs:
            versionSpec: '10.x'
            displayName: 'Install Node.js'
      
    - task: Npm@0
        inputs:
            command: 'install'
        displayName: 'npm install'
    
    - task: Npm@1
        inputs:
            command: 'custom'
            customCommand: 'run package-mac'
        displayName: 'npm run package-mac'

**Windows**

    trigger:
        - master
    
    pool:
        vmImage: 'windows-2019'
    
    steps:
    - task: Npm@0
        inputs:
            command: 'install'
        displayName: 'npm install'
    
    - task: Npm@1
        inputs:
            command: 'custom'
            customCommand: 'run package-win'
        displayName: 'npm run package-win'
