### ISSUE TITLE
Filenames of dist

### ISSUE THREAD

**Issue by atypicalprogrammer** [electron-userland/electron-builder#966] opened 2016-12-02 19:13 UTC
Is it possible to specify what the filenames should be for each distro (before publishing)?

**Comment by develar** [comment] 2016-12-03 07:14
No. Why do you need?

**Comment by iggyZiggy** [comment] 2016-12-13 12:26
I also need it to define this for publishing, like {productName}-{version}-{osx|lin|win}.{ext}
or maybe it can be done already and I just don't know how?

**Comment by develar** [comment] 2016-12-13 14:17
@iggyZiggy The same question — Why do you need?

**Comment by iggyZiggy** [comment] 2016-12-13 15:12
because i would like it in that form when electron-builder publishes it to git, currently I have to go to git releases and rename each file after publishing

**Comment by develar** [comment] 2016-12-14 07:57
@iggyZiggy Sorry, but could you please provide example? What do you rename and why default naming policy is not suitable for you?

**Comment by iggyZiggy** [comment] 2016-12-14 15:11
I would just like more control on naming final files before they are pushed to github so I can set it up with the updater the way I want, but now there is a new issue with signing the app, for some reason I can't sign the app anymore. Can you please check this [issue](https://github.com/electron-userland/electron-osx-sign/issues/111)

**Comment by ahallicks** [comment] 2016-12-20 10:15
I would also like the ability to change the filename. Spaces always seem wrong in a filename so I convert mine to `{productName}-{version}-{osx|lin|win}-setup.{ext}` as it makes more sense to me to do so.

When using Squirrel this was fine as I could just rename it after the build had completely, but switching to NSIS means that the .yml file now has the original filename so I imagine the update won't work if I change it from the default as part of the build process.

**Comment by develar** [comment] 2016-12-20 10:17
Related to #925

**Comment by rodrigok** [comment] 2017-01-09 11:50
The hability to set the filename `template` would be awesome.

We are facing a problem with windows deploy to github cuz both x86 and x64 have the same file name.

**Comment by develar** [comment] 2017-01-09 11:52
@rodrigok On windows if you use NSIS (default target) you need to distribute the only installer. Not two.

> set the filename template would be awesome.

Will be implemented soon.

**Comment by rodrigok** [comment] 2017-01-09 13:09
@develar One installer with both architectures? That is great, but for now different names for binaries would solve the problem.

**Comment by develar** [comment] 2017-01-09 14:33
> One installer with both architectures

@rodrigok Yes, as stated https://github.com/electron-userland/electron-builder/wiki/NSIS#32-bit--64-bit

**Comment by rodrigok** [comment] 2017-01-09 15:50
@develar great. Is there some way to do that now?

**Comment by develar** [comment] 2017-01-09 15:52
@rodrigok What do you mean? filename template?

**Comment by rodrigok** [comment] 2017-01-09 16:05
@develar No, I want know if there is some way to build the x64 and x86 in the same NSIS installer today.

**Comment by develar** [comment] 2017-01-09 16:08
@rodrigok NSIS was designed as an awesome replacement of Squirrel.Windows and this feature is supported the very beginning. If it doesn't work as expected  – please file new issue.

**Comment by rodrigok** [comment] 2017-01-09 16:13
@develar Ok, and how should I proceed? Just compile one time in a x64 windows, or compile for both and on the same machine (on time with node 64 and one time with node 32) and x64 will be merged with x86?

That is not clear to me.

**Comment by develar** [comment] 2017-01-09 16:16
> That is not clear to me.

So easy as possible :): `build --ia32 --x64`
Of course, build machine should be x64. And if build machine is not windows, add `--win`.

**Comment by rodrigok** [comment] 2017-01-09 17:03
@develar That is amazing. Thanks, it's working for our windows and linux builds.

**Comment by mikew** [comment] 2017-01-26 13:32
@develar Are native modules supported for both x86 and x64 NSIS builds?

**Comment by develar** [comment] 2017-01-26 13:35
@mikew NSIS installer just contains both variants of packed app — so, it is not a question. If you build properly (i.e. to build for win you use win64).

**Comment by EtienneLem** [comment] 2017-01-26 15:52
> So easy as possible :): `build --ia32 --x64`

I’m building my app with the API (not the CLI), any idea how I can build for both? Can’t seem to find any examples or make it work with `builder.Platform.WINDOWS.createTarget()`

**Comment by develar** [comment] 2017-01-26 15:54
@EtienneLem https://github.com/electron-userland/electron-builder/issues/1156#issuecomment-274423471

**Comment by develar** [comment] 2017-02-08 07:42
Partially implemented for NSIS — https://github.com/electron-userland/electron-builder/issues/1222#issuecomment-278253043

**Comment by rodrigok** [comment] 2017-02-08 11:36
This is awesome 😄

**Closed** 2017-02-10 08:00 UTC
Labels: feature

**Comment by develar** [comment] 2017-02-10 08:41
`pkg`, `dmg` and `nsis` are supported. For other targets please file separate issues.
