### ISSUE TITLE
NSIS Installer optionally create desktop shortcut

### ISSUE THREAD

**Issue by mattlyons0** [electron-userland/electron-builder#1095] opened 2017-01-08 07:09 UTC
* **Version**: 11.1.1
Electron-auto-updater: 0.10.1

* **Target**: NSIS

A desktop shortcut is currently created from every version of the [NSIS installer script](https://github.com/electron-userland/electron-builder/blob/b6ae44937e1306c44b703d18913afde01ec66ee2/packages/electron-builder/templates/nsis/installSection.nsh#L140). Optimally this would be configurable. 

This is especially a problem since the autoupdater recreates the icon each time the application is updated. Meaning even if the user removes the desktop icon, it will be recreated by the installer each application update. Optimally the updater should look for the desktop shortcut and keep it if it already exists or not recreate it if it doesn't. Currently the updater will remove the icon (if possible) then put it back.

**Comment by mattlyons0** [comment] 2017-01-08 07:37
A hack I currently use without rewriting all the NSIS install scripts is to utilize the [NSIS Include](https://github.com/electron-userland/electron-builder/wiki/NSIS#custom-nsis-script) function with the following script:

`!macro customInstall
  WinShell::UninstShortcut "$desktopLink" #Removes pins using the shortcut
  Delete "$desktopLink" #Deletes the shortcut
  System::Call 'shell32::SHChangeNotify(i, i, i, i) v (0x08000000, 0, 0, 0)' #Refreshes the desktop
!macroend`

The last line is a weird hack, but if it doesn't run the shortcut will still appear on the desktop (even though it existed for literally milliseconds) until the user presses F5 on their desktop. This is worse than not removing the shortcut because until the user restarts or logs out the shortcut will remain and it will not be deletable or clickable. Deletion results in an error saying it doesn't exist (but still doesn't refresh) and clicking results in nothing happening.

**Comment by Zamiell** [comment] 2017-03-13 16:21
This is a possible duplicate of #1070 ?

**Comment by develar** [comment] 2017-06-16 17:52
Duplicates #1070

**Closed by develar** 2017-06-16 17:52 UTC
Labels: feature, nsis
