### ISSUE TITLE
Build failiing for Windows

### ISSUE THREAD

**Issue by jianfenkezhan** [electron-userland/electron-builder#3472] opened 2018-11-13 06:36 UTC
Error: Exit code: 255. Command failed: /Users/mujianguo/Library/Caches/electron-builder/wine/wine-3.0.3-mac-10.13/bin/wine Z:\Users\mujianguo\Library\Caches\electron-builder\wix\wix-4.0.0.5512.2\candle.exe -arch x64 -dappDir=Z:\Users\mujianguo\amp\desktop_app\release\win-unpacked -pedantic -wx project.wxs
wine: cannot find L"C:\\windows\\system32\\winemenubuilder.exe"
000b:err:wineboot:ProcessRunKeys Error running cmd L"C:\\windows\\system32\\winemenubuilder.exe -a -r" (2)
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
wine: Unhandled page fault on read access to 0x41e164d0 at address 0x4191c749 (thread 0027), starting debugger...
0027:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 32 44") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger

Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
0027:err:hid_report:process_hid_report Device reports coming in too fast, last report not read yet!
wine: Unhandled page fault on read access to 0x41e164d0 at address 0x4191c749 (thread 0027), starting debugger...
0027:err:seh:start_debugger Couldn't start debugger ("winedbg --auto 32 44") (1115)
Read the Wine Developers Guide on how to set up winedbg or another debugger

    at /Users/mujianguo/amp/desktop_app/node_modules/builder-util/src/util.ts:127:16
    at ChildProcess.exithandler (child_process.js:296:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:606:12)
From previous event:
    at execWine (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/wine.ts:64:8)
    at WineVmManager.exec (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/vm/WineVm.ts:13:12)
    at /Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/targets/MsiTarget.ts:81:14
From previous event:
    at MsiTarget.build (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/targets/MsiTarget.ts:43:44)
    at Function.buildAsyncTargets (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/platformPackager.ts:139:36)
    at WinPackager.packageInDistributableFormat (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/platformPackager.ts:118:24)
    at /Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/platformPackager.ts:113:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at WinPackager.pack (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/platformPackager.ts:110:95)
    at /Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/packager.ts:379:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/mujianguo/amp/desktop_app/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/mujianguo/amp/desktop_app/node_modules/graceful-fs/polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:155:5)
From previous event:
    at Packager.doBuild (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/packager.ts:345:24)
    at /Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/packager.ts:315:57
    at Generator.next (<anonymous>)
    at /Users/mujianguo/amp/desktop_app/node_modules/graceful-fs/graceful-fs.js:111:16
    at /Users/mujianguo/amp/desktop_app/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
From previous event:
    at Packager._build (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/packager.ts:284:133)
    at /Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/packager.ts:280:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at Packager.build (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/packager.ts:237:14)
    at build (/Users/mujianguo/amp/desktop_app/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (/Users/mujianguo/amp/desktop_app/node_modules/electron-builder/src/builder.ts:227:10)
    at then (/Users/mujianguo/amp/desktop_app/node_modules/electron-builder/src/cli/cli.ts:46:19)

**Comment by develar** [comment] 2018-11-13 14:00
To build MSI, better to use Windows. And better to no use MSI at all.

**Comment by develar** [comment] 2018-11-15 08:18
It is regression, fixed in upcoming 20.36.0.

**Comment by jianfenkezhan** [comment] 2018-11-15 08:32
thanks a lot for your reply, I am waiting...

**Closed** 2018-11-15 17:02 UTC
Labels: bug, msi

**Comment by gryzzly** [comment] 2018-11-22 16:02
Hey @develar this is just an information that also might be helpful for someone and for the sake of googlability I’m gonna post this here. After upgrading to all the latest `electron-builder` packages 3 days ago code signing stopped working for windows package (when running on macOS). The error was the following:
```
"error output:%!(EXTRA string=wine: failed to initialize: dlopen(/tmp/wine-stage/wine/usr/lib/wine/ntdll.dll.so, 258): image not found"
```

I noticed that `wine` that was installed by electron-builder had `mac-10.13` in its file path (`/wine/wine-3.0.3-mac-10.13/bin/`). Our CI was configured to use older version of macOS and on my dev machine I also had Sierra, which made local signing fail too. Updating CI config to use macOS 10.13 fixed signing problem for us.

**Comment by develar** [comment] 2018-11-22 16:07
@gryzzly Yes, sorry that this change was not reflected in changelog. I decided to stop using old outdated wine on CI servers and now the same wine used regardless is it local machine or not (since that time all major CI macOS providers support Sierra).

**Comment by murray971** [comment] 2018-12-14 22:20
hi- do you know how to get it working with macOS 10.12.6?

**Comment by BarryCarlyon** [comment] 2018-12-22 20:57
Using:

https://github.com/electron-react-boilerplate/electron-react-boilerplate

On 

macOS Mojava 10.14.1

Adjusting package.json to

`    "electron": "^4.0.0",
    "electron-builder": "^20.38.4",
`

Which solve the above error but presents a new issue

```
Error: someplace/your-project-name/node_modules/app-builder-bin/mac/app-builder exited with code 1
    at ChildProcess.childProcess.once.code (someplace/your-project-name/node_modules/builder-util/src/util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at MsiTarget.light (someplace/your-project-name/node_modules/app-builder-lib/src/targets/MsiTarget.ts:105:142)
    at someplace/your-project-name/node_modules/app-builder-lib/src/targets/MsiTarget.ts:89:16
From previous event:
    at MsiTarget.build (someplace/your-project-name/node_modules/app-builder-lib/src/targets/MsiTarget.ts:43:44)
    at Function.buildAsyncTargets (someplace/your-project-name/node_modules/app-builder-lib/src/platformPackager.ts:140:36)
    at WinPackager.packageInDistributableFormat (someplace/your-project-name/node_modules/app-builder-lib/src/platformPackager.ts:119:24)
    at someplace/your-project-name/node_modules/app-builder-lib/src/platformPackager.ts:114:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at WinPackager.pack (someplace/your-project-name/node_modules/app-builder-lib/src/platformPackager.ts:111:95)
    at someplace/your-project-name/node_modules/app-builder-lib/src/packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (someplace/your-project-name/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at someplace/your-project-name/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (someplace/your-project-name/node_modules/app-builder-lib/src/packager.ts:396:24)
    at someplace/your-project-name/node_modules/app-builder-lib/src/packager.ts:366:57
    at Generator.next (<anonymous>)
    at someplace/your-project-name/node_modules/graceful-fs/graceful-fs.js:99:16
    at someplace/your-project-name/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (someplace/your-project-name/node_modules/app-builder-lib/src/packager.ts:335:133)
    at someplace/your-project-name/node_modules/app-builder-lib/src/packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (someplace/your-project-name/node_modules/app-builder-lib/src/packager.ts:288:14)
    at build (someplace/your-project-name/node_modules/app-builder-lib/src/index.ts:59:28)
    at build (someplace/your-project-name/node_modules/electron-builder/src/builder.ts:227:10)
    at then (someplace/your-project-name/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-react-boilerplate@0.17.1 package-win: `electron-builder build --win --x64`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-react-boilerplate@0.17.1 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/barrycarlyon/.npm/_logs/2018-12-22T20_47_26_670Z-debug.log
```

nsis will build but msi will not.

(Also made sure to wipe `~/.wine` just in case)

Similar with `export USE_SYSTEM_WINE=true`

And same issue with another project.

In addition seems related to #3018

**Comment by CQBinh** [comment] 2019-01-08 11:12
Same on Mac OS 10.14
```
"electron": "^4.0.0",
 "electron-builder": "^20.36.0",
```

**Comment by jaredh159** [comment] 2019-01-12 18:43
upgrading to Mojave (10.14) and then upgrading Xcode to `10.1` fixed this for me.

**Comment by CQBinh** [comment] 2019-01-14 06:05
@jaredh159 Updated like you but no luck :(

**Comment by jacktang** [comment] 2019-03-31 16:02
I got the same issue :(
I've clone `https://github.com/electron-react-boilerplate/electron-react-boilerplate` on the ubuntu 16. I installed winehq and mono, and the error
```
[1] yarn build-renderer exited with code 0
  • electron-builder version=20.38.4
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=release/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=4.0.0 appOutDir=release/win-unpacked
  • building        target=MSI arch=x64 file=release/ElectronReact 0.17.1.msi
  • building        target=nsis file=release/ElectronReact Setup 0.17.1.exe archs=x64 oneClick=true perMachine=false
  ⨯ error: exit status 255
path: /usr/bin/wine
args: wine Z:\home\admin\.cache\electron-builder\wix\wix-4.0.0.5512.2\candle.exe -arch x64 -dappDir=Z:\home\admin\electron-react-boilerplate\release\win-unpacked -pedantic -wx project.wxs
output:
error output:0009:fixme:mscoree:ConfigFileHandler_startElement Unknown element L"loadFromRemoteSources" in state 4
0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed

github.com/develar/app-builder/pkg/util.Execute
	/Volumes/data/Documents/app-builder/pkg/util/util.go:74
github.com/develar/app-builder/pkg/wine.execWine
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:88
github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
github.com/alecthomas/kingpin.(*actionMixin).applyActions
```

**Comment by lacymorrow** [comment] 2019-04-29 20:39
These commands worked for me on Mojave 10.14.4
``
export WINEARCH=win32
export USE_SYSTEM_WINE=true
wine uninstaller
npx electron-builder -w
``

**Comment by jacktang** [comment] 2019-04-30 03:20
> I got the same issue :(
> I've clone `https://github.com/electron-react-boilerplate/electron-react-boilerplate` on the ubuntu 16. I installed winehq and mono, and the error
> 
> ```
> [1] yarn build-renderer exited with code 0
>   • electron-builder version=20.38.4
>   • loaded configuration file=package.json ("build" field)
>   • writing effective config file=release/builder-effective-config.yaml
>   • no native production dependencies
>   • packaging       platform=win32 arch=x64 electron=4.0.0 appOutDir=release/win-unpacked
>   • building        target=MSI arch=x64 file=release/ElectronReact 0.17.1.msi
>   • building        target=nsis file=release/ElectronReact Setup 0.17.1.exe archs=x64 oneClick=true perMachine=false
>   ⨯ error: exit status 255
> path: /usr/bin/wine
> args: wine Z:\home\admin\.cache\electron-builder\wix\wix-4.0.0.5512.2\candle.exe -arch x64 -dappDir=Z:\home\admin\electron-react-boilerplate\release\win-unpacked -pedantic -wx project.wxs
> output:
> error output:0009:fixme:mscoree:ConfigFileHandler_startElement Unknown element L"loadFromRemoteSources" in state 4
> 0009:err:mscoree:CLRRuntimeInfo_GetRuntimeHost Wine Mono is not installed
> 
> github.com/develar/app-builder/pkg/util.Execute
> 	/Volumes/data/Documents/app-builder/pkg/util/util.go:74
> github.com/develar/app-builder/pkg/wine.execWine
> 	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:88
> github.com/develar/app-builder/pkg/wine.ConfigureCommand.func2
> 	/Volumes/data/Documents/app-builder/pkg/wine/wine.go:43
> github.com/alecthomas/kingpin.(*actionMixin).applyActions
> ```

I solved the issue by run `wine uninstaller` on debian
