### ISSUE TITLE
NSIS Auto-Update

### ISSUE THREAD

**Issue by kunkinkan** [electron-userland/electron-builder#529] opened 2016-06-20 08:18 UTC
Creating this issue just to keep track of status, or when it is planned.

**Comment by black-snow** [comment] 2016-07-21 19:49
@develar @kunkinkan How's this gonna work? Will it be analogue to Squirrel?

**Comment by develar** [comment] 2016-07-22 05:16
@black-snow yes, only feed url will be changed in the user code. Auto-update API impl will be bundled.

**Comment by black-snow** [comment] 2016-07-22 21:38
Great. How are things going? Any help needed?

**Comment by atypicalprogrammer** [comment] 2016-07-25 06:36
Will this be better than Squirrel auto-update? I don't like with them that I cannot control the process; I should be able to allow the user to choose whether or not to update to the newest version, instead of forcing it. (And also; better security. Allow me access to the downloaded auto-update so I can for example compare md5 hashes, etc). So a method after downloading the update to verify it.

**Comment by black-snow** [comment] 2016-07-26 21:05
@atypicalprogrammer afaik *Squirrel* [does verify checksums](https://github.com/Squirrel/Squirrel.Windows/search?utf8=%E2%9C%93&q=checksum).

**Comment by atypicalprogrammer** [comment] 2016-07-26 21:28
@black-snow how do you figure? I'm talking about me providing a txt file with a checksum to compare with a downloaded file. It's a custom function that should be possible to provide better security. Something that is ran before the update itself is installed, simply a function that can cancel the further progression of install. The checksum validation I can add myself.

**Comment by develar** [comment] 2016-08-03 07:16
Started to work on this.

First version will support only Bintray:
* no rate limits (opposite to GitHub) to access latest version and version files. Rate limit free, no need to parse html or http headers, just use Rest API (opposite to GitHub — token requirement is not user-friendly).
* better security — Bintray reports file sha256/sha1 on version files request. We use it to verify downloaded file (because windows just sucks opposite to macOS — we cannot rely on code sign completely).
* `nsis-auto-updater` will be published to NPM, but only to provide flexibility — will be just prebundled on pack.

**Comment by zh99998** [comment] 2016-09-08 02:45
any good news now?

**Comment by mkazlauskas** [comment] 2016-09-12 18:10
It seems like work is being done. Please write a small readme and I'll be glad to do some testing.

**Comment by develar** [comment] 2016-09-12 18:19
@mkazlauskas Yes. It is nearly finished, but depends on a lot of small, but important things. I hope it  will be ready to test this week if no other critical NSIS issues (like #735) will be discovered.

**Comment by virror** [comment] 2016-09-22 14:51
Are there any docs for this yet so i can start developing this or are they coming when all is done?

**Comment by develar** [comment] 2016-09-22 15:36
> are they coming when all is done?

Yes.

**Comment by develar** [comment] 2016-09-22 15:39
Progress — nsis-updater module is finished, but not tested. I am going to modify electron.asar and replace squirrel implementation to nsis. I don't want to publish module to NPM to not complicate (i.e. you can use electron update API). You will be able to use rich promise-based and robust API instead of electron update API, but only as an alternative option.

**Comment by virror** [comment] 2016-10-03 13:07
Any timeframe for this? Would love to do the switch from Squirrel.windows to NSIS.

**Comment by develar** [comment] 2016-10-14 07:40
As I am macOS user and Windows is the worst OS in the world, testing is not easy.

If you brave enough and cannot wait, you can help me. Not expected to work.

1) Install `electron-auto-updater` as app dependency. Please see https://github.com/develar/onshape-desktop-shell/commit/501683723b1069aa799563336853fbfd7b71ec7b

2) Set `win.publish` to `["bintray", "github"]` (order is very important — `bintray` must be first). If you don't need to publish to GitHub, you can set publish only to bintray.

3) Use `import {autoUpdater} from "electron-auto-updater"` instead of `autoUpdater` from `electron`. `electron-auto-updater` works in the same way as electron bundled, it allows you to avoid conditional statements. Except that on Windows NSIS updater will be used.

4) Do not call `setFeedURL` on Windows. electron-builder automatically creates `.app-update.json` file for you on build in the `resources`. But if need, you can — set to BintrayOptions object. 
```js
 {
  provider: "bintray",
  owner: "actperepo",
  package: "no-versions",
}
```

Again — you don't need to call `setFeedURL`.

Not expected to work. But if you cannot wait, your early feedback is welcome.

**Comment by rsaccon** [comment] 2016-10-14 08:57
@develar, does or will NSIS auto-updater allow to be used with a custom built server ? I just built one (very simple, just a few lines of code, running on AWS lambda and using AWS S3 for downloads) for the mac squirrel auto-updater. Current NSIS auto-updater at current state seems to need either Bintray or Github as "Provider". Or is the idea to let users implement their custom "Provider" ?

**Comment by develar** [comment] 2016-10-14 09:05
@rsaccon As first step, only Bintray supported (it is free, no need to implement own server). Later any  http server will be supported.

**Comment by dharders** [comment] 2016-10-14 09:42
> it is free, no need to implement own server

@develar I think it's only free for **open-source** apps. 

I guess that's why @rsaccon asked, AFAICT the cheapest plan on bintray for closed source apps is $150/mth, which is quite expensive for a small independent dev.

Please correct me if I am wrong, cause I would love to be wrong on this. 

P.s. Thanks for all your hard work to get to this milestone!

**Comment by develar** [comment] 2016-10-14 09:54
@dharders Oh, Bintray pricing page is so bloody and confusing now. https://bintray.com/docs/usermanual/premium/premium_bintraypremium.html Hmm... it seems you are right. No one will restrict you to distribute commercial software, but it is not legal, as far as I see. I will contact Bintray to make it clear.

**Comment by rsaccon** [comment] 2016-10-14 10:09
@develar, @dharders yes, that is exactly the reason I was asking, their prices seem to be a bit high, compared with what I will pay to amazon for a custom built server

**Comment by rsaccon** [comment] 2016-10-14 11:10
@develar thanks for the info. Btw, bintray monthly pricing seems to be without actual charges for bandwidth and storage. And the second-most scary thing to me is the lock-in into a company I never heard of (before reading the source of NSIS updater) for a crucial part of existence for a small independant software developer

**Comment by virror** [comment] 2016-10-14 13:07
Ohh crap, so i can not use my own server to store updates? Then i cant use this since we are developing a commercial application and need to store all the stuff on out own servers. Any plan for implementing custom http servers and do you have any timeframe?

**Comment by develar** [comment] 2016-10-14 13:19
> i can not use my own server to store updates?

Of course you can. I just want magic to ensure that you can get auto-updates without any headache — setup own server.

> Any plan for implementing custom http servers and do you have any timeframe

Any static plain HTTP-server will be supported. It is will be implemented as soon as bintray approach will be proven. 

> timeframe

As far I see, it should be not postponed and implemented as part of this feature ;)

**Comment by virror** [comment] 2016-10-14 13:26
You are doing wonderful work, dont take my comment as criticism : )
This package has helped us loads, was just curious about the plans.

**Comment by willyb321** [comment] 2016-10-15 02:03
I'm definitely willing to help test auto-update for NSIS. I've been chomping at the bit to get rid of Squirrel for [my app.](https://github.com/willyb321/elite-journal) Do let us know if you need any help testing it!

**Comment by willyb321** [comment] 2016-10-15 09:30
Ok, I seem to have it 'working', however, it doesn't seem  to execute the `autoUpdater.quitAndInstall()` method. It'll download the updaate, just not go any further. It could also be that the update-downloaded event is not emitted?

**Comment by develar** [comment] 2016-10-15 16:33
@willyb321 Thanks, yes, working on it.

**Comment by develar** [comment] 2016-10-15 17:54
`electron-auto-updater` will be distributed as npm module and installed in a standard way. Maybe later we will bundled it somehow.  Because now we can use `yarn` instead of slow, unreliable and buggy npm.

**Comment by willyb321** [comment] 2016-10-15 21:17
@develar yeah, v0.0.2 emits the `update-downloaded` event and even installs it. However, it doesn't re-open the app? I may have missed a config option though.

**Comment by willyb321** [comment] 2016-10-16 21:20
@develar It would seem that one of those two commits, 89966d6f83e3173dd173b5d9f23c60d6b5f013f6 or b1ae7d5b3c00de2305d6f8b2cb1981ceb574b4d0 managed to break my GH_TOKEN env on appveyor - See [here](https://ci.appveyor.com/project/willyb321/elite-journal/build/1.0.283), and it was working perfectly fine previously. Its not too big a deal as bintray still seems to work but I just thought i'd let you know!

**Comment by develar** [comment] 2016-10-17 07:17
> However, it doesn't re-open the app

No. As on macOS. Or Skype/Chrome — update installed on quit silently. 

> it doesn't seem to remove the actual folder when it updates, it'll remove the contents, but not the folder itself

Will check.

Progress: Updater is still not polished and not considered as "working". Thanks to @willyb321 for test, but I was busy to fix various publish issues.

**Comment by willyb321** [comment] 2016-10-17 10:48
> No. As on macOS. Or Skype/Chrome — update installed on quit silently

Ok, I can agree with that.  
> Will check.

Thanks!  
Also, its no problem for me to test, and its been working remarkably well in my testing!

**Comment by pwdl** [comment] 2016-10-21 13:29
I just wanted to check the status of this upgrade solution. Is any support required for testing or anything else?

**Comment by develar** [comment] 2016-10-21 13:33
@pwdl As @willyb321 confirmed, Bintray works correctly. You can start to use it in your project and report here if something doesn't work. I still cannot state that Bintray auto-update works because I haven't tested it using real-world app :)

**Comment by pwdl** [comment] 2016-10-21 14:13
Thanks @develar. Completely understood. The $150/month price point for Bintray would certainly make it an unviable option for me. What would be required to develop the auto-update via any http-server via API (or similar) solution? Is it understood, but just needing prioritised and developed or are there unknowns/hurdles to overcome?

**Comment by develar** [comment] 2016-10-21 14:23
> just needing prioritised and developed

Yes. No unknowns/hurdles to overcome. I really hope it will be fixed this month.

**Comment by willyb321** [comment] 2016-10-22 01:41
@pwdl just to back @develar up, I'm still using NSIS and its working flawlessly from what I've seen! - Smaller sizes, no delta, RELEASES, nice and simple since its using same api as normal electron auto-updater. Another plus (for me at least), is the fact that I don't have to host my own updates, which is a problem for me (200kB/s upload!). Sure, bintray could use some work on its pricing, but since my stuff is basically 99% open source/not commercial its not a problem for me at least!  
When I was using squirrel, I had to use external module for downloading the updates from github - which seems to be quite slow here at least. (For releases anyway)

**Comment by FelikZ** [comment] 2016-10-22 19:04
Hosting yourself is not that difficult, cloud instances now very very cheap, and it is possible to find one for 5$ or even cheaper with 1Tb+ traffic.

Awaiting hard self hosted auto-updates!

**Comment by mkazlauskas** [comment] 2016-10-22 20:51
@FelikZ That is true, especially with Docker

**Comment by willyb321** [comment] 2016-10-26 05:02
@develar with commit f69d2025fe56c3825f681819fabf7cf78772d01d , my app throws an error each time it loads, because it can't find app-update.yml - the old .app-update.json is still there however.

**Comment by develar** [comment] 2016-10-26 07:03
@willyb321 Please update `electron-auto-updater` according to `electron-builder` releases. Currently, please use `0.0.4` version (`0.1.0`+ requires new version of electron-builder, not yet published).

**Comment by willyb321** [comment] 2016-10-26 08:02
@develar Ah, I see. Wil do!

**Comment by develar** [comment] 2016-10-29 08:58
It seems currently on Windows you must explicitly call quitAndInstall. On macOs you don't need — update correctly installed on quit. It is not good — it will be fixed in the `electron-auto-updater`.

**Comment by develar** [comment] 2016-10-29 10:05
electron-auto-updater 0.3.0 is published — now update automatically installed on quit in the same way as on macOS. Please note – electron-builder 7.15.0+ is required.

**Comment by develar** [comment] 2016-10-31 06:53
> it doesn't seem to remove the actual folder when it updates, it'll remove the contents, but not the folder itself

Yes, directory of version that is removed by new version — will be empty, but not removed. I have tried to fix it, but no luck because it is *** Windows. Since it is very minor issue, it will be not fixed for now. If you can help — you are welcome.

**Comment by artpol** [comment] 2016-10-31 21:17
Please tell me, what are the best way to publish updates for commercial software with electron-builder today? if only gitHub, is there manual for what file structure i should commit for electron-auto-updater? (bintray - I do not consider, very expensive for me)

**Comment by elronalds** [comment] 2016-10-31 22:38
Yes, I would like to know the same @artpol.  As Squirrel.Windows is going to be depreciated and no longer enhanced what are the options besides bintray.  I'd like a self-hosted option.  Would it be possible to use something like https://github.com/ArekSredzki/electron-release-server ?

**Comment by elronalds** [comment] 2016-10-31 22:58
Yes, I understand that @virror - I wasn't complaining.  I was just suggesting that `electron-release-server` might be a viable option for the self-hosted aspect with the necessary changes.

**Comment by develar** [comment] 2016-11-01 10:47
`generic` provider is supported (not yet pushed and released, electron-auto-updater module is not yet support it).

if 

```json
publish: {
   "provider": "generic",
   "url": "https://develar.s3-website.eu-central-1.amazonaws.com/test",
}
```

specified, then you will get

`app-update.yml` in the app resources (this file is internal, you don't need to be aware of it):

```yaml
provider: generic
url: 'https://develar.s3-website.eu-central-1.amazonaws.com/test'
```

Keep in mind  — you can specify several publish providers, artifacts will be published to all specified, but only the first will be default for auto update (i.e. you don't need to call `setFeedURL` (see about it above — https://github.com/electron-userland/electron-builder/issues/529#issuecomment-253731088)). 

and `latest.yml` This file you must be uploaded in the same directory where `YourAppName Setup 1.0.0.exe` is uploaded.

```yaml
version: 1.1.0
file: TestApp Setup 1.1.0.exe
sha2: 
```

About security — Windows code signing doesn't "work"/help because until all apps on Windows are not signed and unsigned app is not blocked — signed or not signed your app does't matter. Doesn't matter — poor windows user get used to "shut up, windows, let me run app!!!". And checksum can be spoofed as well. Later we will use your public code singing certificate to verify that downloaded exe is really produced by you (since Windows cannot do this work). But it will be not implemented right now.

**Closed** 2016-11-01 15:26 UTC
Labels: enhancement, nsis

**Comment by develar** [comment] 2016-11-01 15:28
electron-builder 7.17.0+ and electron-auto-updater 0.4.0+ support generic http server. Will be released in 20 minutes.

Unit tests passed (amazon s3 was used) but integration test was not yet performed. You are welcome to test it and report issues.

Github will be supported as part of separated issue (feel free to  create this issue :)). This issue will be closed.

In the future electron-builder will support publishing to S3.

Generic provider supports channels — i.e. by default `latest` (`latest.yml`) but you can set `channel` to any valid file name (e.g. `beta`) and upload corresponding file. `electron-auto-updater` uses it as is — i.e. there is no any meta information about channels — file named as channel will be downloaded and used in a general way. Maybe sounds cryptic and low-level, but docs will be added soon :)

**Comment by virror** [comment] 2016-11-01 15:29
Will try for sure as soon as im done with my current task : )

**Comment by develar** [comment] 2016-11-01 15:32
Security note — portable way to verify signed app is found and will be implemented, but cannot promise when. In any case sha256 checksum is required. Checksum can be spoofed (if your http server is hacked), so, checksum is not enough to protect users.

**Comment by rsaccon** [comment] 2016-11-01 16:02
That looks great, I look forward to migrate my squirrel thing to NSIS autoupdate.  Now I am thinking whether it would be be possible  (or whether it makes sense at all) to use this auto updater also for mac, instead of the squirrel thing (which is not so flexible, for example it has very specific requirements for the release server). Then just using just simple Amazon S3 based release hosting for mac and windows, without need for a special release server, for really be great.

**Comment by develar** [comment] 2016-11-01 16:36
> without need for a special release server, for really be great.

Yes, you are right. Current squirrel.mac is a shame since special server is required. I cannot say that it will be fixed any time soon.

**Comment by joshualambert** [comment] 2016-11-01 21:29
Wow, @develar you are awesome. :) I've spent the last 3 weeks hacking together Squirrel.Windows not realizing a better solution is right around this corner. Only possible issue I see here is with the signing for Windows. We bought an EV cert complete with the special USB key and everything needed for signing. Will this approach support signing with an EV cert utility?

**Comment by develar** [comment] 2016-11-02 06:19
> Will this approach support signing with an EV cert utility?

To sign — please use [certificateSubjectName ](https://github.com/electron-userland/electron-builder/wiki/Options#WinBuildOptions-certificateSubjectName) For verification procedure (check exe after download) it doesn't matter (since windows tool will be used).

**Comment by zh99998** [comment] 2016-11-02 08:18
how to get latest.yml with github provider
I only get a Setup exe in my release draft after `npm run dist` call.

**Comment by develar** [comment] 2016-11-02 08:59
@zh99998 github as update server is not supported currently and no workaround because of http://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo (not possible to use GitHub releases as generic http server) It will be fixed tomorrow (could you please create issue ;)?)

**Comment by zh99998** [comment] 2016-11-02 09:16
well then how to use generic provider
for amazon s3 or other s3-like storage REST API, how to specific authentication key (or I have to make it globally writable)?

**Comment by develar** [comment] 2016-11-02 09:19
@zh99998 as stated, "In the future electron-builder will support publishing to Amazon S3." For generic provider no publish — you upload files manually (latest.yml and setup exe). electron-auto-updater just downloads files using plain HTTPS.

**Comment by zh99998** [comment] 2016-11-02 10:34
does nsis delta update planned? or have to download full size package each version update

**Comment by develar** [comment] 2016-11-02 10:36
@zh99998 Delta updates planned, but not in the short term. Since we use lzma2 compression, size of installer ~ 30MB.

**Comment by mikew** [comment] 2016-11-02 20:17
Where exactly is Squirrel.Windows being deprecated? Is it electron, or electron-builder?

Is there a reference server for this new implementation?

Will Mac and Windows require two different solutions?

What does this deprecation solve?

**Comment by joshualambert** [comment] 2016-11-02 21:22
I've got the app built using NSIS now thanks to the latest Electron builder and the wonderful efforts of @develar. Question I have now is what replaces NUTS as the update server, and is there any docs available on how to do it?

**Comment by zh99998** [comment] 2016-11-03 04:23
how to use this updater? 
I tried autoUpdater in electron docs, but seems it still use Squirrel as backend.

```JavaScript
autoUpdater.checkForUpdates()
#=> Update URL is not set
autoUpdater.setFeedURL("...")
autoUpdater.checkForUpdates()
#=> Can not find Squirrel
```

in my package.json
```json
{
  "provider": "generic",
  "url": "..."
}
```

**Comment by develar** [comment] 2016-11-03 07:34
> Where exactly is Squirrel.Windows being deprecated? Is it electron, or electron-builder?

electron-builder

> Is there a reference server for this new implementation?

Of course not. Use any https-compliant web server. Just download `latest.yml` and setup exe. That's all.

> Will Mac and Windows require two different solutions?

As commented above, Squirrel.Mac is a nightmare because requires special server. If you mean application side — no. No — `electron-auto-updater` can be used on macOS as well, you don't need to use different API. See above "works in the same way as electron bundled, it allows you to avoid conditional statements. Except that on Windows NSIS updater will be used.".

> What does this deprecation solve?

User's WTF and real needs  https://github.com/electron-userland/electron-builder/issues/472#issuecomment-225656393

**Comment by develar** [comment] 2016-11-03 07:44
> what replaces NUTS as the update server, and is there any docs available on how to do it?

NUTS and other servers are required only and only because of *** Squirrel.mac design. Neither Squirrel.Windows, nor electron-builder NSIS requires special server. Any, any https-compliant web server can be used.

Your question is — will electron-auto-updater supports NUTS and other update server (special support is required to avoid configuration on your side — i.e. electron-auto-updater will support default configuration of update server (again, special server is required only and only for macOs) to grab latest version and artifact).

The answer is — I will try to get rid of Squirrel.Mac special server requirement using local http server hack. But cannot promise when.

But in any case yes — probably NUTS and other servers will be supported by electron-auto-updater.

**Comment by develar** [comment] 2016-11-03 07:45
@zh99998 Please see https://github.com/electron-userland/electron-builder/issues/529#issuecomment-253731088

**Comment by develar** [comment] 2016-11-04 06:08
https://github.com/electron-userland/electron-builder/wiki/Auto-Update

**Comment by keverw** [comment] 2016-11-04 06:29
Nice to see progress on a better updater on Windows. Does this one handle Mac too? I'm guessing not, and you'd have to use setFeedURL for the Mac one built in. Then it sounds like no updater really supports Linux right now, but i think the recommendation is just use the builtin package manager on those systems.

**Comment by develar** [comment] 2016-11-04 06:31
> Does this one handle Mac too?

Not yet. In the future `setFeedURL` will be not required on macOs as well.

> no updater really supports Linux right now

Yes. AppImage supports updates, but it is not yet supported on electron-builder side. The Ubuntu Store looks promising, but Snaps not yet supported.

**Comment by keverw** [comment] 2016-11-04 06:37
> Not yet. In the future setFeedURL will be not required on macOs as well.

Nice! A unified system for both sounds awesome then. Simplify the updater server requirements. Sounds like the goal is mainly just being able to plop up files on a plain http server. So love that :)

> Yes. AppImage supports updates

Interesting. Just looked up their site. Looks cool. Seems to not be Electron specific but interesting.

**Comment by develar** [comment] 2016-11-10 10:41
Great news — soon you can throw away Nuts any other *** update servers and use plain generic http server for macOs. Linux AppImage update is coming as well. https://github.com/megahertz/electron-simple-updater/issues/4

**Comment by MaKleSoft** [comment] 2016-11-10 13:49
@develar That's exciting news! I wonder what you mean by 'plain generic http server though'? Do you mean a static file server serving the release files?

**Comment by develar** [comment] 2016-11-10 13:52
> Do you mean a static file server serving the release files?

Yes. You don't need to use special electron update server.

**Comment by MaKleSoft** [comment] 2016-11-10 14:04
@develar Sweet! Is there documentation somewhere on how this works exactly, i.e. file name conventions and such?

**Comment by develar** [comment] 2016-11-10 14:21
@MaKleSoft Please note — in my message stated "soon"/"will" and link to opened issue ;) So, stay tuned (https://github.com/electron-userland/electron-builder/wiki/Auto-Update will be updated and linked issue will be closed).

**Comment by MaKleSoft** [comment] 2016-11-10 14:56
@develar Haha, sorry. Got a little overexcited there :)

**Comment by MTRNord** [comment] 2016-11-11 14:36
Is it just me? And why does it happen? (new issue?) I do get following when I try the autoudater with nsis:

`Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\Programiles (x86)\Lornsenschule Vertretungsplan\resources\app-update.yml'`

**Comment by develar** [comment] 2016-11-11 14:48
@MTRNord Please specify electron-builder version.

**Comment by MTRNord** [comment] 2016-11-11 14:48
@develar it is 6.4.0

**Comment by develar** [comment] 2016-11-11 14:50
@MTRNord As stated, "Please note – electron-builder 7.15.0+ is required." I suggest to use `8.2.0`.

**Comment by MTRNord** [comment] 2016-11-11 14:50
ah ok than I try to update. I did not see that. Sorry

**Comment by develar** [comment] 2016-11-11 14:51
@MTRNord Please consider to use https://sibbell.com/ ;)

**Comment by MTRNord** [comment] 2016-11-11 14:53
@develar yeah I will use that :)

**Comment by consense** [comment] 2016-11-22 10:08
As far as I can see the current architecture pull the release channel option out of the app-update.yml so the channel is hardcoded for the app version the user currently has installed.
It would be amazing if one could control the channel at runtime (e.g. when initializing electron-auto-updater) so one could dynamically assign alpha/beta test capabilities within a userSettings API call the electron app makes against the backend.

**Comment by develar** [comment] 2016-11-24 16:33
@consense Of course not. Do whatever you want — please see https://github.com/electron-userland/electron-builder/wiki/Auto-Update — call `setFeedURL` and pass you desired options (see example about BintrayOptions in the docs).

**Comment by mengfoobar** [comment] 2016-11-27 02:28
@develar  Thanks for the hard work mate. But I've been reading through this ticket and wiki, and still can't seem to quite figure out how this all works.

Would I just need to upload the .exe installer file created from electron-builder to a http server? Where do I specify the update url in the code if i dont set the feedUrl (in .build.publish.url)?

thanks!

**Comment by zh99998** [comment] 2016-11-27 03:08
is there any way to get update download progress or speed?

**Comment by kevinphelps** [comment] 2016-11-27 21:56
@mengfoobar I think I can help. You need to upload the `.exe` and 'latest.yml`. The `latest.yml` file will be generated with installer if you have `.build.publish` configured; otherwise, it shouldn't be too difficult generate it yourself.

If you don't configure `.build.publish` (in package.json), you can set the url using:

``` JavaScript
autoUpdater.setFeedURL({
    provider: 'generic',
    url: 'https://example.com/path/to/upload/directory'
});
```

**Comment by kevinphelps** [comment] 2016-11-27 22:04
@develar Thanks for all the work you did on this!

I don't know if this will help anyone else, but I wrote a small node server that basically proxies the latest release on GitHub Releases and it works great with this auto updater. And you can run it for free on Heroku. I set it up so that I can upload the installer and `latest.yml` to GitHub Releases and point the auto updater at the Heroku app.

If anyone is interested, I can package the code and publish it to npm for you to try!

**Comment by mengfoobar** [comment] 2016-11-28 02:59
@kevinphelps hi Kevin, thanks for trying to help! Unfortunately, i still can't get it to work after following what you said...
The "update-available" event is now triggered, but immediately i get an "error" event with the message:

{"code": "MODULE_NOTE_FOUND"} 

For the record, I'm using electron-auto-updater 0.61, and am using 'generic' provider + amazon s3. Anyone else have this problem?

**Comment by mengfoobar** [comment] 2016-11-28 04:20
okay i figured it out, i think 0.6.1 npm build for electron-auto-updater is missing a dependency (fs-extra). For anyone having this problem, just used 0.6.0 and it'll be good. just a fyi @develar 

and thanks again @kevinphelps , advice was perfect ;)

**Comment by develar** [comment] 2016-11-28 07:29
@mengfoobar Fixed in 0.6.2.

**Comment by develar** [comment] 2016-11-28 07:34
> I wrote a small node server that basically proxies the latest release on GitHub Releases and it works great with this auto updater

@kevinphelps GitHub supported directly. Why do you need to setup proxy server?

> is there any way to get update download progress or speed?

@zh99998 

1. `checkForUpdates` returns `Promise<UpdateCheckResult>`
2. `UpdateCheckResult` may contain property `downloadPromise` Null if no update.
3. Well... yes, you cannot currently get progress or speed from promise. Please file issue about it.

**Comment by kevinphelps** [comment] 2016-11-28 07:39
@develar Oh. I needed it because the repo is private.

**Comment by Positive07** [comment] 2016-11-29 02:44
Just some simple questions. Suppose I'm using Github releases (public open source repo) to deliver updates (I also have Mac files uploaded but currently no REST API).

What should I do in my Electron code? Do I need to setup `autoUpdater.setFeedURL` if I understood right, that is only needed on Mac, so if I wanted to support Mac I would check if `os.platform` is `darwin` and only then `setFeedURL`?

Thanks from your hard work, it has simplified everything a lot.

**Comment by develar** [comment] 2017-01-14 18:27
Miracles happens. Serverless macOS auto-update is implemented in the electron-builder 11.3.0 and electron-auto-updater 1.0.0 https://github.com/electron-userland/electron-builder/issues/1089#issuecomment-272643033

**Comment by rsaccon** [comment] 2017-01-14 19:25
@develar thanks to make the miracle happen ! It is like Santa Claus came for a second round ! Look forward to rip out my own hackish serverside workarounds.

**Comment by develar** [comment] 2017-01-24 16:41
`electron-auto-updater` renamed to `electron-updater`

**Comment by Timer** [comment] 2017-01-25 05:11
Does `electron-updater` work with https://github.com/GitbookIO/nuts?

**Comment by willyb321** [comment] 2017-01-25 05:16
@Timer nah you dont need it, its serverless. have a look [here](https://github.com/electron-userland/electron-builder/blob/master/docs/Auto%20Update.md)

**Comment by Timer** [comment] 2017-01-25 05:40
I'd like to configure nuts to be used as a generic https server if possible -- my repos are private & I still like having my artifacts published on github.

**Comment by kevinphelps** [comment] 2017-01-25 10:11
@Timer, I have written a node Express server that does that. I can post the code if you want.

**Comment by Timer** [comment] 2017-01-25 17:02
That would be much appreciated @kevinphelps; it would save me quite a bit of time! Thanks! 💯

**Comment by develar** [comment] 2017-01-25 17:28
@Timer for your case I suggest amazon s3 — more robust because you don't need to maintain own server / https cert. You can be sure always that it works and uptime 100%. Yes, currently artifacts are not uploaded automatically, but you can file issue  / use another tool to publish artifacts.

**Comment by Timer** [comment] 2017-01-25 18:14
@develar perhaps if I run into some free time I could make a small tool to do that -- but I was planning on using heroku anyway which is managed and has https.

I still don't believe the docs are very clear explaining what is required from a generic server... Do I just need to host `latest.yml` and `latest-mac.json` at the root of the generic URL I specify with the binaries available at the provided links in those files (e.g. can I have all assets in the same s3 bucket, e.g. `s3.amazonaws.com/example/latest-mac.json` & `s3.amazonaws.com/example/latest-mac-*.zip`)?

**Comment by develar** [comment] 2017-01-25 19:10
> Do I just need to host

Yes. Nothing more. Create any path as you want in the bucket (e.g. `test` in the bucket `develar`) and 

```
{
  provider: "generic",
  url: "https://develar.s3.amazonaws.com/test",
}
```

**Comment by Timer** [comment] 2017-01-26 00:42
Can the link in `latest-mac.json` be relative or does it have to be absolute?

**Comment by develar** [comment] 2017-01-26 06:54
@Timer Squirrel.Mac issue. Electron-builder cannot fix it.

**Comment by Timer** [comment] 2017-01-26 06:58
Neat @develar, thanks for all your help!
I took the time to make a small app that mirrors github releases to S3, and I modify the JSON file for the new URL path. 😄

**Comment by aj-ptw** [comment] 2017-01-26 12:50
@kevinphelps would love to see the Heroku app you made! My repos are private. Thanks for any and all time!

**Comment by aj-ptw** [comment] 2017-01-26 13:19
@develar is there a way to include release notes?

**Comment by develar** [comment] 2017-01-26 13:20
@aj-ptw Please file new issue about it.

**Comment by kevinphelps** [comment] 2017-01-26 15:13
@Timer @aj-ptw I extracted my update server code in this repo: https://github.com/kevinphelps/electron-update-server. Let me know if you have any questions. Sorry if this seems overbuilt, I extracted it from my update/login/api server. It has all the groundwork for adding additional endpoints.

**Comment by Timer** [comment] 2017-01-26 16:02
Awesome @kevinphelps 💯!

@aj-ptw I change it automatically -- see https://github.com/Timer/electron-release-s3-sync/blob/master/src/index.js#L97-L105.
If you just want to sync your latest release with s3, you can install `electron-release-s3-sync` and run it with the appropriate env vars (GH_USER, GH_TOKEN, GH_ORG, GH_REPO, AWS_BUCKET, AWS_BUCKET_URL).
Looks something like this:
![](https://puu.sh/tAEPc/c3a018d3ad.png)

e.g.
```bash
$ yarn add electron-release-s3-sync --dev
- or -
$ npm i electron-release-s3-sync --save-dev

$ ./node_modules/.bin/electron-release-s3-sync
```

**Comment by sylhero** [comment] 2017-02-06 19:01
I'm using `"electron": "^1.4.15"` `"electron-builder": "^12.0.3"` and `electron-updater": "^1.4.2"`. I used the 
`
autoUpdater.setFeedURL({
        provider: 'generic',
        url: 'https://s3/release'
    });
`
but I don't see the latest.yaml generated unless I config the build.publish. Anyone has the same issue?

**Comment by bartekczyz** [comment] 2017-02-10 13:15
@sylhero I've experienced the same thing, updating electron-builder to 13.x.x ( 13.3.1 in my case ) helped.

**Comment by ccorcos** [comment] 2017-04-19 19:20
where do these json and yml files come from?

**Comment by black-snow** [comment] 2017-04-20 13:01
@ccorcos which files do you mean? `latest.yml`?

**Comment by ccorcos** [comment] 2017-04-20 17:43
yes: `latest.yaml` and `latest.json`
