### ISSUE TITLE
Travis NSIS EPIPE error

### ISSUE THREAD

**Issue by ghost** [electron-userland/electron-builder#1978] opened 2017-08-22 16:23 UTC
* **Version**: 19.24.1

* **Target**: Windows, Linux | ia32, x64

I have the following .travis.yml, and I get the following error in the Travis log.

```
dist: trusty
sudo: required

language: node_js
node_js: '8'

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

os:
  - linux

cache:
  directories:
    - node_modules
    - "$HOME/.cache/electron"
    - "$HOME/.cache/electron-builder"
    - "$HOME/.npm/_prebuilds"

addons:
  apt:
    packages:
    - libsecret-1-0

before_install:
  - mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.2.0/git-lfs-linux-amd64-2.2.0.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1 && /tmp/git-lfs/git-lfs pull
  - curl -L https://yarnpkg.com/latest.tar.gz | tar xvz && mv dist $HOME/.yarn
  - export PATH="$HOME/.yarn/bin:$PATH"
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y && sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF && echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list && sudo apt-get update && sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono wine1.8 gcc-multilib g++-multilib icnsutils graphicsmagick xz-utils

install:
  - yarn

script:
  - yarn dist --linux --win --ia32 --x64

before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
```

```
Building NSIS installer
  Packaging NSIS installer for arch x64
  Packaging NSIS installer for arch ia32
Downloading nsis-3.0.1.13, please wait
Downloading nsis-resources-3.1.0, please wait
Error: write EPIPE
    at _errnoException (util.js:1041:11)
    at WriteWrap.afterWrite (net.js:858:14)
error Command failed with exit code 1.
```

**Comment by develar** [comment] 2017-08-22 16:32
I am sure that it is temporary problem.

Anyway, I recommend you to remove `sudo: required`, `- sudo add-apt-repository ppa:ubuntu-wine/ppa ....` and just use our docker image — https://github.com/electron-userland/electron-builder/wiki/Docker

**Comment by moriczgergo** [comment] 2017-08-22 16:39
Hmmm... could you provide a .travis.yml using that?

**Comment by develar** [comment] 2017-08-22 16:47
@cawa-93 could you please provide your Travis config?

**Comment by develar** [comment] 2017-08-22 16:48
Please see https://github.com/electron-userland/electron-builder/issues/1751#issuecomment-312809154

**Comment by moriczgergo** [comment] 2017-08-22 16:51
Does that user docker?
I've edited that .travis.yml because I don't need OSX builds.

I've added the debug env value and here's the new output:
https://travis-ci.org/moriczgergo/musicsort

**Comment by develar** [comment] 2017-08-23 06:32
I recommend you to build windows on macOS, exactly as in the provided sample travis file. To avoid any issues with Linux Zoo. Is it suitable for you?

**Comment by nukeop** [comment] 2018-02-08 18:05
I'm having the exact same problem with the newest release of electron-builder on travis. What is the cause?

**Comment by develar** [comment] 2018-02-08 18:47
@nukeop Please try 20.0.2 and file a new issue if need.

**Comment by nukeop** [comment] 2018-02-08 21:34
Didn't fix it, the 20.0.2 version of the builder still crashes with the same error.
```
  • downloading               path=/home/travis/.cache/electron-builder/nsis/nsis-resources-3.3.0 url=https://github.com/electron-userland/electron-builder-binaries/releases/download/nsis-resources-3.3.0/nsis-resources-3.3.0.7z
Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
```

**Comment by globaltommy** [comment] 2018-02-09 14:29
I have the same issue :(

**Comment by nukeop** [comment] 2018-02-13 18:03
Can this be reopened? I have no problems with building on Windows, but unfortunately travis doesn't offer windows machines.

**Comment by develar** [comment] 2018-02-13 20:13
@nukeop Please try 20.0.4 and set env `DEBUG=electron-builder` and attach log of the terminal output.

**Comment by nukeop** [comment] 2018-02-13 20:19
According to release notes nothing related to Windows builds has changed since 20.0.2 where the issue still existed.

**Comment by nukeop** [comment] 2018-02-13 21:39
Travis output (highlighted relevant line):

https://travis-ci.org/nukeop/nuclear/jobs/341145410#L4999

**Comment by globaltommy** [comment] 2018-02-14 09:34
I can build on Ubuntu but when trying to build windows target on centos7 I get exactly same exception. I suspect it's one of the dependencies but haven't had luck fixing it yet.

**Comment by mrdev023** [comment] 2018-03-30 07:25
I have the same issue with gitlab-ci

**Comment by probonopd** [comment] 2018-04-19 06:28
Same here, building Windows on Travis CI:
https://travis-ci.org/probonopd/readium-desktop/builds/368486050#L2318

**Comment by moriczgergo** [comment] 2018-05-06 08:04
This is not relevant anymore for me. Feel free to close it if you want to.

**Comment by develar** [comment] 2018-05-06 08:42
@moriczgergo Why not relevant?

**Comment by moriczgergo** [comment] 2018-05-07 20:10
@develar I have deprecated the project that would’ve used it, and Travis support was removed from it long ago.

**Comment by null-dev** [comment] 2018-06-30 16:21
By the way, I am still encountering this issue, if you need any information on the project to help reproduce this I would be happy to help

**Comment by cruzj6** [comment] 2018-07-02 02:38
I am also encountering this issue on Debian. I am able to build fine on Ubuntu.

**Comment by albertotorresfoltyn** [comment] 2018-07-12 15:16
Same thing here...
running as cli version 20.20.4 under centos 7

**Comment by albertotorresfoltyn** [comment] 2018-07-13 13:19
I have this error in debian and in centos 7

**Comment by junebug12851** [comment] 2018-08-30 15:10
This is the 2nd impossible error I've come across in Travis, I've been working at this non-stop for 24 hours now, literally, so I just don't recall all the different stuff Ive tried but it's been one brick wall after another. I've tried everything I can think of.

Really at this point I'm going to chalk it up to electron-builder not being at all compatible with Travis in nay way and just build locally manually on my end. 

If I'm wrong anywhere correct me, I've just literally been at this for a solid 24 hours with no breaks at all therefore I'll be more than happy to be corrected as it'd be nice surprise. Anyways I have to draw the line somewhere so until I hear anything further I'm calling it quits on Travis. At least it builds correctly on my local dev machine.

**Comment by deepakpreman** [comment] 2019-02-13 09:41
does any one have answer for this.

**Comment by nukeop** [comment] 2019-07-01 21:34
Travis now offers Windows machines so maybe this will be obsolete.

**Comment by probonopd** [comment] 2019-09-04 17:21
Not doing anything is never a good reason to close tickets in my humble opinion. So I don't know what good this bot is supposed to be doing.

**Comment by probonopd** [comment] 2019-11-03 20:04
Not doing anything is never a good reason to close tickets in my humble opinion. So I don't know what good this bot is supposed to be doing.

**Comment by nukeop** [comment] 2019-11-03 22:14
Closed for the third time for inactivity...

For what it's worth, electron-builder works fine in Github Actions when building on Windows machines.

**Comment by probonopd** [comment] 2019-11-03 22:19
> For what it's worth, electron-builder works fine in Github Actions when building on Windows machines.

Cool. Do you have an example we could have a look at? Thanks.

**Comment by nukeop** [comment] 2019-11-03 22:24
Yes.

Example recent run: https://github.com/nukeop/nuclear/runs/282512732
And the simple action that launched it: https://github.com/nukeop/nuclear/blob/master/.github/workflows/build.yml

I've also been experimenting with automated deployment on a separate branch, which mostly works, I just don't know how to upload several artifacts to a single release yet.
https://github.com/nukeop/nuclear/blob/feature/actions-deployment/.github/workflows/build.yml

**Comment by ishansharma2912** [comment] 2019-11-05 12:48
@globaltommy @albertotorresfoltyn I am also getting the same error on Centos 7 and on Ubuntu it's working fine. If you have applied any solution to it, Can you help me in that?

**Comment by moriczgergo** [comment] 2020-01-07 17:50
A shitton of people are having this problem. Stop making them stale,

**Comment by nukeop** [comment] 2020-03-07 18:47
this is just comedic now

**Comment by moriczgergo** [comment] 2020-05-09 15:02
ugh

**Comment by moriczgergo** [comment] 2020-05-09 15:03
Actually. This issue is not relevant for me now. Is it work as expected now?

**Comment by moriczgergo** [comment] 2020-05-09 15:03
Because if so I can close the issue

**Closed** 2021-06-16 22:50 UTC
Labels: backlog, reply-needed

**Comment by probonopd** [comment] 2021-06-18 05:48
Yes this is still relevant @stale

**Comment by albertotorresfoltyn** [comment] 2021-06-23 02:28
the issue is not relevant for me, I'm not using it

**Comment by Fireant456** [comment] 2021-07-08 18:31
I have this issue on CentOS 7

**Comment by amofen** [comment] 2023-03-20 15:24
we were facing the same issue when using the builder image. 
Since we were behind proxy we were downloading the builder binaries and extracting them to .cache location. 
The extraction process was not done correctly,  which results in the nsis folder to have all files in one folder without subfolder . 

we fixed the extraction command , and now we are able to build windows exe on linux container ( gitlab runner on kubernetes )
