### ISSUE TITLE
Failed to codesigh on electron 9.0.0-beta.24 MacOs Mojave 10.14.6

### ISSUE THREAD

**Issue by Sergey-Churilin** [electron-userland/electron-builder#4969] opened 2020-05-14 09:50 UTC
* **Version**: 22.6.0

* **Electron Version**: 9.0.0-beta.24

* **Electron Type (current, beta, nightly)**: beta

* **Target**: mac

* **Operating System:** macOS Mojave 10.14.6
  
* **Last Known Working Electron version:** 7.1.11, 9.0.0-beta.22
  
* **Expected Behavior**
Application builds without issues

* **Actual Behavior**
Errors in console and build fails

### Additional Information

Console build error:
 signing         file=dist/mac/App.app identityName=Apple Development: user@gmail.com (111111) identityHash=222222 provisioningProfile=none
  Command failed: codesign --sign 22222222 --force --timestamp --options runtime --entitlements /Users/user/<pathToEntitlements>/entitlements.mac.inherit.plist /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
stackTrace=                                                                                                                                                                                       Error: Command failed: codesign --sign 2222222 --force --timestamp --options runtime --entitlements /Users/user/<pathToEntitlements>/entitlements.mac.inherit.plist /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
/Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: /Users/user/<path>/mac/App.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
 at ChildProcess.exithandler (child_process.js:289:12)
at ChildProcess.emit (events.js:182:13)
at maybeClose (internal/child_process.js:961:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:250:5)
From previous event:
at runCallback (timers.js:693:18)
at tryOnImmediate (timers.js:664:5)
at processImmediate (timers.js:646:5)
From previous event:
at MacPackager.signApp (/Users/user/<path>/node_modules/app-builder-lib/src/macPackager.ts:329:27)
at MacPackager.doPack (/Users/user/<path>/node_modules/app-builder-lib/src/platformPackager.ts:244:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by mikkame** [comment] 2020-05-15 06:47
I had same error

**Comment by nali** [comment] 2020-05-15 09:53
Experiencing this as well when trying to codesign a macOS app: in this erroring case, it looks like the tree traversal in the forked version of electron-osx-sign that electron-builder uses isn't signing the deepest nodes first, resulting in the issue of `codesign` complaining about unsigned inner contents. 

With debug output enabled:
```
electron-osx-sign Walking... dist/mac/MYAPP.app/Contents +2ms
  electron-osx-sign Signing... dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +13ms
  electron-osx-sign Executing... codesign --sign A57A723015018A8BC34920145AC4BAE194E023B9 --force --timestamp --options runtime --entitlements build/entitlements.mac.plist dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework +1ms
  electron-osx-sign Error executing file:
 > Stdout:
 > Stderr: dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework: code object is not signed at all
In subcomponent: dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Helpers/chrome_crashpad_handler
 +178ms
```

Using the current version of [electron-osx-sign](https://github.com/electron/electron-osx-sign) on the same macOS app works fine though: the innermost contents are signed first:
```
electron-osx-sign Walking... dist/mac/MYAPP.app/Contents +2ms
  electron-osx-sign Signing... dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/am.lproj/locale.pak +25ms
  electron-osx-sign Executing... codesign --sign A57A723015018A8BC34920145AC4BAE194E023B9 --force --timestamp dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/am.lproj/locale.pak +0ms
  electron-osx-sign Signing... dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/ar.lproj/locale.pak +411ms
  electron-osx-sign Executing... codesign --sign A57A723015018A8BC34920145AC4BAE194E023B9 --force --timestamp dist/mac/MYAPP.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/ar.lproj/locale.pak +0ms
...
```

**Comment by x4080** [comment] 2020-05-22 23:57
Hi @nali, how do you fix it in the project that uses electron builder ? I tried to just install electron-osx-sign and it still shows error code sign (electron 9.1)

Thanks

**Comment by lutzroeder** [comment] 2020-05-23 02:26
Duplicate of #4969

**Comment by alchaplinsky** [comment] 2020-05-23 10:03
Same issue here

**Comment by dariocravero** [comment] 2020-05-25 16:51
until https://github.com/electron-userland/electron-builder/pull/4993 or a similar solution gets merged, monkey patching `node_modules/app-builder-lib/electron-osx-sign/sign.js` with the code on that PR works

**Comment by x4080** [comment] 2020-05-25 23:58
cool, wait for things to get merged

**Closed** 2020-05-27 09:35 UTC

**Comment by mitjans** [comment] 2020-11-02 11:54
Hi! Any update on this?
Monkey patching the file at node_modules works, but shouldn't it be merged into master by now?
Thank you

**Comment by mitjans** [comment] 2020-11-02 12:17
Any update on this?
Monkey patching the file `sign.js` at `node_modules` works, but shouldn't this be merged into master by now?
Thanks!
