### ISSUE TITLE
Auto-Update quitAndInstall Not Working On Mac

### ISSUE THREAD

**Issue by daveywc** [electron-userland/electron-builder#1604] opened 2017-05-31 22:41 UTC
"electron-builder": "^18.2.1"
"electron-updater": "^1.16.0"
Target: Mac

My auto-update on Windows is working fine.  However I still have two issues on the Mac.  

On the Mac it recognises that there is an update then asks the user if they want to download and install.  If the user responds 'Yes' then the update is downloaded and the user is advised that the new version is downloaded and will be installed when they click OK.  However the quitAndInstall never seems to get called.  If I close the app and re-open it again it just goes through the same process.  Also on Mac my progress is not logged to my log file, nor is the status bar working.  Both of these things work correctly on Windows.  See code  and log file below.

[log.txt](https://github.com/electron-userland/electron-builder/files/1043106/log.txt)

`autoUpdater.on('download-progress', (progressObj) => {
        let log_message = "Download speed: " + progressObj.bytesPerSecond;
        log_message = log_message + ' - Downloaded ' + progressObj.percent + '%';
        log_message = log_message + ' (' + progressObj.transferred + "/" + progressObj.total + ')';
        log.log('info', log_message);
        mainWindow.setProgressBar((progressObj && progressObj.percent) ? progressObj.percent / 100 : -1)
    });

    autoUpdater.on('update-downloaded', (versionInfo) => {
        var dialogOptions = {
            type: 'question',
            defaultId: 0,
            message: `The update is ready to install, Version ${versionInfo.version} has been downloaded and will be automatically installed when you click OK`
        };
        dialog.showMessageBox(mainWindow, dialogOptions, function() {
            if (!isDev) {
                autoUpdater.quitAndInstall();
            }
        });
    });`

**Comment by daveywc** [comment] 2017-06-07 02:39
I've made another donation.  Any chance of getting some help with this issue?

**Comment by develar** [comment] 2017-06-07 06:42
> Also on Mac my progress is not logged to my log file

Fixed in the electron-updater 2.0.0

**Comment by develar** [comment] 2017-06-07 07:21
It is not electron-updater issue. Please see https://github.com/electron/electron/issues/3583

As you have made a donation, issue was investigated by me for you. 

You need to modify your code:

```js
setImmediate(() => {
          app.removeAllListeners("window-all-closed")
          if (focusedWindow != null) {
            focusedWindow.close()
          }
          autoUpdater.quitAndInstall(false)
        })
```

1. In the your dialog handler, you must call `quitAndInstall` or other actions only in the `setImmediate`. To ensure that all dialog/sheet windows were released.
2. To ensure that your `window-all-closed` handler (if it is added, e.g. https://github.com/develar/onshape-desktop-shell/blob/master/src/WindowManager.ts#L16) doesn't prevent quit, remove all such listeners `app.removeAllListeners("window-all-closed")`.
3. Explicitly close window. `mainWindow.close()` If you have more than one windows, close all (`BrowserWindow.getAllWindows()` to get all windows).

If still no luck — try `mainWindow.destroy()`.

**Closed by develar** 2017-06-07 07:21 UTC

**Comment by daveywc** [comment] 2017-06-07 22:36
Thanks @develar.  Both issues are now resolved.  Mac auto-updates are working nicely.  Appreciate your help.

**Comment by Kunze** [comment] 2017-08-02 20:41
Did not work for windows.
The app does not start after closing.

**Comment by sweetevil** [comment] 2017-10-24 15:15
@develar I am having same issue `autoUpdater` is working fine on windows but having issues on mac. 

```
app.on('ready', () => {
    // handle app updates
    if (process.env.NODE_ENV !== 'development') {
      autoUpdater.setFeedURL(updateFeedUrl);
      autoUpdater.on('error', (err) => {
        console.log(err);
      });
      // wait for things to settle in
      setTimeout(() => {
        checkForUpdates();
      }, 30000);
    }
    ipcMain.on('application:quit-install', () => autoUpdater.quitAndInstall());
    autoUpdater.on('update-downloaded', () => {
      updateDownloaded = true;
      dialog.showMessageBox({
        title: 'New Version Downloaded',
        message: 'The update will be applied the next time you start the app. Close and restart now to run the latest version.',
        buttons: ['Restart', 'Later'],
        icon: dialogIcon
      }, (response) => {
        if (response === 0) {
          autoUpdater.quitAndInstall();
        }
      });
    });
    autoUpdater.on('update-available', () => { updateAvailable = true;
      console.log('update-av', updateAvailable);
    });

    let opts = {
      show: false,
      width: 1200,
      height: 720,
      minWidth: 1200,
      minHeight: 720,
      titleBarStyle: 'hiddenInset'
    };
    Object.assign(opts, config.getData().winBounds);
    delete opts.fullscreen; // prevent app from launching fullscreen
    mainWindow = new BrowserWindow(opts);

    mainWindow.loadURL(`file://${__dirname}/app/app.html`);

    template = getTemplate();
    menu = Menu.buildFromTemplate(template);
    Menu.setApplicationMenu(menu);
  });
```

**Comment by purplekrayons** [comment] 2017-11-22 16:14
@sweetevil unfortunately, @develar left out a critical piece of information from the documentation -- auto updating will not work unless your Mac application is signed.

I found this out by reading through the [electron docs for auto updating](https://github.com/electron/electron/blob/master/docs/api/auto-updater.md).

> Your application must be signed for automatic updates on macOS. This is a requirement of Squirrel.Mac

This may be the cause of your issue.

**Comment by sweetevil** [comment] 2017-11-24 13:47
@purplekrayons My issue was with me using dmg format but zip format was needed to make it work. I just changed the format and it worked for our customers fine 👍

**Comment by purplekrayons** [comment] 2017-11-24 15:16
@sweetevil Most interesting. Are you signing your Mac app? I wasn't able to get mine working -- to note I am using .zip -- this makes me think perhaps I have another thats causing my mac clients not to auto-update.

**Comment by onassar** [comment] 2018-03-11 05:59
I (quite naturally) had a `close` event on a BrowserWindow set up (for Macs) in order to capture the `Command+W` hotkey. Because of this, the `autoUpdater.quitAndInstall` method wasn't working. Here's my go at a helper-function to deal with cases of aggressive event listeners preventing the app from properly restarting:


    /**
     * ensureSafeQuitAndInstall
     * 
     * @access  public
     * @return  void
     */
    function ensureSafeQuitAndInstall() {
        const electron = require('electron');
        const app = electron.app;
        const BrowserWindow = electron.BrowserWindow;
        app.removeAllListeners('window-all-closed');
        var browserWindows = BrowserWindow.getAllWindows();
        browserWindows.forEach(function(browserWindow) {
            browserWindow.removeAllListeners('close');
        });
    }

Hope this is helpful to someone out there :)

**Comment by garshythoel** [comment] 2019-02-14 02:15
> I (quite naturally) had a `close` event on a BrowserWindow set up (for Macs) in order to capture the `Command+W` hotkey. Because of this, the `autoUpdater.quitAndInstall` method wasn't working. Here's my go at a helper-function to deal with cases of aggressive event listeners preventing the app from properly restarting:
> 
> ```js
> /**
>  * ensureSafeQuitAndInstall
>  * 
>  * @access  public
>  * @return  void
>  */
> function ensureSafeQuitAndInstall() {
>     const electron = require('electron');
>     const app = electron.app;
>     const BrowserWindow = electron.BrowserWindow;
>     app.removeAllListeners('window-all-closed');
>     var browserWindows = BrowserWindow.getAllWindows();
>     browserWindows.forEach(function(browserWindow) {
>         browserWindow.removeAllListeners('close');
>     });
> }
> ```
> 
> Hope this is helpful to someone out there :)

This (we think) just solved a massive issue with our app's upgrade flow. Thanks!

**Comment by onassar** [comment] 2019-02-14 11:50
ps. my loom hasn't worked for ages ;)

**Comment by Kirezi** [comment] 2021-06-01 18:53
@onassar where did you use that helper function, I run into similar issue but I can't fix the issue

**Comment by onassar** [comment] 2021-06-01 19:21
@Kirezi 

Sadly, it's been years, and I ended up abandoning our attempt at a native (Electron wrapped) app. At the time, Electron required way (way way) too much low-level logic to work reliably. It's been years, so my guess is it's not as bad anymore. But I'm not sure where exactly I put that. Likely in the boot script (or whatever the language equivalent of that is these days).

**Comment by effectivecui** [comment] 2021-11-10 06:28
> * To ensure that your `window-all-closed` handler (if it is added, e.g. https://github.com/develar/onshape-desktop-shell/blob/master/src/WindowManager.ts#L16) doesn't prevent quit, remove all such listeners `app.removeAllListeners("window-all-closed")`.

thanks.

**Comment by effectivecui** [comment] 2021-11-10 06:29
> It is not electron-updater issue. Please see [electron/electron#3583](https://github.com/electron/electron/issues/3583)
> 
> As you have made a donation, issue was investigated by me for you.
> 
> You need to modify your code:
> 
> ```js
> setImmediate(() => {
>   app.removeAllListeners("window-all-closed")
>   if (focusedWindow != null) {
>     focusedWindow.close()
>   }
>   autoUpdater.quitAndInstall(false)
> })
> ```
> 
> 1. In the your dialog handler, you must call `quitAndInstall` or other actions only in the `setImmediate`. To ensure that all dialog/sheet windows were released.
> 2. To ensure that your `window-all-closed` handler (if it is added, e.g. https://github.com/develar/onshape-desktop-shell/blob/master/src/WindowManager.ts#L16) doesn't prevent quit, remove all such listeners `app.removeAllListeners("window-all-closed")`.
> 3. Explicitly close window. `mainWindow.close()` If you have more than one windows, close all (`BrowserWindow.getAllWindows()` to get all windows).
> 
> If still no luck — try `mainWindow.destroy()`.
> 
> Don't forget to update to electron-updater 2.1.1

thanks. @develar
