### ISSUE TITLE
wrong executable in .desktop

### ISSUE THREAD

**Issue by dperetti** [electron-userland/electron-builder#1291] opened 2017-02-22 11:53 UTC
13.11.1

Linux deb

If find this : 
    Exec="/opt/CodeStory/codestory"

But my executable is `CodeStory`.

I set this in my electron-builder.yml.

    executableName: 'CodeStory'

**Comment by develar** [comment] 2017-02-22 11:55
Is executable app file also named as `codestory`?

**Comment by dperetti** [comment] 2017-02-22 11:58
No, precisely it's `CodeStory` and the correct exec should be:

    Exec="/opt/CodeStory/CodeStory"

**Comment by develar** [comment] 2017-02-22 22:34
`executableName` always is lowercased. Do you want "DO NOT touch my option" and force it to be exactly as specified with uppercased chars?

**Comment by develar** [comment] 2017-02-23 07:27
I cannot reproduce — `codestory` is used in the deb. But you want `CodeStory`, right?

**Comment by dperetti** [comment] 2017-02-23 09:31
Actually I would even prefer "Code Story", which works on Windows. But I wanted to put another possible issue aside 
I'm using a prebuilt app directory. Whatever the name of my electron app living inside, I should be able to specify it in the config and get it to work. Maybe I'm just confused with the documentation but I made multiple attempts with different combinations and something was always wrong in the end.
I'll try to narrow down the issue a bit further and I'll let you know.
Thanks !

**Comment by develar** [comment] 2017-02-23 09:37
`Code Story` contradicts to linux conventions

> I'm using a prebuilt app directory
> I should be able to specify it in the config and get it to work

Yes, in case of prebuilt app directory we must use `executableName` and convert it to correct value according to target (i.e. lowercase).

**Comment by dperetti** [comment] 2017-02-23 09:55
It's an app, not a unix command. In Ubuntu, apps are called "LibreOffice Writer", "LibreOffice Calc", etc.
Actually I have Code Story, but also other variants : Code Story DEMO, Code Story READER.
I should be able to use this on Linux ! 
I don't think we should need to use `executableName` if `productName` is correctly set.
This is probably related, but I just tried to build an AppImage with the productName set to "Code Story" (which is the exact name of my electron app in the pre-built folder).
The build is successful, but when I run it is says (sorry it's french!) :

`/tmp/.mount_Rzpxw0/AppRun: ligne 56: /tmp/.mount_Rzpxw0/usr/bin/codestory: Aucun fichier ou dossier de ce type
`

So apparently `Code Story` it was automatically converted to `codestory`. Why not, but then the executable should be renamed as well I guess.

**Comment by develar** [comment] 2017-02-23 10:03
Ok. So, you worry only about product name. Error is clear — you build app using electron-packager and your app name is `Code Story` But electron-builder expect it as codestory (as electron-builder packs and as it should be according to linux conventions). So, `executableName` must be taken in account for prepackaged app.

**Comment by dperetti** [comment] 2017-02-23 10:20
I'm fine with electron-builder renaming the executable internally as long as it does it in a way that doesn't brake anything :-)

**Comment by dperetti** [comment] 2017-02-23 10:36
BTW, if I set `executableName` to "codestory", it doesn't change anything and I get the exact same error.

**Comment by develar** [comment] 2017-02-23 10:38
Will be fixed in 2 days. As workaround, you can currently or use electron-builder to pack, or rename executable manually before build.

**Comment by dperetti** [comment] 2017-02-23 10:49
That's weird, even though I renamed my executable manually to `codestory`, I still get the same error.
How can I read the content of the AppImage to figure out ?
I tried this :

```
./appimagetool-x86_64.AppImage -l codestory-1.0.4-x86_64.AppImage 
This doesn't look like a squashfs image.
sqfs_open_image error
```

**Comment by develar** [comment] 2017-02-23 10:51
> How can I read the content of the AppImage to figure out ?

Using any "normal" unarchiver. e.g. http://www.iunarchive.com

**Comment by dperetti** [comment] 2017-02-23 11:02
well, just ark > 16.0.8 apparently https://github.com/probonopd/AppImageKit/issues/173

**Comment by dperetti** [comment] 2017-02-23 11:18
Isn't supposed the `--appimage-extract` option to extract the content of the AppImage ?
It works when I do : `appimagetool-x86_64.AppImage --appimage-extract`. I get a bunch of files in the console and  also a full squashfs-root folder.
But with my codestory Appimage, nothing, just this :
```
./codestory-1.0.4-x86_64.AppImage --appimage-extract
installed: X-AppImage-BuildId=617b5240-f9a9-11a6-32f4-0dfe4513412d image: X-AppImage-BuildId=617b5240-f9a9-11a6-32f4-0dfe4513412d
/tmp/.mount_QhIfHt/AppRun: ligne 58: /tmp/.mount_QhIfHt/usr/bin/codestory: Aucun fichier ou dossier de ce type

```

**Comment by develar** [comment] 2017-02-23 11:40
`sudo mount file.AppImage  /mnt`?

**Comment by dperetti** [comment] 2017-02-23 11:50
thanks ! I could figure out that I probably did a mistake somewhere. Using "codestory" everywhere definitely  works.

**Comment by dperetti** [comment] 2017-02-23 13:39
Of course, you'll just need to make sure the full real name (with spaces if any) is set in the .desktop file.

**Comment by dperetti** [comment] 2017-02-24 11:36
Another way to this : when using a prebuilt app, any key from `package.json` should be overridable.
In my case, what really blocks me is the fact that the `name` is taken from `package.json` and cannot be overridden in the builder config.

**Comment by develar** [comment] 2017-02-24 11:38
It cannot be overridden because in this case we must modify packed package.json — but as you don't use electron-builder to pack, it is not possible.

**Comment by dperetti** [comment] 2017-02-24 11:42
I don't get it. I think it should be the exact opposite : since I'm using a prebuilt app, I should be able package it without relying on package.json, just using the config. This step should even be electron-agnostic.

**Comment by develar** [comment] 2017-02-24 11:44
To set application name, you can use `productName` in the config.

**Closed** 2017-02-24 12:14 UTC
Labels: feature, linux

**Comment by develar** [comment] 2017-02-24 12:20
14.2.0 — `executableName` is used as is. Not lowercased.
