### ISSUE TITLE
Close running processes on silent uninstall

### ISSUE THREAD

**Issue by Kiyozz** [electron-userland/electron-builder#2642] opened 2018-02-26 13:59 UTC
* **Version**:  19.56.0

* **Target**: nsis

Hi,

My customer wants the installer/uninstaller to be fully silent for install on multiple computers.

When non-silent uninstall, the message box ask to close the process before uninstall.
When silent uninstall, the question of message box is ignored (of course, silent) but default answer seems to be "no".
How can we close running processes when silent uninstall (and child processes) ?

Thanks.

**Comment by hallss93** [comment] 2018-02-26 18:25
I have a similar problem. I have already reported it #2612 but so far nothing!

**Comment by develar-vacation** [comment] 2018-02-26 18:26
Silent uninstall must close app, so, looks like a bug. I am on vacation, will check one week later. Please ping to be notify one week later :)

**Comment by alexgreenough** [comment] 2018-07-27 14:20
is there any update on this issue?

**Comment by elvisvoer** [comment] 2019-06-27 14:20
@develar I am also having issues with the silent uninstaller closing the running application and I could see that the issue is here: https://github.com/electron-userland/electron-builder/blob/a23e68066b3912110024d219507f5691fd14e450/packages/app-builder-lib/templates/nsis/uninstaller.nsh#L4

Basically the check is only if the uninstall is not in silent mode. There is another check down in line 25 but that is only if the uninstaller is assisted. There is no check if the installer is one-click and silent

**Comment by Kiyozz** [comment] 2019-06-27 22:22
Wow, it’s been a year! How does this progress?

**Comment by Kiyozz** [comment] 2019-08-26 23:02
I think this issue still happens

**Comment by Kiyozz** [comment] 2019-10-26 06:36
Any news ?

**Closed** 2020-01-01 09:21 UTC
Labels: backlog

**Comment by lister169126** [comment] 2021-04-22 00:47
Still not fixed

**Comment by sabyasachibal** [comment] 2021-07-15 12:49
I am facing the same issue.
