### ISSUE TITLE
DMG icon is not set, shows default dmg icon

### ISSUE THREAD

**Issue by Ralph-Juke** [electron-userland/electron-builder#5611] opened 2021-02-04 08:16 UTC
* **Version**: 22.9.1
* **Electron Version**: 11.2.1
* **Electron Type (current, beta, nightly)**: current
* **Target**: Mac + DMG

OS: Mac OS Big Sur

Building / Notarising works fine, only issue is that the icon of the DMG stays the default icon.

DMG json part:
    "dmg": {
      "background": "img/dmg_background.png",
      "icon": "img/dmg_icon.icns",
      "title": "My App Installer",
      "window": {
        "width": "540",
        "height": "380"
      }
    }

Below you can see the green/yellow crown in the top bar. this is the actual dmg_icon:
![icon is used in top bar](https://user-images.githubusercontent.com/74725329/106863592-0697bf80-66c9-11eb-9496-ce39d1bc39b9.png)

The icon of the DMG it self stays the default Mac icon for the DMG
![dmg icon](https://user-images.githubusercontent.com/74725329/106863594-07c8ec80-66c9-11eb-9dbf-57832d6598bb.png)

My question, is this the the intended behaviour? or should the icon change and this is an actual bug?

On Big Sur you can change the icon in a very inconvenient mode only by rebooting in recovery mode. Both terminal and using the info window of a file won't let you change the icon as it did on older versions of Mac OS.

My suggestion is to have or update the DMG icon with the "icon" icon, or have a additional key for the DMG icon itself

**Comment by mmaietta** [comment] 2021-03-05 22:55
Hmmm, I'm unable to reproduce this MacOS Catalina, so this may be a new bug. 

My company blocks updating to Big Sur 😭...so I'll need to figure out another way about this. PR is welcome if you're willing to explore the code
Here's how [To setup a local dev environment](https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment)

**Comment by sangeeth96** [comment] 2021-03-10 06:45
@Ralph-Juke AFAIK, the `.dmg` file's icon is set by macOS itself. I've never noticed it being different for any app I've downloaded so far. You may close this issue if it's only related to the icon of the `.dmg` file.

**Closed** 2021-07-29 21:32 UTC
Labels: bug, mac
