### ISSUE TITLE
The command is disabled and cannot be executed at MacUpdater.quitAndInstall

### ISSUE THREAD

**Issue by Kirezi** [electron-userland/electron-builder#5935] opened 2021-05-31 15:15 UTC
* **Electron Version**:^12.0.2
* **Electron-builder**:^22.10.5

* **Electron-updater**:^4.3.8

* **Target**: Mac

* **NPM Version**: 6.14.11
* **Node Version**: v14.16.0

windows auto update work perfectly, but on Mac, when the application has finished updating, this error appears twice
![beaf8381-4a90-4d37-99d7-880b917aa21f](https://user-images.githubusercontent.com/17754183/120210389-b86d7580-c1fd-11eb-90af-bab2532907b3.png)

and once I hit ok, the app reopen itself and complete the update. How can I get rid of this macUpdater issue?
I am new to electron and any help would be appreciated, Thanks.

code:
```
autoUpdater.on('update-downloaded', () => {
  const options = {
    buttons: [],
    title: i18n.translate('updateRelaunchRequired'),
    message: i18n.translate('updateWillRestart'),
  };

  dialog.showMessageBox(options).then(
    (result) => {
      setImmediate(() => autoUpdater.quitAndInstall(false, true));
    },
    (error) => {
      main.log(`autoUpdater.on  showMessageBox error`, error);
    }
  );
});
```

**Comment by mmaietta** [comment] 2021-05-31 15:37
Two quick notes, can you try not using `setImmediate()`, just use `autoUpdater.quitAndInstall(false, true)`?
Curious if it's colliding here:
https://github.com/electron-userland/electron-builder/blob/ef704a11e57666c723b6a5535c66b5a5cb697255/packages/electron-updater/src/BaseUpdater.ts#L15-L19

**Comment by Kirezi** [comment] 2021-05-31 16:20
@mmaietta  I tried removing setImmediate(). here is the below code and still getting the same error
```
autoUpdater.on('update-downloaded', () => {
  const options = {
    buttons: [],
    title: i18n.translate('updateRelaunchRequired'),
    message: i18n.translate('updateWillRestart'),
  };

  dialog.showMessageBox(options).then(
    (result) => {
  autoUpdater.quitAndInstall(false, true));
    },
    (error) => {
      main.log(`autoUpdater.on  showMessageBox error`, error);
    }
  );
});
```

**Comment by Kirezi** [comment] 2021-06-01 15:16
@develar any chance of getting help on this?

**Comment by kalryoma** [comment] 2021-06-02 09:51
> @mmaietta I tried removing setImmediate(). autoUpdater.quitAndInstall is never called
> 
> ```
> autoUpdater.on('update-downloaded', () => {
>   const options = {
>     buttons: [],
>     title: i18n.translate('updateRelaunchRequired'),
>     message: i18n.translate('updateWillRestart'),
>   };
> 
>   dialog.showMessageBox(options).then(
>     (result) => {
>   autoUpdater.quitAndInstall(false, true));
>     },
>     (error) => {
>       main.log(`autoUpdater.on  showMessageBox error`, error);
>     }
>   );
> });
> ```

same issue here! call ```autoUpdater.quitAndInstall()``` inside 'update-downloaded' trigger this bug immediately

**Comment by Kirezi** [comment] 2021-06-02 14:11
@develar I have made a donation, can someone help here

**Comment by mmaietta** [comment] 2021-06-02 14:29
@kalryoma @Kirezi quick Q, did this start as a regression after updating electron-builder by chance?
Would you be willing to try ^22.11.5? I'm trying to triage the issue but I also don't have a way to test this.

**Comment by Kirezi** [comment] 2021-06-02 15:33
@mmaietta I just tried 22.11.5 and still getting the error

**Comment by mmaietta** [comment] 2021-06-03 00:57
@Kirezi I did a quick search and found these resources as the error being thrown is part of electron core.
https://github.com/electron/electron/issues/7792#issuecomment-828354361

Can you try either of these two approaches?
```
const autoUpdater = require('electron-updater')
autoUpdater.nativeUpdater.quitAndInstall()
```
or use electron core which is what the `nativeUpdater` is proxying.
```
import { autoUpdater } from 'electron';
autoUpdater.quitAndInstall();
```

**Comment by Kirezi** [comment] 2021-06-03 16:41
@mmaietta tried both approach and looks like they break the updater. I don't think nativeUpdater is supported in electron

**Comment by mmaietta** [comment] 2021-06-03 20:32
Sorry, what's the error? If it's a typing issue, then perhaps can cast as `any` first?

`nativeUpdater` is a proxy
https://github.com/electron-userland/electron-builder/blob/dc359de5019807a014c62468385dfb14bbb5bd83/packages/electron-updater/src/MacUpdater.ts#L13-L14

**Comment by Kirezi** [comment] 2021-06-03 21:06
yep it was complaining on the nativeUpdater as a type issue.  I am using js not sure if I can cast variable. can you give me an example

**Comment by mmaietta** [comment] 2021-06-04 01:15
Can you please post the full error here?

**Comment by Kirezi** [comment] 2021-06-04 14:21
That's the error I am getting
![image](https://user-images.githubusercontent.com/17754183/120816237-91c17e80-c51e-11eb-919b-54b90c43798b.png)

**Comment by Kirezi** [comment] 2021-06-04 14:21
followed by this one too 
![image](https://user-images.githubusercontent.com/17754183/120816383-aaca2f80-c51e-11eb-90a1-f07e9a50408b.png)

**Comment by Kirezi** [comment] 2021-06-04 16:18
@mmaietta the macUpdater is being caught in the error event as follow
`autoUpdater.on('error', (error) => {
  dialog.showErrorBox('Error: ', error == null ? 'unknown' : (error.stack || error).toString());
});`

and doing this to update my application 
`autoUpdater.on('update-downloaded', () => {
const options = {
    buttons: [],
    title: i18n.translate('updateRelaunchRequired'),
    message: i18n.translate('updateWillRestart'),
  };

 
  dialog.showMessageBox(options).then(
    (result) => {
      if(result.response === 0) {
     setImmediate(() =>autoUpdater.quitAndInstall(false, true) ) 
    }  
    },
    (error) => {
      main.log(`autoUpdater.on  showMessageBox error`, error);
    }
  );
}`

although the application update successfully on mac, the showErrorBox still appears with the error message. either this error is not something to worry about or should be fixed on the electron-updater package

**Comment by mmaietta** [comment] 2021-06-04 19:20
Definitely should be fixed in electron-updater, it sounds like some event listener or process is being killed when you run `quitAndInstall` (such as another `checkForUpdates` loop maybe?)

Did this issue recently start for you?  These are the most changes that were introduced that I think could be related if so.
https://github.com/electron-userland/electron-builder/blob/dc359de5019807a014c62468385dfb14bbb5bd83/packages/electron-updater/src/MacUpdater.ts#L152-L165
https://github.com/electron-userland/electron-builder/blob/dc359de5019807a014c62468385dfb14bbb5bd83/packages/electron-updater/src/MacUpdater.ts#L139-L145

Side question: Do you happen to have `autoInstallOnAppQuit` set?
I'm trying to discern where the error is being thrown, particularly since you're saying that the update does complete successfully, but an error is still thrown.

I don't have an effective manner of testing this (or just don't know how to yet), would you mind if I generated some `.patch` file(s) to test out different fixes or just to add more logging to help debug this further? Trying to get to the bottom of this as fast as possible for you 🙂

**Comment by purocean** [comment] 2021-06-07 10:27
I use `setTimeout` instead of `setImmediate`, resolved this problem.

```
if (result.response === 0) {
    setTimeout(() => {
      autoUpdater.quitAndInstall()
    }, 500);
  }
```

Attention: DO NOT use `setTimeout(..., 0)`, I don't know why, but the value `500` works for me. `zero` not work.

**Comment by Kirezi** [comment] 2021-06-07 17:28
@mmaietta I am not using the autoInstallonAppQuit flag. sure, let me know anything you need from me, I can share my update file if that will help

**Comment by Kirezi** [comment] 2021-06-07 17:41
> I use `setTimeout` instead of `setImmediate`, resolved this problem.
> 
> ```
> if (result.response === 0) {
>     setTimeout(() => {
>       autoUpdater.quitAndInstall()
>     }, 500);
>   }
> ```
> 
> Attention: DO NOT use `setTimeout(..., 0)`, I don't know why, but the value `500` works for me. `zero` not work.

Unfortunately that didn't work for me,  the only thing that's preventing this error @mmaietta @purocean is ignoring this error as such 
```
autoUpdater.on('error', (error) => {
  if(process.platform !=='darwin' && (error.stack || error).toString().includes('The Command is disabled and cannot be executed')){
      dialog.showErrorBox('Error: ', error == null ? 'unknown' : (error.stack || error).toString());
  }

});


```

**Comment by mmaietta** [comment] 2021-06-09 20:19
Oomph, I think the update-downloaded event is being fired twice, which would call the quitAndInstall twice then.
https://github.com/electron-userland/electron-builder/blob/v22.11.5/packages/electron-updater/src/BaseUpdater.ts#L29
https://github.com/electron-userland/electron-builder/blob/v22.11.5/packages/electron-updater/src/MacUpdater.ts#L126

Can you please try this patch?
`electron-updater+4.3.9.patch`
```
diff --git a/node_modules/electron-updater/out/MacUpdater.js b/node_modules/electron-updater/out/MacUpdater.js
index c0b2c4e..97b856c 100644
--- a/node_modules/electron-updater/out/MacUpdater.js
+++ b/node_modules/electron-updater/out/MacUpdater.js
@@ -107,7 +107,7 @@ class MacUpdater extends AppUpdater_1.AppUpdater {
                             headers: { "Cache-Control": "no-cache" },
                         });
                         // The update has been downloaded and is ready to be served to Squirrel
-                        this.dispatchUpdateDownloaded(event);
+                        // this.dispatchUpdateDownloaded(event);
                         if (this.autoInstallOnAppQuit) {
                             this.nativeUpdater.once("error", reject);
                             // This will trigger fetching and installing the file on Squirrel side

```

**Comment by Kirezi** [comment] 2021-06-11 14:42
@mmaietta I am currently using 4.3.9 and keep seeing the error

**Comment by mmaietta** [comment] 2021-06-12 20:07
Just to confirm, did you apply my patch?

**Comment by Kirezi** [comment] 2021-06-14 14:17
@mmaietta how can I apply that patch(specific instruction) ?

**Comment by varunsrin** [comment] 2021-06-16 17:12
@mmaietta I've started seeing this issue recently, and it's sporadic. Some more details in case it helps debug: 

Versions of packages: 

```
electron 12.0.2
electron-builder 22.10.5
```

The code that triggers the auto-update quit and install: 
```ts
import { autoUpdater } from 'electron-updater';

autoUpdater.on('update-downloaded', () => {
  dialog
    .showMessageBox(mainWindow, {
      title: 'Update',
      message: 'A new version is available.',
      defaultId: 0,
      cancelId: 1,
      buttons: ['Install and restart', 'Install on next open'],
    })
    .then((result) => {
      if (result.response === 0) {
        setImmediate(() => autoUpdater.quitAndInstall());
      }
      return result.response;
    })
    .catch((err) => {
      console.log(err);
    });
});
```

The observed error from user perspective is that the "Update: A new version is available" dialog appears multiple times and clicking on it more than once causes the application to crash. The update ends up being installed successfully, but it's not a great user experience. The error is also not consistent - only some users have reported this, though the frequency went up recently 



The observed error from stack trace: 

```
The command is disabled and cannot be executed
```

**Comment by varunsrin** [comment] 2021-06-16 17:12
@Kirezi you can use `yarn patch-package` to try out @mmaietta's patch suggestion: https://www.npmjs.com/package/patch-package

**Comment by mmaietta** [comment] 2021-06-21 03:29
Woah, sorry for the delay here. The bot notifications overwhelm my inbox and I have no idea how to track previous conversations. (Any tips/tricks/suggestions welcome)

@varunsrin, how many times is that `update-downloaded` event triggering for you exactly?
Did my patch work correctly for you by chance?

**Comment by mingy98** [comment] 2021-06-22 13:27
`update-downloaded` is only triggered once for me, and I make sure to only call `quitAndInstall` a single time, but this bug is still showing up

**Comment by mmaietta** [comment] 2021-06-22 18:49
Would someone be willing to try the latest electron-builder for this issue @ ^22.11.7 and confirm they're on the latest electron-updater @ 4.3.9?
There weren't many mac changes, but the entire compiler, publishing, and formatting changed so it's making it really difficult to triage.

**Comment by lauer** [comment] 2021-06-24 09:07
I get the same error

* `electron-builder: 22.11.7`
* `electron-updater: 4.3.9`

```
[2021-06-24 11:05:50.258] [error] Error: Error: The command is disabled and cannot be executed
    at MacUpdater.quitAndInstall (/Applications/APP.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:135:32)
    at Immediate._onImmediate (/Applications/APP.app/Contents/Resources/app.asar/app/updater.js:22:36)
    at processImmediate (internal/timers.js:456:21)


```

**Comment by Kirezi** [comment] 2021-06-24 13:26
> I get the same error
> 
> * `electron-builder: 22.11.7`
> * `electron-updater: 4.3.9`
> 
> ```
> [2021-06-24 11:05:50.258] [error] Error: Error: The command is disabled and cannot be executed
>     at MacUpdater.quitAndInstall (/Applications/APP.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:135:32)
>     at Immediate._onImmediate (/Applications/APP.app/Contents/Resources/app.asar/app/updater.js:22:36)
>     at processImmediate (internal/timers.js:456:21)
> ```
> 
> This error occur 2 times.
> 
> UPDATE:
> 
> Okay, so the problem is actually in the quitAndInstall() method.
> 
> If I update the. `node_modules/electron-updater/out/MacUpdater.js:135` to not include the extra check. The updater install the updates and restart the app with the new version.
> 
> ```
>             // And trigger the update
>             //this.nativeUpdater.checkForUpdates();
> ```

@lauer did it fix the issue after you commented out the extra check?

**Comment by lauer** [comment] 2021-06-24 14:23
> @lauer did it fix the issue after you commented out the extra check?

Yes, it dit.

**Comment by Kirezi** [comment] 2021-06-24 17:09
> I get the same error
> 
> * `electron-builder: 22.11.7`
> * `electron-updater: 4.3.9`
> 
> ```
> [2021-06-24 11:05:50.258] [error] Error: Error: The command is disabled and cannot be executed
>     at MacUpdater.quitAndInstall (/Applications/APP.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:135:32)
>     at Immediate._onImmediate (/Applications/APP.app/Contents/Resources/app.asar/app/updater.js:22:36)
>     at processImmediate (internal/timers.js:456:21)
> ```
> 
> This error occur 2 times.
> 
> UPDATE:
> 
> Okay, so the problem is actually in the quitAndInstall() method.
> 
> If I update the. `node_modules/electron-updater/out/MacUpdater.js:135` to not include the extra check. The updater install the updates and restart the app with the new version.
> 
> ```
>             // And trigger the update
>             //this.nativeUpdater.checkForUpdates();
> ```

@mmaietta is it possible to include this fix in the next version

**Comment by mmaietta** [comment] 2021-06-26 01:44
PRs are always welcome 🙂 
Setting up a dev environment is fairly simple too: https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

Opened PR https://github.com/electron-userland/electron-builder/pull/5989

**Closed** 2021-06-26 20:07 UTC
Labels: electron-updater, reply-needed

**Comment by mmaietta** [comment] 2021-06-26 20:09
@develar can you please perform a release? Need to deloy this critical electron-updater fix

**Comment by Kirezi** [comment] 2021-06-28 15:52
Thanks @mmaietta and everyone here for the help 😃

**Comment by vineet1984** [comment] 2023-04-23 11:26
@mmaietta @Kirezi Has this issue been resolved in core electron? I am still seeing this error on Mac with autoUpdater.checkForUpdates() in main.js. I tried commenting out the additional checkForUpdates line in MacUpdater.js as you suggested but it didn't work for me.

"electron": "^21.2.0"

```
const { app, BrowserWindow, ipcMain, dialog, screen, Tray ,session, autoUpdater } = require('electron')
const os = require('node:os');
const log = require('electron-log');

log.info('Log from the main process');

autoUpdater.logger = log
autoUpdater.logger.transports.file.level = 'debug'

if (require('electron-squirrel-startup')) app.quit()

const macUrl = `${server}/update/osx_${os.arch()}/${app.getVersion()}`

autoUpdater.setFeedURL({
  url: macUrl
});

autoUpdater.on('update-downloaded', (event, releaseNotes, releaseName) => {
  log.info('Update downloaded');
  const dialogOpts = {
    type: 'info',
    buttons: ['Restart', 'Later'],
    title: 'Application Update',
    detail:
      'A new version has been downloaded. Restart the application to apply the updates.',
  }

  dialog.showMessageBox(dialogOpts).then((returnValue) => {
    if (returnValue.response === 0) { 
        setTimeout(() => {
          autoUpdater.quitAndInstall();
        }, 500);
    }
  })
})
```

Any help would be appreciated.
