### ISSUE TITLE
electron-updater fails to fetch updates from GitHub

### ISSUE THREAD

**Issue by p2004a** [electron-userland/electron-builder#7398] opened 2023-01-27 23:57 UTC
* **Electron-Builder Version**: 23.6.0
* **Node Version**: 16
* **Electron Version**: 21.3.3
* **Electron Type (current, beta, nightly)**: current
* **Electron Updater version**: 5.2.1 (tested and 5.3.0 is also broken)
* **Target**: Linux+Windows

As of 2023-01-28 22:55 UTC, electron-updater stops being able to update application using GitHub.

My application: https://github.com/beyond-all-reason/BYAR-Chobby/releases/tag/v1.1861.0
Other test application using updater: https://github.com/iffy/electron-updater-example/releases/tag/v0.8.1

The issue seems to be that `https://github.com/beyond-all-reason/BYAR-Chobby/releases/latest` stopped returning JSON when called with `Accept: application/json` but always just returns HTML entirely breaking update.

**Comment by p2004a** [comment] 2023-01-28 00:03
Opened https://github.com/orgs/community/discussions/45590

**Comment by p2004a** [comment] 2023-01-28 00:08
Stacktrace of failure:

```
Error: Error: Cannot parse releases feed: Error: Unable to find latest version on GitHub (https://github.com/beyond-all-reason/BYAR-Chobby/releases/latest), please ensure a production release exists: SyntaxError: Unexpected token '<', "






<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at GitHubProvider.getLatestTagName (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:149:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GitHubProvider.getLatestVersion (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:80:23)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:305:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:24)
    at Object.newError (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/builder-util-runtime/out/index.js:47:19)
    at GitHubProvider.getLatestTagName (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:153:42)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async GitHubProvider.getLatestVersion (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/providers/GitHubProvider.js:80:23)
    at async AppImageUpdater.getUpdateInfoAndProvider (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:305:19)
    at async AppImageUpdater.doCheckForUpdates (/tmp/.mount_BeyondAgzbTH/resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:319:24),
```

**Comment by djdefi** [comment] 2023-01-28 05:50
Does the [GitHub repository releases API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release) provide the needed JSON information? Such as: `https://api.github.com/repos/[owner]/[repo]/releases/latest`

**Comment by lutzroeder** [comment] 2023-01-28 05:55
@djdefi this is an update scenario so the code probing this location is shipped in lots of apps already and can't be modified.

**Comment by Fuzzwah** [comment] 2023-01-28 07:40
GitHub Engineers have pushed a change that has reverted `releases/latest` so it's once again respecting the `Accept: application/json` option, and once again returns json.

**Comment by p2004a** [comment] 2023-01-28 11:01
Now, that it's resolved:
- is calling `https://github.com/{org}/{repo}/releases/latest` with `Accept: application/json` a documented and supported flow that is ok for electron-updater to use?
- or is it undocumented "accidentail" behavior that electron-updater depends on incorrectly?

**Comment by davicr** [comment] 2023-01-30 14:14
> GitHub Engineers have pushed a change that has reverted releases/latest so it's once again respecting the Accept: application/json option, and once again returns json.
> As @jdolitsky mentions, the longer term change should be for electron apps to use the Rest API.

**Comment by lutzroeder** [comment] 2023-01-30 17:32
@develar and @mmaietta are you aware of this issue?

@Fuzzwah @jdolitsky @djdefi since this is an auto update scenario this code shipped and is in lots of app bits on lots of users machines. Any changes to URLs would likely leave those users stranded on outdated bits potentially missing critical updates.  Such users might not be authenticated with GitHub or even have a GitHub account.

**Comment by iffy** [comment] 2023-01-30 20:45
@lutzroeder is correct. Most of my app's users do not have GitHub accounts. I may use this interruption as a nudge to move away from hosting releases on GitHub. But any change I make, or GitHub makes, or electron-updater makes needs to have a long, published deprecation window because of the possibility of stranding users of old versions.

**Comment by mmaietta** [comment] 2023-01-30 23:24
@lutzroeder no I wasn't aware there were changes in the GH "get latest release" functionality.
Apart from electron-builder, I don't use electron for anything anymore actually.

AFAICT, it seems like the best route is to use an API directly as we don't know how long GH plans to keep supporting the current method, considering they had to rollback to support the functionality.

That all being said, does Github have a non-auth API? A quick search didn't return anything for me and I don't see another way of electron-updater being able to support GH as a Release Provider if GH intends on shutting down the `Accept: application/json` functionality.
Is the best route to start adding "deprecation/warning" log messages to nudge developers to use a different Publisher?

**Comment by darthwillis** [comment] 2023-01-31 17:49
👋🏻 Hey folks! This outage was an unintended consequence of a bug fix around `/releases/` routing. We have no intentions of altering the current expected behavior of the releases endpoints, or REST APIs. We do not have plans to deprecate returning JSON from `https://github.com/{org}/{repo}/releases/latest` with `Accept: application/json`. We apologize for the outage and are taking steps to mitigate the possibility of this recurring in the future!

**Comment by mmaietta** [comment] 2023-01-31 19:18
That's awesome news. Many thanks for confirming @darthwillis ! 

I think it's safe to close this issue now

**Closed by mmaietta** 2023-01-31 19:18 UTC

**Comment by darthwillis** [comment] 2023-01-31 21:32
Hey @mmaietta, if you don't mind a quick follow up.

I have spent some time this afternoon looking at the `https://github.com/{org}/{repo}/releases/latest` with `Accept: application/json` headers API calling pattern. It is not currently in our docs, and I haven’t been able to find other examples of non-REST-api routes that support JSON responses.

Before I go farther, this does not mean we are going to change the route functionality, or deprecate it. And it doesn’t change our repair items from Friday’s outage. We certainly need to continue to support this calling pattern with the number of electron apps out there installed on user devices.

If I may ask though, is the only blocker for moving to the [documented REST API](https://docs.github.com/en/rest/releases/releases?apiVersion=2022-11-28#get-the-latest-release) of https://api.github.com/repos/OWNER/REPO/releases/latest that it requires using a GitHub auth token?

In my testing, I am able to hit the REST API unauthenticated with `curl -H "Accept: application/json" https://api.github.com/repos/nodejs/node/releases/latest`. Maybe I have missed something in my environment though.

Are there any other blockers for using REST? I am wondering if it is possible, and a good idea to move towards a documented endpoint.

**Comment by mmaietta** [comment] 2023-01-31 22:54
Ooooo, I agree that using REST is best here in addition to using something that is documented. I wasn't part of the maintainer crew when the GitHub integration was built out, so I'm not familiar with the design decisions made at the time.

I just tested locally as well with the `curl` you provided and it works just fine for me. 

These are the two files that are handling electron-updater's fetching from Github
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/providers/GitHubProvider.ts
https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/providers/PrivateGitHubProvider.ts

I see there's a documented [Get a Release Asset](https://docs.github.com/en/rest/releases/assets?apiVersion=2022-11-28#get-a-release-asset) API that says it requires an auth token, but it seems to work without one for my public electron-builder-test repo.
```
curl -H "Accept: application/vnd.github+json" https://api.github.com/repos/mmaietta/electron-builder-test/releases/assets/74830694
```
@darthwillis is this expected behavior? It seems expected for a private repo to require an auth token, but for public repos, can I rely on an auth token header **not being** necessary?

**Comment by iffy** [comment] 2023-02-01 16:38
> Are there any other blockers for using REST? I am wondering if it is possible, and a good idea to move towards a documented endpoint.

I think the main concern would be rate limiting for unauthenticated users as described [here](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-personal-accounts): 

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the person making requests.

That endpoint does indeed look like it's subject to the 60 requests per hour per IP limit:

```
curl -I https://api.github.com/repos/nodejs/node/releases/latest
HTTP/2 200 
...
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
x-ratelimit-reset: 1675272935
x-ratelimit-resource: core
x-ratelimit-used: 2
...
```

I could imagine a scenario where many users share an IP address (e.g. a university) and cause updates to fail for each other. If the rate limit for that endpoint were removed, I would see no problem eventually switching to it.
