### ISSUE TITLE
Custom Application Contents > `files` paths should have priority over the default ones

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [electron-userland/electron-builder#4545] opened 2019-12-18 22:43 UTC
* **Version**: 21.2.0

* **Targets _(not relevant)_**: A lot (Windows, Linux, Mac: zip, NSIS, win-portable, AppImage)

So, in the docs: https://www.electron.build/configuration/contents#files
We have a bunch of default paths, and they are always added, no matter what you write in your "files" section or do not write at all.

This is working as expected (from what I understand from the docs, "All default ignores are added in any case"), but the issue is that in my use case, I do need to bundle  two `.d.ts` files from `node_modules`. My first assumption was that the custom `files` parameter rewrites the whole array of globs; then, I tried leaving only those relevant to my apps. In any way, my rules to include these two `.d.ts` were ignored or actually overridden with the array of the default ones.

Paths that don't intersect with default ones do work, so it is not a problem with the configuration in `package.json`.

In my view, custom `files` paths should have priority over the default ones.

---

About my particular use case: in my game editor, I have a pixi.js graphics engine in its `node_modules`. The version of it in my `package.json` determines the version my users will have in their projects. As I need to load typedefs and minified versions of pixi.js, I would like to take them from one place, but `.d.ts` are not packed into `.asar` archive, forcing me to write extraneous tasks in pipelines and change my app's logic.

**Comment by CosmoMyzrailGorynych** [comment] 2020-02-17 00:15
Inactive issues are still issues.

**Comment by christianbundy** [comment] 2020-04-12 17:14
Is *this* why `fs.readFileSync(path.join(__dirname, "README.md"))` is failing in one of my dependencies? I've been explicitly adding the readme to `files` but it isn't appearing in `app.asar`.

**Comment by CosmoMyzrailGorynych** [comment] 2020-04-12 23:10
> Is this why fs.readFileSync(path.join(__dirname, "README.md")) is failing in one of my dependencies? 

Yes.

**Comment by christianbundy** [comment] 2020-04-12 23:42
Wonderful. If anyone is looking for a workaround: https://github.com/fraction/oasis-desktop/commit/d586cca912cde1acb52217e39b842befa6445f70

It uses [Patch-Package](https://github.com/ds300/patch-package), which is janky, but it's the only way that I was able to remove the `README.md` exclusion.

**Comment by mgziminsky** [comment] 2020-05-03 22:00
I'm actually getting ready to open a separate issue for this, but with the current version, a "hack" you can use to not have the defaults included is to put a dummy `FileSet` object somewhere in your files list that has a `from` value of something that doesn't exist. Everything after that will be in a separate filtering group. So if you put the dummy, or valid, object as the first entry, then no default values will be included. If you put it at the end or somewhere else, then defaults will be applied to the items above it, but can be overridden below it. Example below.

https://github.com/electron-userland/electron-builder/blob/2e49f0bb1bd8448e1c2ccc4e2eb9def77b1a04df/packages/app-builder-lib/src/fileMatcher.ts#L132-L136

```json
{
  ...
  "files": [
    // Custom filters that will have defaults applied
    "assets",
    "stuff",
    "!stuff/skip",

    // Dummy separator. Everything after this will not get the default rules and they have precedence over those above.
    // This can be a valid entry as well if you have the need
    { "from": "no-more-defaults" },

    // These should work now
    "README.md",
    "**/*.d.ts",
    "!**/nope.d.ts"
  ]
  ...
}
```

I'm not sure whether or not this is by design, but I was having the opposite issue as you two where I was having too many things included due to the defaulting rules and how FileSets are treated specially. I'm going to be opening an issue to at least fix and improve the documentation. If this isn't an intentional feature though, it's possible that they'll patch it in a future version and this trick won't work any more.

**Comment by inca** [comment] 2020-06-11 15:19
Bump. Same use case as OP: I need `.d.ts` files included.

Workarounds, albeit much appreciated, are quite nasty. This is a design flaw, which I'd very much appreciate being fixed.

**Comment by inca** [comment] 2020-06-11 16:09
Fwiw I was only able to "fix" the issue by patching [this line](https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/fileMatcher.ts#L21) and removing `.d.ts` from predefined excluded extensions.

There are uses cases which require bundling `.d.ts` into source (e.g. we use TypeScript support to develop in-app extensions). Ignoring them "by default" without actually providing a way to override these defaults makes little sense imo.

**Comment by inca** [comment] 2020-08-10 16:43
Yes, still relevant.

https://github.com/electron-userland/electron-builder/blob/f938de5aae09cb832a6f7f742e64a0d6c025fb9f/packages/app-builder-lib/src/fileMatcher.ts#L21 — if I understand correctly, this line applies extension-based filter to virtually every file resource, leaving no workarounds rather than monkey-patching `electron-builder`.

My app happens to work with TypeScript (with TypeScript being a part of app domain, rather than the technology to build the app itself), which leaves me with no choice.

**Comment by CosmoMyzrailGorynych** [comment] 2020-10-13 22:32
Stalebot is trash.
Bugs that don't get maintainers' attention are still bugs.

**Comment by CosmoMyzrailGorynych** [comment] 2020-12-17 03:51
I need a bot that replies to stalebots.

**Comment by taylorthurlow** [comment] 2020-12-17 23:27
This seems tangentially related but somehow everything in my `.gitignore` is being ignored by default when packaging the app. Removing my `/dist` directory from the gitignore causes it to be included in the package again, can't find a way to prevent that from happening.

@CosmoMyzrailGorynych I have been driven to near insanity with stale bots multiple times. They are infuriating, at best.

**Comment by CosmoMyzrailGorynych** [comment] 2021-03-31 04:39
Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?

This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Closed** 2021-06-11 00:46 UTC
Labels: backlog
