### ISSUE TITLE
electron-builder auto updater timeout

### ISSUE THREAD

**Issue by launcher-dev** [electron-userland/electron-builder#4763] opened 2020-03-10 16:57 UTC
* **22.4.0**: 

4.2.4

* **NSIS**: 

Hi, is there anyway to increase the update download timeout? I finally got auto updating to work with s3 bucket but there's an issue. If the user's internet connection is too slow, the update will not finish and an error will be thrown. After logging, the timeout is 30 seconds. I know my code is working because if I run my program on my server with fast internet, the update download finishes and auto updating works perfect. But when running my program on my computer (with my slow wifi) the auto update doesn't finish downloading, so auto updating won't work.

Is there anyway to change this timeout? Thanks

**Comment by launcher-dev** [comment] 2020-03-10 17:10
@develar maybe the legend himself knows something about this.

**Comment by pverscha** [comment] 2020-03-11 08:27
@launcher-dev duplicate of #4744

**Comment by launcher-dev** [comment] 2020-03-11 14:17
> @launcher-dev duplicate of #4744

thank you :)

**Closed** 2020-03-11 16:46 UTC
