### ISSUE TITLE
Missing Assets When Installing on Windows

### ISSUE THREAD

**Issue by turbobeast** [electron-userland/electron-builder#290] opened 2016-04-04 15:49 UTC
All the resources are contained in the `Setup.exe`. When the installer runs, I can see that all the files are `Extract`ed, but once installed, files are missing from the `/resources` folder. 
The missing files are `.exe` files, it does not seem to drop any non-`.exe` files. 

This is happening on a 64-bit, Windows 8.1 machine.

**Comment by develar** [comment] 2016-04-04 17:07
Do you use `extraResources`? Or what "resources" mean? Sorry, issue is not clear for me.

**Comment by turbobeast** [comment] 2016-04-04 17:20
Oh, I use electron-packager first to create the `.exe`. It creates a `/resources` folder that includes an `atom.asar` and  a dir with all my app files. The `Setup.exe` unzipped maintains the same structure. 

Does `extraResources` work for windows now? Maybe I need to do more research.

**Comment by turbobeast** [comment] 2016-04-04 17:39
I thought at first the files were not actually being copied/installed. But it appears that the OS seems to be deleting the files shortly after they are installed. This might not be a electron-builder issue.

**Comment by develar** [comment] 2016-04-04 17:39
> I use electron-packager first to create the .exe

You should not. electron-builder uses electron-packager under the hood. Please use only electron-builder.

> Does extraResources work for windows now?

Yes. Confirmed by @d9k.

**Comment by develar** [comment] 2016-04-04 17:41
See https://github.com/electron-userland/electron-builder/blob/master/docs/options.md extraResources

**Comment by turbobeast** [comment] 2016-04-04 18:30
Thanks. I think this is the issue http://answers.microsoft.com/en-us/windows/forum/windows8_1-files/exe-files-randomly-deleting-themselves/b26c3c82-2d59-4ff9-bcb2-9ad132488528

**Comment by develar** [comment] 2016-04-04 18:32
@turbobeast Don't think so. If you can, please share app / configs and I will try to help.

**Comment by turbobeast** [comment] 2016-04-04 18:45
I have not yet attempted to use `extraResources`. I have confirmed that the installer does copy the files over on install. But the `.exe` files disappear shortly thereafter.

**Comment by develar** [comment] 2016-04-04 18:51
@turbobeast I am not Squirrel.windows expert, but if you somehow copy resources to exe.... it seems you are doing it wrong. Additional resources issue is fixed in electron-builder using this option (it will be listed in the nuspec) and it is the only supported and recommended way. Other ways on your own risk and not tested/documented/supported.

**Comment by d9k** [comment] 2016-04-05 02:53
@turbobeast may it be that your squirrel-aware (squirrel installer events handler) code at the entry point of your app does some deleting?
> But the .exe files disappear shortly thereafter. 
which .exe do you mean? Packaged installer? Please specify it's path and name, it may be useful.

**Comment by turbobeast** [comment] 2016-04-05 14:33
I have some precompiled `.exe` files that I include with the other assets of my app. I thought the installer was failing to copy them over, but I realized that the OS is deleting them after they are copied over, so I have no reason to believe it is actually an issue with electron-builder.

I have some `.dll` files in the same directory that get copied over fine, and do not randomly disappear. It might be solved by signing the app. 

I don't think it's related to the squirrel event handlers. I currently don't do anything more than. `app.quit(); return true;` in any of the handlers.

**Comment by develar** [comment] 2016-04-05 14:36
@turbobeast No magic. If file is not listed in the spec (https://github.com/develar/windows-installer/blob/builder/src/index.js#L125), it is not included in the nupkg and is not a part of Setup.exe.

>  that get copied over fine, and do not randomly disappear

because it is a part of spec `*.dll`.

So, solution — use `extraResources`.

**Closed by develar** 2016-04-05 14:36 UTC
Labels: question, windows

**Comment by d9k** [comment] 2016-04-05 15:40
@turbobeast thank you for clear explanation.

**Comment by develar** [comment] 2016-04-06 13:14
@turbobeast I think again and decided that current behaviour is not expected and not user-friendly. 

If you somehow managed to copy  precompiled .exe files to app dist folder, it should be automatically included in the nupkg.

But I still don't understand how do you copy it. `electron-packager` will pack it into the app exe, it will be not copied to app dist folder, right? Could you please explain — maybe you have some excluded rules or something like that.

**Comment by turbobeast** [comment] 2016-04-06 19:33
I am using the two `package.json` structure with an `app/` dir. I have the binaries in the app dir with the rest of my app code and assets. Like, I said, I don't use (might switch, but haven't completed that yet) `electron-builder` for packaging, I use `electron-packager` directly to package and create the `-win32-ia32` folder. 

Once packaged, in the `-win32-ia32/resources/app` folder is everything that was originally under `app/` (`.css`, `.html`, `.js`, `.dll`, `.exe`...). 

I then run `electron-builder ./dist/MyApp-win32-ia32 --platform=win --out=./dist/`  This creates the `MyApp Setup.exe` file. If I unzip `MyApp Setup.exe`, the inner binaries are there. When I run it (install the app) on a machine, the `.exe` files  get copied over, but quickly disappear. 

I believe the machine is deleting theme, because it considers them to a be a malware threat. I don't know this for sure, but my app is not signed. 

I hope this is clear.

**Comment by develar** [comment] 2016-04-07 05:42
@turbobeast Thanks for clear explanation. `electron-builder` under the hood also packs app using `electron-packager`, so, result is not predictable.
