### ISSUE TITLE
Infinite loop when packaging

### ISSUE THREAD

**Issue by marscos** [electron-userland/electron-builder#3219] opened 2018-08-09 19:03 UTC
* **Version**: 20.26.1

* **Target**: Win -> Win

I was trying to pack an app built with `create-react-app` for the first time. However, it reaches an infinite loop, as stated in the error message. While investigating, I found #3191 got the same error as I did, but I couldn't get their solution. #3037 seems to be related as well, though I can't really tell, since it's stated to be fixed.

I apologize in advance if this should actually be an app-builder issue.

Node version: v8.9.4
NPM version: 5.6.0
Yarn version: 1.9.2

My dependencies:
```
"dependencies": {
  "electron-is-dev": "^0.3.0",
  "electron-settings": "^3.2.0",
  "needle": "^2.2.1",
  "react": "^16.4.2",
  "react-dom": "^16.4.2",
  "react-router": "^4.3.1",
  "react-router-dom": "^4.3.1",
  "react-scripts": "1.1.4"
},
"devDependencies": {
  "electron": "^2.0.6",
  "electron-builder": "^20.26.1"
}
```
Log:
```
  • electron-builder version=20.26.1
  • loaded configuration file=package.json ("build" field)
  • loaded parent configuration preset=react-cra
  • description is missed in the package.json appPackageFile=D:\Omnipart\sipint-desktop\package.json
  • author is missed in the package.json appPackageFile=D:\Omnipart\sipint-desktop\package.json
  • writing effective config file=dist\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.6 appOutDir=dist\win-unpacked
  ⨯ Infinite loop: D:\node_modules
github.com/develar/app-builder/pkg/nodeModules.(*Collector).processDependencies
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:268
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:178
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:194
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:194
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:32
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:196
github.com/develar/app-builder/pkg/nodeModules.(*Collector).readDependencyTree
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:194
github.com/develar/app-builder/pkg/nodeModules.ConfigureCommand.func1
        /Users/develar/go/src/github.com/develar/app-builder/pkg/nodeModules/tree.go:32
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*actionMixin).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/actions.go:28
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).applyActions
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:557
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).execute
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:390
github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin.(*Application).Parse
        /Users/develar/go/src/github.com/develar/app-builder/vendor/github.com/alecthomas/kingpin/app.go:222
main.main
        /Users/develar/go/src/github.com/develar/app-builder/main.go:64
runtime.main
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/proc.go:198
runtime.goexit
        /usr/local/Cellar/go/1.10.3/libexec/src/runtime/asm_amd64.s:2361

Error: D:\Omnipart\sipint-desktop\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (D:\Omnipart\sipint-desktop\node_modules\builder-util\src\util.ts:255:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at computeNodeModuleFileSets (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\out\util\appFileCopier.js:429:18)
    at D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:268:42
    at Generator.next (<anonymous>)
From previous event:
    at then (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:264:14)
From previous event:
    at _computeFileSets (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:265:10)
    at WinPackager.copyAppFiles (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:301:27)
    at D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:209:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at WinPackager.doPack (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:157:165)
    at D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:112:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\platformPackager.ts:110:95)
    at D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\packager.ts:376:24
    at Generator.next (<anonymous>)
    at xfs.stat (D:\Omnipart\sipint-desktop\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at D:\Omnipart\sipint-desktop\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\packager.ts:344:39)
    at D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\packager.ts:314:57
    at Generator.next (<anonymous>)
    at D:\Omnipart\sipint-desktop\node_modules\graceful-fs\graceful-fs.js:99:16
    at D:\Omnipart\sipint-desktop\node_modules\graceful-fs\graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\packager.ts:285:133)
    at D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\packager.ts:281:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at Packager.build (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\packager.ts:238:14)
    at build (D:\Omnipart\sipint-desktop\node_modules\app-builder-lib\src\index.ts:58:28)
    at build (D:\Omnipart\sipint-desktop\node_modules\electron-builder\src\builder.ts:227:10)
    at then (D:\Omnipart\sipint-desktop\node_modules\electron-builder\src\cli\cli.ts:42:48)
    at <anonymous>
```

**Comment by derek126** [comment] 2018-08-12 22:30
Duplicate of my issue [3113](https://github.com/electron-userland/electron-builder/issues/3113)

**Closed** 2018-09-25 01:44 UTC
