### ISSUE TITLE
connect refused: https://service.electron.build/find-build-agent?no-cache=1gmpgmg

### ISSUE THREAD

**Issue by lemonschen** [electron-userland/electron-builder#6353] opened 2021-10-18 01:14 UTC
> electron-builder --publish never --linux

  • electron-builder  version=22.10.4 os=10.0.19043
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=out\builder-effective-config.yaml
  • packaging       platform=linux arch=x64 electron=12.2.2 appOutDir=out\linux-unpacked
  • scheduling remote build  target=deb arch=x64
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1gmpgmg": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1gmpgmg": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1gmpgmg": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1gmpgmg": dial tcp 51.15.76.176:443: connectex: No connection could be made because the target machine actively refused it.  
  ⨯ E:\Development\Gitee\electron-egg\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=

        Error: E:\Development\Gitee\electron-egg\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE

            at ChildProcess.<anonymous> (E:\Development\Gitee\electron-egg\node_modules\builder-util\src\util.ts:243:14)

            at Object.onceWrapper (events.js:520:26)

            at ChildProcess.emit (events.js:400:28)

            at maybeClose (internal/child_process.js:1055:16)

            at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)

        From previous event:

            at processImmediate (internal/timers.js:464:21)

        From previous event:

            at RemoteBuilder.build (E:\Development\Gitee\electron-egg\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:52:28)

            at RemoteTarget.finishBuild (E:\Development\Gitee\electron-egg\node_modules\app-builder-lib\src\linuxPackager.ts:99:30)        

            at async Promise.all (index 1)

            at AsyncTaskManager.awaitTasks (E:\Development\Gitee\electron-egg\node_modules\builder-util\src\asyncTaskManager.ts:65:25)     

            at Packager.doBuild (E:\Development\Gitee\electron-egg\node_modules\app-builder-lib\src\packager.ts:446:5)

            at executeFinally (E:\Development\Gitee\electron-egg\node_modules\builder-util\src\promise.ts:12:14)

            at Packager._build (E:\Development\Gitee\electron-egg\node_modules\app-builder-lib\src\packager.ts:369:31)

            at Packager.build (E:\Development\Gitee\electron-egg\node_modules\app-builder-lib\src\packager.ts:333:12)

            at executeFinally (E:\Development\Gitee\electron-egg\node_modules\builder-util\src\promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-egg@1.15.0 package:linux: `electron-builder --publish never --linux`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-egg@1.15.0 package:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2021-10-18T00_42_19_751Z-debug.log
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run package:linux" terminated with exit code: 1.

**Comment by mmaietta** [comment] 2021-10-22 03:51
Duplicate of https://github.com/electron-userland/electron-builder/issues/3569#issuecomment-879545047

**Closed by mmaietta** 2021-10-22 03:51 UTC
Labels: electron-publish
