### ISSUE TITLE
Provide support for building/outputting a Flatpak as part of the build pipeline

### ISSUE THREAD

**Issue by x80486** [electron-userland/electron-builder#3212] opened 2018-08-08 20:00 UTC
I see there is a [`electron-installer-snap`](https://github.com/electron-userland/electron-installer-snap) and also an [`electron-installer-dmg`](https://github.com/electron-userland/electron-installer-dmg).

Would it be possible to have an `electron-installer-flatpak` also?

Or just support that format out-of-the box when using the `electron-builder` alone?

**Comment by Wetrain** [comment] 2018-09-26 14:11
This would be awesome, all Linux distributions support Flatpak :) unlike Snap!

**Comment by oscartbeaumont** [comment] 2019-04-18 09:45
Are there any updates on this?

**Comment by gasinvein** [comment] 2020-04-30 11:26
Isn't this a duplicate of #512?

**Closed** 2020-09-19 11:53 UTC
Labels: feature, linux
