### ISSUE TITLE
makensis.exe fails with yarn 3 when using pnp

### ISSUE THREAD

**Issue by marchaos** [electron-userland/electron-builder#6639] opened 2022-02-15 09:50 UTC
* **Election Builder Version: 22.14.13**

* **Node Version: 16**

* **Electron Version: 16.0.7**
* **Electron Type (current, beta, nightly)**

* **Target: NSIS**

I'm using yarn 3.1.1, but imagine this might affect yarn 2 - seems more of an issue with pnp. 

```
  • spawning        command=C:\Users\<user>\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe -WX -DAPP_ID=RhinoBucket -DAPP_GUID=a6cf6831-9faf-5cd2-abfa-a08114db3e2f -DUNINSTALL_APP_KEY=a6cf6831-9faf-5cd2-abfa-a08114db3e2f -DPRODUCT_NAME=RhinoBucket -DPRODUCT_FILENAME=RhinoBucket -DAPP_FILENAME=RhinoBucket -DAPP_DESCRIPTION= -DVERSION=1.0.0 -DPROJECT_DIR=C:\Users\<user>\dev\<project>\packages\electron-app -DBUILD_RESOURCES_DIR=C:\Users\<user>\dev\<project>\packages\electron-app\build -DAPP_PACKAGE_NAME=RhinoBucket -DMUI_ICON=C:\Users\<user>\dev\<project>\dist\electron\.icon-ico\icon.ico -DMUI_UNICON=C:\Users\<user>\dev\<project>\dist\electron\.icon-ico\icon.ico -DAPP_64=C:\Users\<user>\dev\<project>\dist\electron\RhinoBucket-1.0.0-x64.nsis.7z -DAPP_64_NAME=RhinoBucket-1.0.0-x64.nsis.7z -DAPP_64_HASH=8FA7811188AC802645498FDA783F14EC3F842EF6FFE444CECFEAC09582728C7C73F73BCEE77109F98A203EA9CC81F24885908BF65E749969159FBBAC72492CB2 -DCOMPANY_NAME= -DAPP_INSTALLER_STORE_FILE=rhinobucket-updater\installer.exe -DCOMPRESSION_METHOD=7z -DMULTIUSER_INSTALLMODE_ALLOW_ELEVATION -DINSTALL_MODE_PER_ALL_USERS_REQUIRED -DallowToChangeInstallationDirectory -DSHORTCUT_NAME=RhinoBucket -DUNINSTALL_DISPLAY_NAME=RhinoBucket 1.0.0 -DMUI_WELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp -DMUI_UNWELCOMEFINISHPAGE_BITMAP=${NSISDIR}\Contrib\Graphics\Wizard\nsis3-metro.bmp -DESTIMATED_SIZE=189571 -DCOMPRESS=auto -DUNINSTALLER_OUT_FILE -XOutFile "C:\Users\<user>\dev\<project>\dist\electron\RhinoBucket Setup 1.0.0.exe" -XVIProductVersion 1.0.0.0 -XVIAddVersionKey 
/LANG=1033 ProductName "RhinoBucket" -XVIAddVersionKey /LANG=1033 ProductVersion "1.0.0" -XVIAddVersionKey /LANG=1033 LegalCopyright "Copyright © 2022 " -XVIAddVersionKey /LANG=1033 FileDescription "" -XVIAddVersionKey /LANG=1033 FileVersion "1.0.0" -XVIAddVersionKey /LANG=1033 CompanyName "" -XUnicode true -XSetCompressor zlib - cwd=C:\Users\<user>\dev\<project>\.yarn\cache\app-builder-lib-npm-22.14.13-a7f366c579-a32a5ef25b.zip\node_modules\app-builder-lib\templates\nsis
  • exited          command=makensis.exe code=-4058 pid=undefined
  • async task error  error=spawn C:\Users\<user>\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe ENOENT
  ⨯ spawn C:\Users\<user>\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe ENOENT  failedTask=build stackTrace=Error: spawn C:\Users\<user>\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:477:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

The `ENOENT` seems to be caused by the `cwd` location. `cwd=C:\Users\<user>\dev\<project>\.yarn\cache\app-builder-lib-npm-22.14.13-a7f366c579-a32a5ef25b.zip\node_modules\app-builder-lib\templates\nsis` is a zip file location / yarn dep which probably needs specific logic to handle. I patch NsisTarget.js so that `cwd` was a local directory, and copied the templates into there from `app-builder-lib\templates` and now it works. 

Not sure if I'm missing some option to allow yarn deps to be resolved, but from looking at how `nsisTemplatesDir` - nothing special seems to be happening.

**Comment by mmaietta** [comment] 2022-02-16 00:50
It fails for all pnpm unfortunately. I was able to dig into where it's failing but it's unfortunately, not electron-builder code:
https://github.com/electron-userland/electron-builder/issues/6289#issuecomment-1033243907

I'd love to have pnpm support, but I don't understand how it parses the dependency tree for packaging for electron nor how to write Go.

**Comment by mmaietta** [comment] 2022-02-16 00:51
Closing this as a duplicate of #6289

**Closed by mmaietta** 2022-02-16 00:51 UTC
Labels: nsis

**Comment by burgil** [comment] 2022-06-06 20:57
Hey, I also think it's not a duplicate @mmaietta,
The other issue errors is module could not be found,
but here the issue is about nsis now spawning on yarn 3,
I am also having the same issue **only** when I package it with Nsis

**Comment by burgil** [comment] 2022-06-06 20:57
On that note @marchaos were you able to fix it?

**Comment by burgil** [comment] 2022-06-06 21:54
hOLY Moly I was just able to figure it out and it worked!
@marchaos 
We simply need to unplug it on yarn 3, but not just `it` (referring to electron-builder) we need to specifically unplug `app-builder-lib`, **But you may say, I did that, It didn't work**
## I just found out all we had to do is add the `-R` to the unplug method, after running `yarn unplug --help` I got more insights, now check it out if you run this it will work: `yarn unplug app-builder-lib -R`
