### ISSUE TITLE
Download block maps  Cannot download differentially, fallback to full download - Windows 10 - Github Private -Error: Maximum allowed size is 50 MB

### ISSUE THREAD

**Issue by hmpargi** [electron-userland/electron-builder#4676] opened 2020-02-14 06:30 UTC
**electron-builder version: ^22.3.2"
electron version: ^8.0.0"
electron-updater version: 4.2.0"
Target: Windows 10
 Github Private repository**

``` 

`[2020-02-13 22:17:34.744] [info] Checking for update
[2020-02-13 22:17:37.465] [info] Found version 1.0.0 (url: psstracker-Setup-1.0.0.exe)
[2020-02-13 22:17:37.465] [info] Downloading update from psstracker-Setup-1.0.0.exe
[2020-02-13 22:17:37.469] [info] No cached update info available
[2020-02-13 22:17:37.471] [info] Download block maps (old: "https://api.github.com/repos/myusername/psstracker/releases/assets/18021931.blockmap", new: https://api.github.com/repos/myusername/psstracker/releases/assets/18021931.blockmap)
[2020-02-13 22:17:37.934] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\har\Desktop\Myapps\epssapp\psstracker\dist\win-unpacked\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:239:26)
    at ClientRequest.<anonymous> (C:\Users\har\Desktop\Myapps\epssapp\psstracker\dist\win-unpacked\resources\app.asar\node_modules\electron-updater\node_modules\builder-util-runtime\out\httpExecutor.js:298:17)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2510:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)`
```

Please help why I am having this issue. any idea or fix please. its GitHub Pvt repo. i am trying to make it work for windows 10.

**Comment by hmpargi** [comment] 2020-02-15 17:54
This is weird, so I build my program with the following dependencies by downgrading electron version and auto-updates working on windows.

"electron": "^5.0.13",
"electron-builder": "^22.3.2"


but whenever I compile with 8.0.0 it doesn't download

**Comment by rancorfloydz** [comment] 2020-03-19 15:52
I also got the same issue 
**[error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB**

> This is kind of weird , auto-update failed but it still downloading the EXE then install it silently in the background, attach is the log


"electron-builder": "^22.4.1",
"electron": "^8.1.1",
"electron-updater": "^4.2.5",
Target: nsis
Github Private repository
node --version : v12.14.1
 npm: '6.13.7',

`
let buildOptions = {
  "appId": "com.company.writer",
  "productName": "WriterApp",
  "directories": {
    "output": "output/" + appVersion
  },
  "extraResources": [
    {
      "from": "./resources",
      "to": "./",
      "filter": [
        "**/*"
      ]
    }
  ],
  "files": [
    "**/*",
    "!**src/*",
    "!**config/*",
    "!**icons/*",
    "!**test/*",
    "!**static/*",
    "!*.db",
    "!**db/*"
  ],
  "mac": {
    "category": "public.app-category.productivity",
    "target": "dmg",
    "icon": "build/icons/mac/easywrite.icns"
  },
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64",
        ]
      }
    ],
    "icon": "build/icons/win/easywrite.ico",
    "publish" : [{
      "provider": "github",
      "private": true,
      "token": "hash"
    }],
    "certificateFile" : "private/cert-v2.pfx",
    "verifyUpdateCodeSignature" : false,
    "publisherName" : "writer-v2"
  },
  "nsis": {
    "allowToChangeInstallationDirectory": true,
    "oneClick": false
  }
}`



[main.log](https://github.com/electron-userland/electron-builder/files/4355477/main.log)

**Comment by rancorfloydz** [comment] 2020-03-19 15:57
I also got the same issue 
**[error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB**

> This is kind of weird , auto-update failed but it still downloading the EXE then install it silently in the background, attach is the log


"electron-builder": "^22.4.1",
"electron": "^8.1.1",
"electron-updater": "^4.2.5",
Target: nsis
Github Private repository
node --version : v12.14.1
 npm: '6.13.7',

`
let buildOptions = {
  "appId": "com.company.writer",
  "productName": "WriterApp",
  "directories": {
    "output": "output/" + appVersion
  },
  "extraResources": [
    {
      "from": "./resources",
      "to": "./",
      "filter": [
        "**/*"
      ]
    }
  ],
  "files": [
    "**/*",
    "!**src/*",
    "!**config/*",
    "!**icons/*",
    "!**test/*",
    "!**static/*",
    "!*.db",
    "!**db/*"
  ],
  "mac": {
    "category": "public.app-category.productivity",
    "target": "dmg",
    "icon": "build/icons/mac/easywrite.icns"
  },
  "win": {
    "target": [
      {
        "target": "nsis",
        "arch": [
          "x64",
        ]
      }
    ],
    "icon": "build/icons/win/easywrite.ico",
    "publish" : [{
      "provider": "github",
      "private": true,
      "token": "hash"
    }],
    "certificateFile" : "private/cert-v2.pfx",
    "verifyUpdateCodeSignature" : false,
    "publisherName" : "writer-v2"
  },
  "nsis": {
    "allowToChangeInstallationDirectory": true,
    "oneClick": false
  }
}`


[main.log](https://github.com/electron-userland/electron-builder/files/4355549/main.log)

**Comment by harusurv** [comment] 2020-05-21 10:46
Its still happening for some users, its a issue pretty common for electron updater, after years its still happening,  will it be ever solved?

**Comment by VitruxPT** [comment] 2020-06-16 23:04
It's still happening to me as well, it never downloads differencially because of the 50MB limit.
It seems like it's trying to download the `.exe` instead of the `.blockmap` file because the `.exe` is over 50MB however the `.blockmap` is only 84KB

- electron-builder: 22.7.0
- electron-updater: 4.3.1
- electron: 9.0.2

**Comment by coolswitch** [comment] 2020-07-15 06:39
I got a similar issue

```
2020-07-14 17:40:31 INFO AutoUpdate: No cached update info available
2020-07-14 17:40:31 INFO AutoUpdate: Download block maps (old: "https://...exe.blockmap", new: https://....blockmap)
2020-07-14 17:40:32 DEBUG AutoUpdate: [
  {
    "kind": 0,
    "start": 0,
    "end": 93151072
  }
]
2020-07-14 17:40:32 INFO AutoUpdate: Full: 90,967.84 KB, To download: 0 KB (0%)
2020-07-14 17:40:34 ERROR AutoUpdate: Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected mIVIoQ+sJcOqxBZn+QyGgtiw6i27k+LmkQo3j7BCAYlOgu9vh1yHoTMVtmqMQkWCOz8Kx+yjHUFD1+mrVfTfZw==, got Kk2y541sEKXdausV3bMTTJy/L00PhlyJ9R2gESrFZLIdwtglXXBYOCsiYM4SfHYy13vo5j49WX961KmL0er7tQ==
    at t.newError (C:\Program Files\Pitaya\resources\app.asar\dist\main.js:1:1408)
    at y.validate (C:\Program Files\Pitaya\resources\app.asar\dist\main.js:1:157342)
    at WriteStream.<anonymous> (C:\Program Files\Pitaya\resources\app.asar\dist\main.js:1:176632)
    at WriteStream.emit (events.js:223:5)
    at internal/fs/streams.js:218:14
    at C:\Program Files\Pitaya\resources\app.asar\dist\main.js:1:5818
    at FSReqCallback.oncomplete (fs.js:146:23)
```

i tried this
```
  nsis: {
      differentialPackage: false,
      ...
  },
```
it was't work


Version: 22.7.0
Electron Version:9.0.2
electron-updater Version:4.3.1

**Comment by coolswitch** [comment] 2020-07-17 09:30
In the source code  packages/builder-util-runtime/src/httpExecutor.ts 中，line 209 has the following code:
```
              if (size > 52428800) {
                callback(new Error("Maximum allowed size is 50 MB"))
                return
              }
```
It seems that it only works on  xxxxx.exe.blockmap，For differential download, you can try to delete it. When electron-updater cannot find it, it will use full download. At this time, the application should be able to update normally.

The difference download seems to download only the parts different from the history version, which will be very fast, but if the difference is > 50m, it is no different from full download.

hope that can help you

Who can help me

**Comment by coolswitch** [comment] 2020-07-17 11:13
> I got a similar issue
> 
> ```
> 2020-07-14 17:40:31 INFO AutoUpdate: No cached update info available
> 2020-07-14 17:40:31 INFO AutoUpdate: Download block maps (old: "https://...exe.blockmap", new: https://....blockmap)
> 2020-07-14 17:40:32 DEBUG AutoUpdate: [
>   {
>     "kind": 0,
>     "start": 0,
>     "end": 93151072
>   }
> ]
> 2020-07-14 17:40:32 INFO AutoUpdate: Full: 90,967.84 KB, To download: 0 KB (0%)
> 2020-07-14 17:40:34 ERROR AutoUpdate: Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected mIVIoQ+sJcOqxBZn+QyGgtiw6i27k+LmkQo3j7BCAYlOgu9vh1yHoTMVtmqMQkWCOz8Kx+yjHUFD1+mrVfTfZw==, got Kk2y541sEKXdausV3bMTTJy/L00PhlyJ9R2gESrFZLIdwtglXXBYOCsiYM4SfHYy13vo5j49WX961KmL0er7tQ==
> ```
> ...

错误日志里的sha512值，每次都不一样，怀疑是  src/differentialDownloader/DifferentialDownloader.ts，line 123:
```
    const fileOut = createWriteStream(this.options.newFile, {fd: newFileFd})

      const streams: Array<any> = []
      const digestTransform = new DigestTransform(this.blockAwareFileInfo.sha512)
      // to simply debug, do manual validation to allow file to be fully written
      digestTransform.isValidateOnEnd = false
      streams.push(digestTransform)

      // noinspection JSArrowFunctionCanBeReplacedWithShorthand
      fileOut.on("finish", () => {
        (fileOut.close as any)(() => {
          // remove from fd list because closed successfully
          fdList.splice(1, 1)
          try {
            digestTransform.validate()
          }
          catch (e) {
            reject(e)
            return
          }

          resolve()
        })
      })

      streams.push(fileOut)

      let lastStream = null
      for (const stream of streams) {
        stream.on("error", reject)
        if (lastStream == null) {
          lastStream = stream
        }
        else {
          lastStream = lastStream.pipe(stream)  // 把 fileOut.pipe(digestTransform) ? 
        }
      }
```
fileOut它不是可写流吗？
我要疯了，已经不想处理这个问题了

**Comment by fakaka** [comment] 2020-07-20 06:48
一样的问题，但是却下载下来了
```
PS D:\hairpin> Auto install update on quithub.com/repos/fakaka/hairpin-admin/releases/assets/23041319.blockmap", new: ht
Install: isSilent: true, isForceRunAfter: false/releases/assets/23041319.blockmap)
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (D:\hairpin\resources\app.asar\background.js:1:158128)
    at ClientRequest.<anonymous> (D:\hairpin\resources\app.asar\background.js:1:159644)
    at ClientRequest.emit (events.js:210:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2559:12)
    at SimpleURLLoaderWrapper.emit (events.js:210:5)
New version 1.0.9 has been downloaded to C:\Users\MJ\AppData\Local\hairpin-admin-updater\pending\update.exe
```

**Comment by aashutoshrathi** [comment] 2020-08-18 06:06
Facing similar issue
```
Checking for update
Found version 0.4.4 (url: <repo>-Setup-0.4.4.exe)
Downloading update from <repo>-Setup-0.4.4.exe
updater cache dir: C:\Users\<uname>\AppData\Local\<repo>-updater
Download block maps (old: "https://api.github.com/repos/<owner>/<repo>/releases/assets/x.blockmap", new: https://api.github.com/repos/<owner>/<repo>/releases/assets/x.blockmap)
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\aashu\AppData\Local\Programs\<repo>\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:241:26)
    at ClientRequest.<anonymous> (C:\Users\aashu\AppData\Local\Programs\<repo>\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:303:17)
    at ClientRequest.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
```

**Comment by Psycarlo** [comment] 2020-11-04 11:55
Got this error
"Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB"
I have private Github.

Versions:
"electron": "^9.0.0"
"electron-updater": "^4.3.5"
* "vue-cli-plugin-electron-builder": "~2.0.0-rc.4" *

**Comment by WinnieFE** [comment] 2020-11-14 09:31
The same problem:
 Cannot download differentially, fallback to full download: Error: Cannot download ...  status 404: Not Found

Error: sha512 checksum mismatch, expected g5tfHSEOBHCqz1slo0knGI30u84ZFygP2lpUKH61St40GKTVof+rsX5y47uKvm/uDiQ6jiKY893lJShXdRf+2w==, got GI8zjqm9R1VkoDv/OKaKBKNkUuP+EWhcGZiUpR8OVAjGmWqlWwtUBbh1gqL7CTOM7/PogUPg8lhGdK5mnHcAdQ==
  

version:
"electron": "^9.0.0"
"electron-updater": "^4.3.5"

**Comment by PByH** [comment] 2020-12-01 15:02
Faced with the same problem(

[2020-12-01 21:46:11.451] [info] Download block maps (old: "http://...exe.blockmap", new: http://...exe.blockmap)
[2020-12-01 21:46:11.496] [info] Full: 67,616.07 KB, To download: 0 KB (0%)
[2020-12-01 21:46:11.963] [error] Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch, expected DTDTy1jthl03YzqQNmYrTJyD7Oir8MBsNRlLJbX7qGGGUolyujoIozCKxVDm8bxM70Lxeh8kqGcBFNPNRuptTQ==, got Yb7wlW9RCkOtFF4rkj67ciA/94bcGL1dIoPgqxHTglM7xY00h5sosFThv+YLNJcU91wCvStnYSKBRKfhAkUXbA==

    "electron": "7.1.2",
    "electron-builder": "^21.2.0"

why this issue is closed while so many people feel hurt(

**Comment by NGrey5** [comment] 2020-12-05 04:49
Been facing this issue for a long time. I'm also baffled why this has been closed multiple times when people still have the issue. I don't see any resolution on any of the issues either.

I've tried with at least 3 different major versions of both electron and electron-builder/updater, as well as many different minor versions. Nothing seems to fix it. Note, it works fine most of the time with a public github repo, although I've run into the issue using a public before. It seems the main issue is with private repos.

Can somebody **please** provide some sort of answer to the problem, or possibly an insight as to what is going on?

Currently on 
`
"electron": "^9.2.0""electron-builder": "^22.8.0\
"electron-updater": "^4.3.4"
`

**Comment by REDDE4D** [comment] 2020-12-05 17:55
Same issue here

```
[2020-12-05 18:54:04.173] [info] Download block maps (old: "https://api.github.com/repos/REDDE4D/testing/releases/assets/29193464.blockmap", new: https://api.github.com/repos/REDDE4D/testing/releases/assets/29193464.blockmap)
[2020-12-05 18:54:04.552] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\sk290\Documents\GitHub\master-electron\dist\win-unpacked\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:241:26)
    at ClientRequest.<anonymous> (C:\Users\sk290\Documents\GitHub\master-electron\dist\win-unpacked\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:303:17)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6254)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

Version:
```
"electron": "^11.0.3"
"electron-builder": "^22.9.1"
"electron-updater": "^4.3.5"
```

**Comment by crisilva95** [comment] 2021-03-30 14:22
I'm having a similar issue downloading from my s3 bucket 'Cannot download differentially, fallback to full download: Error: Cannot download...' but my error code is 403: Forbidden, even though it was able to get the new version files without permission issues (I'm using aws4 to sign to my private s3 bucket). Doesn't make any sense.

This issue should not be closed, can someone help?

**Comment by mmaietta** [comment] 2021-03-31 15:56
Looking at the source, it seems we're using an old package: https://www.npmjs.com/package/http
I'm wondering if that has limitations with differential chunks size.

I found the history of that size change (https://github.com/electron-userland/electron-builder/commit/c5c2eeb80b9f357c18b486e94524580016009bd3), it was upped from 5MB to 50MB on 7/1/2019. I'm still not sure how those special numbers were determined or if they're just arbitrary.
https://github.com/electron-userland/electron-builder/issues/3564

I created a patch to switch it to 100mb for anyone who is willing to test it out, as I don't have an env to do so myself.
`builder-util-runtime+8.7.3.patch`
```
diff --git a/node_modules/builder-util-runtime/out/httpExecutor.js b/node_modules/builder-util-runtime/out/httpExecutor.js
index 476421c..05f537c 100644
--- a/node_modules/builder-util-runtime/out/httpExecutor.js
+++ b/node_modules/builder-util-runtime/out/httpExecutor.js
@@ -237,8 +237,8 @@ Please double check that your authentication token is correct. Due to security r
             const size = parseInt(contentLength, 10);
 
             if (size > 0) {
-              if (size > 52428800) {
-                callback(new Error("Maximum allowed size is 50 MB"));
+              if (size > 104857600) {
+                callback(new Error("Maximum allowed size is 100 MB"));
                 return;
               }
 
@@ -254,8 +254,8 @@ Please double check that your authentication token is correct. Due to security r
             } else if (result == null) {
               result = chunk;
             } else {
-              if (result.length > 52428800) {
-                callback(new Error("Maximum allowed size is 50 MB"));
+              if (result.length > 104857600) {
+                callback(new Error("Maximum allowed size is 100 MB"));
                 return;
               }
 
```

**Comment by HarunKilic** [comment] 2021-04-06 06:02
> Looking at the source, it seems we're using an old package: https://www.npmjs.com/package/http
> I'm wondering if that has limitations with differential chunks size.
> 
> I found the history of that size change ([c5c2eeb](https://github.com/electron-userland/electron-builder/commit/c5c2eeb80b9f357c18b486e94524580016009bd3)), it was upped from 5MB to 50MB on 7/1/2019. I'm still not sure how those special numbers were determined or if they're just arbitrary.
> #3564
> 
> I created a patch to switch it to 100mb for anyone who is willing to test it out, as I don't have an env to do so myself.
> `builder-util-runtime+8.7.3.patch`
> 
> ```
> diff --git a/node_modules/builder-util-runtime/out/httpExecutor.js b/node_modules/builder-util-runtime/out/httpExecutor.js
> index 476421c..05f537c 100644
> --- a/node_modules/builder-util-runtime/out/httpExecutor.js
> +++ b/node_modules/builder-util-runtime/out/httpExecutor.js
> @@ -237,8 +237,8 @@ Please double check that your authentication token is correct. Due to security r
>              const size = parseInt(contentLength, 10);
>  
>              if (size > 0) {
> -              if (size > 52428800) {
> -                callback(new Error("Maximum allowed size is 50 MB"));
> +              if (size > 104857600) {
> +                callback(new Error("Maximum allowed size is 100 MB"));
>                  return;
>                }
>  
> @@ -254,8 +254,8 @@ Please double check that your authentication token is correct. Due to security r
>              } else if (result == null) {
>                result = chunk;
>              } else {
> -              if (result.length > 52428800) {
> -                callback(new Error("Maximum allowed size is 50 MB"));
> +              if (result.length > 104857600) {
> +                callback(new Error("Maximum allowed size is 100 MB"));
>                  return;
>                }
>  
> ```

How can i apply this?

**Comment by gijsaddas** [comment] 2021-04-06 22:31
> Looking at the source, it seems we're using an old package: https://www.npmjs.com/package/http
> I'm wondering if that has limitations with differential chunks size.
> 
> I found the history of that size change ([c5c2eeb](https://github.com/electron-userland/electron-builder/commit/c5c2eeb80b9f357c18b486e94524580016009bd3)), it was upped from 5MB to 50MB on 7/1/2019. I'm still not sure how those special numbers were determined or if they're just arbitrary.
> #3564
> 
> I created a patch to switch it to 100mb for anyone who is willing to test it out, as I don't have an env to do so myself.
> `builder-util-runtime+8.7.3.patch`
> 
> ```
> diff --git a/node_modules/builder-util-runtime/out/httpExecutor.js b/node_modules/builder-util-runtime/out/httpExecutor.js
> index 476421c..05f537c 100644
> --- a/node_modules/builder-util-runtime/out/httpExecutor.js
> +++ b/node_modules/builder-util-runtime/out/httpExecutor.js
> @@ -237,8 +237,8 @@ Please double check that your authentication token is correct. Due to security r
>              const size = parseInt(contentLength, 10);
>  
>              if (size > 0) {
> -              if (size > 52428800) {
> -                callback(new Error("Maximum allowed size is 50 MB"));
> +              if (size > 104857600) {
> +                callback(new Error("Maximum allowed size is 100 MB"));
>                  return;
>                }
>  
> @@ -254,8 +254,8 @@ Please double check that your authentication token is correct. Due to security r
>              } else if (result == null) {
>                result = chunk;
>              } else {
> -              if (result.length > 52428800) {
> -                callback(new Error("Maximum allowed size is 50 MB"));
> +              if (result.length > 104857600) {
> +                callback(new Error("Maximum allowed size is 100 MB"));
>                  return;
>                }
>  
> ```

Hi, I was running into the same issue as the other people posting in this thread. I tried applying this patch. Didn't work, so I made another that patched the builder-util-runtime module **inside** the electron-updater module.

```
diff --git a/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js b/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js
index 476421c..3495f7f 100644
--- a/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js
+++ b/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js
@@ -237,8 +237,8 @@ Please double check that your authentication token is correct. Due to security r
             const size = parseInt(contentLength, 10);
 
             if (size > 0) {
-              if (size > 52428800) {
-                callback(new Error("Maximum allowed size is 50 MB"));
+              if (size > 104857600) {
+                callback(new Error("Maximum allowed size is 100 MB"));
                 return;
               }
 
@@ -254,8 +254,8 @@ Please double check that your authentication token is correct. Due to security r
             } else if (result == null) {
               result = chunk;
             } else {
-              if (result.length > 52428800) {
-                callback(new Error("Maximum allowed size is 50 MB"));
+              if (result.length > 104857600) {
+                callback(new Error("Maximum allowed size is 100 MB"));
                 return;
               }
 ```

**Comment by lalanankit** [comment] 2021-04-22 10:25
Do we have a fix for the said issue? Somehow, I temporarily managed to solve the issue by making changes to the library. This has resolved my issue.

- Go to your node_modules folder and search for "builder-util-runtime" package
- In the "out" folder look for "httpExecutor.js" file and somewhere around line#240, comment out the following three lines.
- Build a package and publish it via Github private repo.
- To check if the issue is resolved, publish a new version again and see if the download works.

The above steps solved my issue and a new log "main" file gets generated for the latest version.

Screenshot of the above steps:
![image](https://user-images.githubusercontent.com/71725903/115698829-c5888080-a384-11eb-8855-644f43ee3d8c.png)

**Comment by mmaietta** [comment] 2021-05-03 05:53
Merged.

@develar can you please perform a release cut? (and instruct me how to do so for future releases? 🙂 )

**Closed by mmaietta** 2021-05-03 05:53 UTC

**Comment by AkhmedovSH** [comment] 2021-05-04 20:03
when this commit will be released?

**Comment by AkhmedovSH** [comment] 2021-05-04 20:04
> Merged.
> 
> @develar can you please perform a release cut? (and instruct me how to do so for future releases? 🙂 )

when this comment will be released?

**Comment by develar** [comment] 2021-05-05 06:01
22.11.1 was released two days ago as a pre-release.

**Comment by AkhmedovSH** [comment] 2021-05-06 07:18
> 22.11.1 was released two days ago as a pre-release.

But this size error still exist nothing changed

**Comment by zalenskiSofteq** [comment] 2021-06-01 10:46
> > 22.11.1 was released two days ago as a pre-release.
> 
> But this size error still exist nothing changed

You should use the latest "electron-updater" package:
`"electron-updater": "^4.3.4"`

**Comment by snaildos** [comment] 2021-06-27 06:01
This is still happening.

**Comment by snaildos** [comment] 2021-06-27 06:01
Not sure its because if my application is on the old version of elec updater, and this is the new one, but I don't know how to compress my app, it's about 7mb over.. this is a pain.

**Comment by stoefln** [comment] 2021-08-09 19:40
Also happens to me. Version 4.3.9.

**Comment by snaildos** [comment] 2021-08-09 23:54
Updating to latest version resolved it for me.

**Comment by ipax77** [comment] 2021-11-14 09:49
I'm on
"electron-updater": "^4.3.9"
and
"electron-builder": "^22.3.2"
And got: Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch

**Comment by R2rog** [comment] 2022-02-11 03:19
> 

Same, has anyone solved this problem?

**Comment by keyurchitroda** [comment] 2022-03-23 11:34
I'm using electron builder to auto-update my app for mac, windows & ubuntu OS. mac & windows are working fine. But, the Ubuntu deb package app is throwing errors while it's updating as I attach error logs below. I've tried some solutions available on web but didn't get the solution.

Error: Error: ENOENT: no such file or directory, open '/opt/Centroall Tracker/resources/app-update.yml'

electron = 11.0.5
electron-builder = 22.11.17
electron-updater = 4.6.5

**Comment by mmaietta** [comment] 2022-04-07 00:51
Linux auto-update has always been AppImage only
