### ISSUE TITLE
 Unable to copy file for caching: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by MelonCode** [electron-userland/electron-builder#8508] opened 2024-09-19 08:20 UTC
* **Electron-Builder Version**: 24.13.3

* **Node Version**: 18

* **Electron Version**: 31.0.0

* **Electron Type (current, beta, nightly)**: current

* **Electron Updater Version**: 6.3.0

* **Target**: Mac (Apple Silicon  / Intel)

We've identified a recurring error during the update process for our application. The error occurs when the downloader attempts to copy a file for caching:

```[AutoUpdate] [object Promise] Unable to copy file for caching: ENOENT: no such file or directory, copyfile '/Users/USERNAME/Library/Caches/amie-desktop-updater/pending/Amie-240918.0.1-arm64-mac.zip' -> ''```

Key points:
1. This error is consistently reported by multiple users
2. It appears to occur after the download phase
3. We're using GitHub releases as update mechanism 
4. Despite this error, the update process seems to complete successfully:
   - Users have latest version after restarting the app.

There's no stack trace in the log, but if we're able to identify correctly, error originates here

https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/AppUpdater.ts#L681-L695

Where `cacheDirForPendingUpdate` is only place that could produce path containing `/pending` in the codebase  

While the error doesn't seem to prevent successful updates, its frequent occurrence across our user base, so any tips would be appreciated.

**Comment by mmaietta** [comment] 2024-09-19 16:57
This looks like a duplicate of https://github.com/electron-userland/electron-builder/issues/8507
Going to consolidate our convo there as the renaming happens here:
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/MacUpdater.ts#L122-L127
And the var is set on this line.
https://github.com/electron-userland/electron-builder/blob/3b03f27245458a0b595b7a65c8634f184d32f2fa/packages/electron-updater/src/MacUpdater.ts#L104

I'll take a look at this and continue the work on it in the other #8507

**Closed by mmaietta** 2024-09-19 16:57 UTC
