### ISSUE TITLE
MacOS Auto-Updater Stopped Working

### ISSUE THREAD

**Issue by marc-parillo** [electron-userland/electron-builder#2508] opened 2018-01-22 15:26 UTC
* **Version**: 19.54.0 

* **Electron Updater Version**: 2.19.1

* **Target**:  macOS

This issue just recently appeared when using Auto-Updater with Mac.  The error returned from the Auto-Updater script is below:  "Bad Request 400" error.   

**The updates on Mac had worked in the past and the Auto-Updater continues to work when updating the Windows version (nsis)**.  It's just Mac that has stopped working for some reason.

The file the updater is looking for (https://api.github.com/nbcnc/Orbit/releases/assets/5939990) doesn't exist -- returns 400.

"Error: Cannot download "https://api.github.com/nbcnc/Orbit/releases/assets/5939990": Error: Cannot download "https://api.github.com/repos/nbcnc/Orbit/releases/assets/5939990", status 400: Bad Request
    at /Applications/Orbit.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:74:22
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (/Applications/Orbit.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:101:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Orbit.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at /Applications/Orbit.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Orbit.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Orbit.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:332:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Orbit.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:367:11)
    at EventEmitter.ipcMain.on (/Applications/Orbit.app/Contents/Resources/app.asar/main.js:354:11)
    at emitOne (events.js:96:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/Applications/Orbit.app/Contents/Resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:194:7)"

**Comment by setpixel** [comment] 2018-01-22 22:30
@marc-parillo your repo doesn't exist

**Comment by develar** [comment] 2018-01-23 08:18
Do you use private GitHub provider or public?

**Comment by develar** [comment] 2018-01-23 08:29
I cannot reproduce for public GitHub provider.

**Comment by nbcnc** [comment] 2018-01-23 21:02
I use a **private** GH repo.  Updates only stopped working recently on MacOS and Updates continue to work under a private repo for Windows updates.  Are private repos being phased out?  I only use a private repo because I don't want to expose my source files.

**Comment by marceloromaomultilaser** [comment] 2018-02-22 15:51
Same with me!! Please, someone help us!!

**Comment by develar** [comment] 2018-02-22 18:24
As stated in the docs, private GitHub repo for specific cases. And bugs in this area are not fixed in a short term because not easy to reproduce and there are a lot of other more import issues. I will try to allocate time to investigate this issue this week.

**Comment by nbcnc** [comment] 2018-02-22 18:33
@develar is correct about the docs.  I moved my releases to an AWS S3 account and it's working again.  Not going to bother with private GitHub repos anymore.

**Comment by develar** [comment] 2018-02-22 18:40
Or you can use public github repo (not private repo with your source files). Just create public repo in your org :)

**Comment by marceloromaomultilaser** [comment] 2018-02-22 18:44
I did this, i have a repo just for upload the files. And I change my repo to public and i have the same issue. =(

But thanks @develar , i will waiting your analysis! ;-)

**Comment by marceloromaomultilaser** [comment] 2018-02-22 18:48
Just for help you:
I think the problem is that they try to download a  /app.zip  (I dont know what is this):

Look:

[2018-02-16 16:25:34.471] [info] App starting...
[2018-02-16 16:25:34.998] [info] Checking for update
[2018-02-16 16:25:37.001] [info] Found version 2.1.5 (url: Mercury-2.1.5-mac.zip, Mercury-2.1.5.dmg)
[2018-02-16 16:25:37.003] [info] Downloading update from Mercury-2.1.5-mac.zip, Mercury-2.1.5.dmg
[2018-02-16 16:25:37.083] [info] / requested
**[2018-02-16 16:25:37.092] [info] /app.zip requested**
[2018-02-16 16:25:37.821] [warn] Error: Update download failed. The server sent an invalid response. Try again later.
[2018-02-16 16:25:37.822] [error] Error: Error: Update download failed. The server sent an invalid response. Try again later.
[2018-02-16 16:25:37.822] [info] Ocorreu um erro: Error: Update download failed. The server sent an invalid response. Try again later.
[2018-02-16 16:25:37.823] [error] Error: Error: Cannot download "https://api.github.com/repos/MultilaserWeb/MercuryMac/releases/assets/6236601": Error: Cannot download "https://api.github.com/repos/MultilaserWeb/MercuryMac/releases/assets/6236601", status 400: Bad Request
    at /Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:74:22
    at ClientRequest.downloadRequest.httpExecutor.doRequest.downloadResponse (**/Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:101:11**)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:191:7)
    at URLRequest.ClientRequest.urlRequest.on (/Applications/Mercury.app/Contents/Resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:96:13)
    at URLRequest.emit (events.js:191:7)
From previous event:
    at /Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:44:12
From previous event:
    at MacUpdater.doDownloadUpdate (/Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/out/MacUpdater.js:127:11)
    at /Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:340:25
    at Generator.next (<anonymous>)
From previous event:
    at MacUpdater.downloadUpdate (/Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:382:11)
    at /Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:316:49
From previous event:
    at MacUpdater.doCheckForUpdates (/Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:353:11)
    at /Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:264:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at MacUpdater._checkForUpdates (/Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:307:11)
    at MacUpdater.checkForUpdates (/Applications/Mercury.app/Contents/Resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:213:35)
    at e (/Applications/Mercury.app/Contents/Resources/app.asar/dist/electron/main.js:1:1428)
    at App.<anonymous> (/Applications/Mercury.app/Contents/Resources/app.asar/dist/electron/main.js:1:2227)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
[2018-02-16 16:25:37.824] [info] Ocorreu um erro: Error: Cannot download "https://api.github.com/repos/MultilaserWeb/MercuryMac/releases/assets/6236601": Error: Cannot download "https://api.github.com/repos/MultilaserWeb/MercuryMac/releases/assets/6236601", status 400: Bad Request

**Comment by nbcnc** [comment] 2018-02-22 19:18
@develar you're correct, but I wanted to keep my source files private.  From what I can tell, GitHub publishes the source files with the Releases -- so I have to resort to either a private repo or an S3 AWS Bucket with limited privileges (where I can control what files are available).

**Comment by develar** [comment] 2018-02-22 19:30
@nbcnc You can simply create dedicated repo like "my-public-binaries". But yes — I am not sure is it fully legal. e.g. http://github.com/electron-userland/electron-builder-binaries/releases is not banned by  GitHub.

**Comment by marceloromaomultilaser** [comment] 2018-03-06 12:55
@develar I´ve change my repo to public but the problem persist. I dont think is limited to Private repo.

My projet:
electron-updater: 2.20.1
electron-builder: 19.55.2

Please, help us.. theres a lot of people with this problem.

**Comment by eranimo** [comment] 2018-04-10 19:53
I also have this problem with a private GitHub provider on `^19.8.0`

**Closed** 2018-07-27 07:38 UTC
Labels: electron-updater, reply-needed

**Comment by fer-fullstackdev** [comment] 2019-03-15 12:12
Hello
I have same problem. Anybody solved this problem?
Please help me.
Thanks

**Comment by almamlaka** [comment] 2020-01-21 12:29
Me too tested with windows
