### ISSUE TITLE
Electron 9 and Mac App Store: Invalid Symlink

### ISSUE THREAD

**Issue by james-criscuolo** [electron-userland/electron-builder#5033] opened 2020-06-04 13:55 UTC
* **Version**:  22.7.0

* **Electron Version**: 9.0.2
* **Electron Type (current, beta, nightly)**: current

* **Target**: mas

I attempted to do an app store build yesterday, and was rejected by the app store because of an invalid symlink (forget the exact message, sorry). Upon investigating, a symlink is being created that no longer exists at `app/Contents/Frameworks/Electron\ Framework.framework/Helpers`. This points to `Versions/Current/Helpers`, which does not exist. There are several other symlinks there, pointing into `Versions/Current`, and they all still map correctly.

My mac build still works, so I think this is just the app store being overly strict, but I did not want to go and attempt a PR to remove it without checking if it's expected or there should be a new place for that symlink to point.

Edit: This last worked with Electron 8.2.1 and electron-bulider 22.6.0, I assume the issue is the electron major version bump.

**Comment by davidwinter** [comment] 2020-06-04 19:39
I've had the same issue today with an app rejection due to the symlink.

**Comment by davidwinter** [comment] 2020-06-05 07:22
Reverting back the packages, I can confirm resolves the issue.

Is there any quick fix for this so that we can package up with Electron v9 and pass app store submissions?

**Comment by james-criscuolo** [comment] 2020-06-05 21:23
Looks like it's electron side actually, follow this: https://github.com/electron/electron/issues/23828

**Closed** 2020-08-11 23:55 UTC
Labels: backlog

**Comment by sagar-winjit** [comment] 2020-10-27 12:25
You can check this: https://github.com/electron/electron/issues/23828#issuecomment-717205771
