### ISSUE TITLE
How to build for mac app store?

### ISSUE THREAD

**Issue by mcfedr** [electron-userland/electron-builder#332] opened 2016-04-18 14:15 UTC
I cannot see to set the `platform` or `target` setting to `mas`

`electron-packager` accepts `mas` as `platform`

**Comment by develar** [comment] 2016-04-18 14:17
Not yet supported, it is easy to do, will be fixed tomorrow.

**Comment by mcfedr** [comment] 2016-04-18 14:25
Awesome response @develar 

I dont know how much you know about this. I have up to now been using `electron-packager`, in my gulp file, and a bit of code to build the package to upload for mac store.

The package is built with the tool [productbuild](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/productbuild.1.html) - basically I run

    productbuild --component "MyApp.app" "/Applications" --sign "' + codeSignPackage + '" "../../release/Myapp-mas-x64/MyApp.pkg"

Please beaware that its nessesary to use a *different* signing key to the one used to sign the `.app` 

The app one is something like '3rd Party Mac Developer Application: Company (XXX)' and the installer one is '3rd Party Mac Developer Installer: Company (XXX)'

It would be best to have a separate option for the name of the key incase I need to call it something custom.

**Comment by develar** [comment] 2016-04-18 14:29
@mcfedr Thanks for details. Yes – our current issue is that we don't use https://github.com/electron-userland/electron-osx-sign and don't use `productbuild`. Fix is — use electron-sox-sign (and, so, `productbuild`) and allow `mas` as target.

**Comment by mcfedr** [comment] 2016-04-18 14:44
Yes, I was just looking at `electron-osx-sign`, and remembered why my code doesn't use it to generate the package file, https://github.com/electron-userland/electron-osx-sign/issues/33

**Comment by adam-lynch** [comment] 2016-04-24 16:37
@develar it would be amazing if this could be added ASAP. Adding it to my book. Can you confirm that this would be the correct way to set the platform to MAS?

```json
"scripts": {
  ...
  "pack": "build",
  ...
},
"build": {
  ...
  "platform": "mas",
  ...
}
```

**Comment by develar** [comment] 2016-04-24 16:41
@adam-lynch I am working on it right now. Fix will be published tomorrow morning.

> Can you confirm that this would be the correct way to set the platform to MAS?

No. Implemented as "set `build.osx.target` to `["mas"]`" — https://github.com/electron-userland/electron-builder/wiki/Options#OsXBuildOptions-target — to the list current targets `mas` will be added.

**Comment by adam-lynch** [comment] 2016-04-24 16:51
@develar great thanks!

**Comment by develar** [comment] 2016-04-25 06:40
@mcfedr Thank you for links, it was very useful. Your feedback is important, please try 3.11 (`next` version). See https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by mcfedr** [comment] 2016-04-26 08:34
would be really nice if I could pass to the build options the name for signing, not use the same one as for app signing - https://github.com/electron-userland/electron-builder/blob/master/src/macPackager.ts#L69

**Comment by mcfedr** [comment] 2016-04-26 08:42
And now I dont get a normal osx build

**Comment by develar** [comment] 2016-04-26 08:48
> would be really nice if I could pass to the build options the name for signing, not use the same one as for app signing

Do you mean `sign` param? Yeah, it is an error. Well, I want to deprecate `sign` param. It seems, we should introduce CLI args to pass identity/installer identity names. Why env solution (define env)
```
export CSC_NAME="Developer ID Application: Your Name (code)"
export CSC_INSTALLER_NAME="your name"
```

is not suitable for you?

**Comment by develar** [comment] 2016-04-26 08:48
> And now I dont get a normal osx build

What's wrong?

**Comment by mcfedr** [comment] 2016-04-26 09:06
sign: I am starting the build from gulp - there is lots of other stuff that has to happen before electron builder is called - I would prefer to pass as the signing keys as options to the build function, as it is I did `process.env.CSC_NAME = '...'` before making the call, these seems messy to me.

Personally, I wont want to use the cli, It makes sense to me to build a solid API, and the cli on top of that, such that I am not forced to use the cli.

There are reasons why I want to be able to pass args in from gulp - some of my devs work on linux, i want them to be able make linux/windows builds - so i detect in gulp what platforms they are running on and pass only the platforms they can build for to the build function.

osx build: I dont get a 'normal' darwin build in the release folder, I have put `.build.osx.target = ['dmg','mas'] in the `package.json` but the result is a dmg with the `mas` platform, not a dmg with the `darwin` platform as I would expect.

**Comment by develar** [comment] 2016-04-26 09:43
@mcfedr Thanks for detailed feedback. All your points is valid and confirmed.

> with the mas platform, not a dmg with the darwin platform as I would expect.

Why do you want to build both if you distribute app using MAS? (no doubt, it will be fixed, but I want to know exactly why).

**Comment by mcfedr** [comment] 2016-04-26 11:36
I need both because I use one for distributing to testers and one for the store - although actually the mas build is probably ok for that as i dont need the auto-update functionality. 

Either way, I feel like this should be my choice :)

Also, to me its a bit strange to use a separate 'target' option, when both `packager` and `prebuilt add an extra `mas` platform.

**Comment by develar** [comment] 2016-04-26 11:51
> Also, to me its a bit strange to use a separate 'target' option, when both packager and prebuilt add an extra mas platform.

Your case exactly is a reason. "need both because I use one for distributing to testers and one for the store". Otherwise on execute "platform darwin" you will get "zip" + "dmg", but for testers you want only DMG (or, may be, just zip/7z). So, `target` is an elegant solution.

**Comment by mcfedr** [comment] 2016-04-26 12:04
Seems like i would just use `build({platform: 'mas'})` or `build({platform: 'darwin'})` or `build({platform: ['darwin', 'mas']})`  when i want both.

**Comment by develar** [comment] 2016-04-26 12:15
@mcfedr But configuration is the same (`build.osx`). Code signing is the same (so, certs are not downloaded twice, keychain is not created twice).

So, we decided to keep platform as OS only. `target` allows you to specify wanted distributable format (dmg, zip, mas, xz, deb, rpm, 7z, sfx, pkg, sh-installer and so on).

**Comment by develar** [comment] 2016-04-29 19:13
[3.14](https://github.com/electron-userland/electron-builder/releases/tag/v3.14.0) — you can build dmg and mas. or 7z. (`['dmg','mas']`).

**Comment by develar** [comment] 2016-05-01 13:33
Proposal: Add `identity`, `installerIdentitiy` to `build.osx`. 

So, it will be easy to pass it using programmatic API:

```js
build({
  devMetadata: {
    build: {
      osx: {
        identity: "my name"
      }
    }
  }
})
```

**Closed** 2016-05-02 07:10 UTC
Labels: enhancement, osx

**Comment by develar** [comment] 2016-05-02 08:20
Recommended way to provide entitlements — files `mas.entitlements`, `mas.inherit.entitlements`and others in the `build` directory. See https://github.com/electron-userland/electron-builder/wiki/Options#buildmas

**Comment by mcfedr** [comment] 2016-05-02 13:23
@develar these changes sound great, i'm going to check them out when im back at work

**Comment by mcfedr** [comment] 2016-05-17 09:50
Just wanted to say thanks, got my mas and dmg builds working. Things are good!

**Comment by develar** [comment] 2016-05-17 10:02
@mcfedr Thanks for confirmation, feel free to file issues if something not user-friendly/can be improved. Please be aware of https://github.com/electron-userland/electron-builder/issues/398 (non-Apple cert doesn't work on CI).

**Comment by mcfedr** [comment] 2016-05-17 11:43
Thanks, I'm currently only signing with apple certs so its not a problem.

It might be of help, we use this tool, https://github.com/ekreative/xcode-build-tools, for helping create a keychain on CI server
