### ISSUE TITLE
S3 Provider fails to upload

### ISSUE THREAD

**Issue by brandonhilkert** [electron-userland/electron-builder#1618] opened 2017-06-05 21:04 UTC
* **Version**: 18.3.0

* **Electron-Updater**: 2.0.0

* **Target**: OSX/Windows

I'm using the S3 provider. I can confirm my ENV vars are set properly by successfully uploading via the command line using the `aws` tool. However, when I go to publish I get:

```
Error: Cannot cleanup:

Error #1 --------------------------------------------------------------------------------
AccessDenied: Access Denied
    at Request.extractError (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/services/s3.js:539:35)
    at Request.callListeners (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:682:14)
    at Request.transition (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:684:12)
    at Request.callListeners (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at callNextListener (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/sequential_executor.js:95:12)
    at IncomingMessage.onEnd (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/event_listeners.js:256:13)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
From previous event:
    at Request.promise (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/node_modules/aws-sdk/lib/request.js:776:12)
    at /Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/src/uploader.ts:86:153
    at Timeout.tryRun [as _onTimeout] (/Users/bhilkert/Dropbox/code/bark-desktop/node_modules/electron-publisher-s3/src/uploader.ts:198:9)
    at ontimeout (timers.js:386:14)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
```

**Comment by develar** [comment] 2017-06-05 21:13
Could you please specify version of electron-publisher-s3? And try to use latest electron-builder?

**Comment by brandonhilkert** [comment] 2017-06-05 21:14
I originally missed the `Cannot cleanup` line, which mean me realize it's possible it needed more than just `PutObject` permissions. I allowed all actions and it worked. Can you confirm the minimal permissions for the S3 provider?

`electron-publisher-s3`: 18.5.0

**Comment by brandonhilkert** [comment] 2017-06-09 20:34
Closing b/c increased permissions seems to have resolved it.

**Comment by develar** [comment] 2017-06-11 18:09
Reopened — question "Can you confirm the minimal permissions for the S3 provider?" is not answered, we must do something smart to save user's time.

**Comment by kasprownik** [comment] 2017-07-11 08:24
Same problem here, what are the minimal working permissions?

**Comment by dsagal** [comment] 2017-07-12 04:29
In case this helps anyone, I had a similar symptom that was caused by using a non-default AWS profile. The `aws` tool uses `AWS_DEFAULT_PROFILE` variable, but the SDK ignores it and uses only `AWS_PROFILE`. If you use a non-default profile, you need to set the latter one. (See also [here](https://github.com/gruntwork-io/terragrunt/issues/105).)

**Comment by romanrev** [comment] 2017-07-12 07:25
@dsagal and @develar that's what we ended up with after trailing the CloudTrail logs for the requests issued by the `electron-builder`:
``` json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowBugdojoDesktopAppS3Releases",
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:ListMultipartUploadParts",
                "s3:PutObject",
                "s3:PutObjectAcl"
            ],
            "Resource": [
                "arn:aws:s3:::release-bucket/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads"
            ],
            "Resource": [
                "arn:aws:s3:::release-bucket"
            ]
        }
    ]
}
```
notice the `*ObjectAcl` actions that we need to allow: that's because the `electron-build` adds a header ` "x-amz-acl": "public-read"` with each upload - trying to mark every object as publicly readable. I am going to open another issue to ask the developers to make that optional, since one can also achieve the same effect with appropriately crafted S3 bucket policy.

**Comment by develar** [comment] 2017-07-12 07:49
@romanrev Thanks (official docs: http://docs.aws.amazon.com/AmazonS3/latest/dev/mpuAndPermissions.html)

**Comment by romanrev** [comment] 2017-07-12 07:54
thanks @develar yes, that's what we looked at after we saw the `CreateMultiPartUpload` call :-)

**Comment by develar** [comment] 2017-07-12 08:18
19.16.0 — you can set `acl` to `null` to disable adding. Will be released today.

**Closed** 2017-07-12 12:01 UTC
Labels: deployment

**Comment by emilbruckner** [comment] 2018-01-17 17:30
To everyone coming from the docs who is as stupid as I am:

You have to change your bucket-name in these permissions …

**Comment by kalokiston** [comment] 2018-04-27 01:57
I needed `s3:GetBucketLocation` as well.

**Comment by PriscilaAlves** [comment] 2018-09-24 17:52
I also needed `s3:GetBucketLocation`. This should probably be referred to in the documentation.

**Comment by JM-Mendez** [comment] 2018-09-29 20:04
@kalokiston @PriscilaAlves 

Do you have your bucket in a region besides the default US East (N. Virginia)? 

I didn't need to add the `s3:GetBucketLocation` permission. But I'm using the default region, so wondering if it's just falling back to that region.

**Comment by mlynch** [comment] 2018-10-19 15:18
Thanks for the policy example! What do you all use for your `Principal` fields? Can't create a bucket policy without it and it seems like the two entries should have different values for that field.

**Comment by JM-Mendez** [comment] 2018-10-19 16:39
@mlynch you have two options

1. use `*` and allow everyone access to your bucket _**(not recommended)**_
2. create an iam user and use it's access key for the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

Then add the user to the policy. I named my iam user `ci_server`
```json
"Sid": "Stmt123456789",
"Effect": "Allow",
"Principal": {
    "AWS": "arn:aws:iam::1234567890:user/ci_server"
 },
```

**Comment by mlynch** [comment] 2018-10-19 16:48
Thanks, though there are two operations here. It seems you want to allow read access to everyone (so users can see and download new versions), but only write access to an IAM user, correct? That would mean two separate principal options?

**Comment by JM-Mendez** [comment] 2018-10-19 16:54
@mlynch If you want to give users direct access to your bucket, then yeah, you'd need to set up those two levels of access. But I recommend using cloudfront. 

The data transfer pricing is cheaper than having users download directly from s3. And when you set up cloudfront, it'll ask to add a policy to the bucket for you.

Here are some articles that led me to this conclusion:

https://medium.com/devopslinks/this-is-how-i-reduced-my-cloudfront-bills-by-80-a7b0dfb24128

https://www.expatsoftware.com/articles/2009/01/cloudfront-costs-compared-to-s3.html

**Comment by mlynch** [comment] 2018-10-19 17:40
Awesome thanks so much! Also probably petter download performance for users around the globe I’d imagine

**Comment by JM-Mendez** [comment] 2018-10-19 17:48
You're welcome :-). 

Yeah you'll get way better download performance since your app will be distributed across the edge network, and will be much closer to your users. 

One thing to keep in mind -- distributing to cloudfront is not immediate. I've seen an average of 20-30 min for full availability. So if you want to test publishing, use minio server like the guide suggests. The cloudfront url is static, so it doesn't affect publishing.

**Comment by dariocravero** [comment] 2018-11-27 20:31
Thanks for the policy guide! I wanted to add that apart from setting I also had to uncheck the `Block new public ACLs and uploading public objects (Recommended)` option in the `Permissions` tab for it to let me upload, otherwise I kept on getting `Access Denied`.

<img width="1575" alt="screenshot 2018-11-27 at 20 28 18" src="https://user-images.githubusercontent.com/376268/49109702-4c53d480-f283-11e8-934a-76d221ca7863.png">

**Comment by erikjalevik** [comment] 2019-02-08 13:00
@JM-Mendez, if I use CloudFront for serving my updates, how do I configure the electron-updater inside my app to use the CloudFront URL instead of trying to access S3 directly?

**Comment by erikjalevik** [comment] 2019-02-08 15:04
> @JM-Mendez, if I use CloudFront for serving my updates, how do I configure the electron-updater inside my app to use the CloudFront URL instead of trying to access S3 directly?

Using `autoUpdate.setFeedURL` seems to do the trick, but then a deprecation message appears in the log: "Feed url Deprecated. Do not use it."

What is the correct way?

**Comment by JM-Mendez** [comment] 2019-02-08 17:20
@erikjalevik this is how I did it. Are you sure you're calling `setFeedUrl` and not `getFeedUrl`? The latter is the one that's deprecated according to the source code

https://github.com/electron-userland/electron-builder/blob/2c674df1333ae0e594ef99c9012d81cc8ddfa30d/packages/electron-updater/src/AppUpdater.ts#L183-L185

https://github.com/electron-userland/electron-builder/blob/2c674df1333ae0e594ef99c9012d81cc8ddfa30d/packages/electron-updater/src/AppUpdater.ts#L191-L205

**Comment by stuartcusackie** [comment] 2019-07-08 15:00
> Thanks for the policy guide! I wanted to add that apart from setting I also had to uncheck the `Block new public ACLs and uploading public objects (Recommended)` option in the `Permissions` tab for it to let me upload, otherwise I kept on getting `Access Denied`.
> 
> <img alt="screenshot 2018-11-27 at 20 28 18" width="1575" src="https://user-images.githubusercontent.com/376268/49109702-4c53d480-f283-11e8-934a-76d221ca7863.png">
> 
> EDIT: I also had to uncheck the second option `Remove public access granted through public ACLs (Recommended) ` otherwise the app wasn't able to look for updates.

The labels have changed. Is this safe??

![image](https://user-images.githubusercontent.com/20210934/60820522-82522300-a199-11e9-9051-11197a51a781.png)

**Comment by kersten** [comment] 2019-09-16 19:33
Sorry to bother u again with this issue, but i can't upload to S3 I always get the error like the issue opener.

**Comment by laurenschroeder** [comment] 2020-05-01 15:12
I was able to get this working for a private bucket after setting ACL to 'private':

``` 
 "publish": {    
      "provider": "s3",    
      "bucket": "bucket-name",    
      "region": "us-east-2",    
      "acl": "private"    
    }
```

**Comment by navelDirt** [comment] 2023-01-12 02:10
> I was able to get this working for a private bucket after setting ACL to 'private':
> 
> ```
>  "publish": {    
>       "provider": "s3",    
>       "bucket": "bucket-name",    
>       "region": "us-east-2",    
>       "acl": "private"    
>     }
> ```

This worked for me, thanks!

**Comment by jackhodkinson** [comment] 2024-03-25 17:51
I have setup my iam user to have full AWS access and setup the bucket to allow ACLs, however, I still get the following error when I try to build *unless* `acl` is set to `private` as mentioned above.

<img width="1164" alt="image" src="https://github.com/electron-userland/electron-builder/assets/17097025/7d227618-aa05-4eff-813a-758244fcd76e">

```
AccessControlListNotSupported: The bucket does not allow ACLs
```

Setting `acl` to `private` makes the build work, however, when I try to use the `autoUpdater` in my main process I'm seeing an error because my AWS keys are not included in the build.

In my `index.ts` file in the main process I have:

```typescript
import { autoUpdater } from "electron-updater"

autoUpdater.on('update-downloaded', (event) => {
  const dialogOpts = {
    type: 'info' as const,
    buttons: ['Restart', 'Later'],
    title: 'Application Update',
    message: String(process.platform === 'win32' ? event.releaseNotes : event.releaseName),
    detail: 'A new version has been downloaded. Restart the application to apply the updates.'
  }

  dialog.showMessageBox(dialogOpts).then((returnValue) => {
    if (returnValue.response === 0) autoUpdater.quitAndInstall()
  })
})

autoUpdater.on('error', (message) => {
  console.error('There was a problem updating the application')
  console.error(message)
})
```

When I run this I get a 403:

```
HttpError: 403 Forbidden
"method: GET url: https://<bucketName>.s3.amazonaws.com/latest-mac.yml?noCache=...

Data:
  <?xml version=\"1.0\" encoding=\"UTF-8\"?>
    <Error><Code>AccessDenied</Code><Message>Access Denied</Message><Reques...
  File "app:///node_modules/builder-util-runtime/out/httpExecutor.js", line 14, in createHttpError
  File "app:///node_modules/builder-util-runtime/out/httpExecutor.js", line 147, in IncomingMessage.<anonymous>
...
```

I suppose we can get around this by baking in the AWS keys into the main process, but idk how I feel about baking in credentials into the build. Alternatively I've seen people discuss using a server to pass credentials to the app, but I don't need a server for anything else so that seems excessive.

Are the only options here to either make the bucket completely public OR bake in some limited credentials to access the bucket? Are there any best practices here?

**Comment by Harukisatoh** [comment] 2025-09-26 19:35
> I have setup my iam user to have full AWS access and setup the bucket to allow ACLs, however, I still get the following error when I try to build _unless_ `acl` is set to `private` as mentioned above.
> 
> <img alt="image" width="1164" src="https://private-user-images.githubusercontent.com/17097025/316601862-7d227618-aa05-4eff-813a-758244fcd76e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTg5MTU1NzEsIm5iZiI6MTc1ODkxNTI3MSwicGF0aCI6Ii8xNzA5NzAyNS8zMTY2MDE4NjItN2QyMjc2MTgtYWEwNS00ZWZmLTgxM2EtNzU4MjQ0ZmNkNzZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA5MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwOTI2VDE5MzQzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNmE1MjY1NjE0ZjAyZDljZGQ5MGI2ZWI4YzExYzQ0ZjY0N2E5NDYwNGI0MTJkYTVmNmNlZDlhZjA3M2MyYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XiT97kYuP0bte0LrR0a0njEz1bv7BOuxFnrVqK4n5BI">
> ```
> AccessControlListNotSupported: The bucket does not allow ACLs
> ```
> 
> Setting `acl` to `private` makes the build work, however, when I try to use the `autoUpdater` in my main process I'm seeing an error because my AWS keys are not included in the build.
> 
> In my `index.ts` file in the main process I have:
> 
> import { autoUpdater } from "electron-updater"
> 
> autoUpdater.on('update-downloaded', (event) => {
>   const dialogOpts = {
>     type: 'info' as const,
>     buttons: ['Restart', 'Later'],
>     title: 'Application Update',
>     message: String(process.platform === 'win32' ? event.releaseNotes : event.releaseName),
>     detail: 'A new version has been downloaded. Restart the application to apply the updates.'
>   }
> 
>   dialog.showMessageBox(dialogOpts).then((returnValue) => {
>     if (returnValue.response === 0) autoUpdater.quitAndInstall()
>   })
> })
> 
> autoUpdater.on('error', (message) => {
>   console.error('There was a problem updating the application')
>   console.error(message)
> })
> When I run this I get a 403:
> 
> ```
> HttpError: 403 Forbidden
> "method: GET url: https://<bucketName>.s3.amazonaws.com/latest-mac.yml?noCache=...
> 
> Data:
>   <?xml version=\"1.0\" encoding=\"UTF-8\"?>
>     <Error><Code>AccessDenied</Code><Message>Access Denied</Message><Reques...
>   File "app:///node_modules/builder-util-runtime/out/httpExecutor.js", line 14, in createHttpError
>   File "app:///node_modules/builder-util-runtime/out/httpExecutor.js", line 147, in IncomingMessage.<anonymous>
> ...
> ```
> 
> I suppose we can get around this by baking in the AWS keys into the main process, but idk how I feel about baking in credentials into the build. Alternatively I've seen people discuss using a server to pass credentials to the app, but I don't need a server for anything else so that seems excessive.
> 
> Are the only options here to either make the bucket completely public OR bake in some limited credentials to access the bucket? Are there any best practices here?

I'm having the same issue as well, ACL is allowed everywhere, but still the CI build fails. Anyone with a solution to this problem?
