### ISSUE TITLE
All icons work except the linux window manager icon

### ISSUE THREAD

**Issue by pliablepixels** [electron-userland/electron-builder#3332] opened 2018-09-17 22:54 UTC
Version: 20.28.3
Target: linux

Hi, I have my config setup perfectly for windows, mac and linux builds. On linux, I get all the icons correctly (launchpad/app/etc) except the window manager icon (circled in red). Any ideas how to configure it?

![screen_shot_2018-09-10_at_3 43 41_pm](https://user-images.githubusercontent.com/4116654/45654696-bf361780-baaa-11e8-8056-aa6eac4a8661.png)

My config file:

```
  "scripts": {
    "electron": "electron .",
    "dist-mac": "./electron_js/sync_versions.sh && electron-builder -m",
    "dist-win": "./electron_js/sync_versions.sh && electron-builder -w",
    "dist-lin": "./electron_js/sync_versions.sh && electron-builder -l",
    "dist-all": "./electron_js/sync_versions.sh && electron-builder -mwl"
  },
  "main": "electron_js/main.js",
  "build": {
    "appId": "com.pliablepixels.zmninjapro",
    "productName": "zmninjapro",
    "compression": "normal",
    "asar": true,
    "directories": {
      "buildResources": "electron_js/icons"
    },
    "files": [
      "electron_js/main.js",
      "www/**/*",
      "!node_modules/**/*"
    ],
    "extraResources": [
      "node_modules/electron-window-state/**/*",
      "node_modules/jsonfile/**/*",
      "node_modules/mkdirp/**/*",
      "node_modules/deep-equal/**/*",
      "node_modules/minimist/**/*",
      "node_modules/menu/**/*",
      "node_modules/clivas/**/*",
      "node_modules/keypress/**/*"
    ],
   
    "mac": {
      "category": "productivity",
      "target": "dmg",
      "icon": "icon.png"
    },
    "win": {
      "icon": "icon.ico",
      "target": [
        {
          "target": "nsis",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "linux": {
      "category": "Utility",
      "target": [
        {
          "target": "AppImage",
          "arch": [
            "x64",
            "ia32",
            "armv7l"
          ]
        }
      ]
    }
```

**Comment by CorySanin** [comment] 2018-09-29 08:41
This isn't an issue with electron-builder. The problem is the path you specify [here](https://github.com/pliablepixels/zmNinja/blob/master/electron_js/main.js#L59) points to a file that doesn't exist. See my pull request for more info 😀

**Comment by CorySanin** [comment] 2018-10-03 04:02
From what I gathered, the problem was caused by 2 things:

- The wrong icon path was being used, [here's the correct one](https://github.com/pliablepixels/zmNinja/pull/712/files#diff-cb0fec148a59662a0b54665241e92f6cR59)
- The icon wasn't included in the asar archive, which was fixed by [adding this](https://github.com/pliablepixels/zmNinja/pull/712/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R135)

**Closed** 2018-10-20 22:39 UTC
