### ISSUE TITLE
autoupdater.quitAndInstall don't relaunch and update success

### ISSUE THREAD

**Issue by FanShiDe** [electron-userland/electron-builder#3402] opened 2018-10-18 15:55 UTC
* **electron-builder**: 20.28.4

* **electron-updater**: 3.1.2

* **Target**:  Mac

click `Restart now` can relaunch because of `app.relaunch();app.exit()`, but cant update from the downloaded update file. Then will launch app and show dialog again and so on, repeated cycle.
@develar @maczikasz, thx.
```js
index = dialog.showMessageBox({
          type: 'info',
          buttons: ['Restart now', 'later'],
          title: 'Updates downloaded',
          message: Message.downloaded + meta.version,
          detail: meta.readme,
        });
        if (index === 0) {
          try {
            autoUpdater.quitAndInstall();
            setTimeout(() => {
              app.relaunch();
              app.exit(0);
            }, 6000);
          } catch (e) {
            dialog.showErrorBox('Error', 'Failed to install updates');
          }
        }
      } else {
        delFile(pkgCacheDir);
        dialog.showMessageBox({
          type: 'warning',
          buttons: ['OK'],
          title: 'Updates downloaded fail',
          message: global.localizedStrings.pkgSignFailMessage,
          detail: global.localizedStrings.pkgSignFailDetail,
        });
      }
```

Error:
```txt
[2018-10-19 00:02:55:0774] [error] Error: Error: No update available, can't quit and install
    at MacUpdater.quitAndInstall (/Users/cuitfanshide/Documents/Projects/7-dragon-ball-wallet-2c/dist/mac/WOOKONG Solo.app/Contents/Resources/app/node_modules/electron-updater/src/MacUpdater.ts:149:24)
    at /Users/cuitfanshide/Documents/Projects/7-dragon-ball-wallet-2c/dist/mac/WOOKONG Solo.app/Contents/Resources/app/dist/main.js:910:43
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

```

**Comment by adammeyer** [comment] 2018-10-18 18:00
I'm seeing the same thing.  Same versions.

**Comment by tassoevan** [comment] 2018-10-30 01:43
Workaround: downgrade `electron-updater` to 3.0.4 (#3269). Can anyone confirm if update it to latest version works?

**Comment by FanShiDe** [comment] 2018-10-30 02:47
The `electron-updater 3.1.2` add a downloaded file path called `__update__`，I need to find this path and do a security check on the update file under the path. So I update to the latest version because of the previous versions do not have this feature.

**Comment by develar** [comment] 2018-10-30 06:41
Please try 3.1.5

**Comment by steffanhalv** [comment] 2018-10-31 12:11
@develar I have same issue with 3.1.6 ..

**Comment by dscalzi** [comment] 2018-11-04 06:12
Same issues.

**Comment by steffanhalv** [comment] 2018-11-04 10:18
My problem was that this folder was created as root and was not writeable:

~/Caches/com.appname.AppName.ShipIt

Doing `sudo chown $USER ~/Caches/com.appname.AppName.ShipIt` fixed the problem and I solved this in app by asking user for password and run that code with child_process if it fails.

I dont know if ship it or electron updater is the cause of this problem, but I think it has to be one of them ^^.

**Comment by develar** [comment] 2018-11-08 08:33
```
try {
            autoUpdater.quitAndInstall();
            setTimeout(() => {
              app.relaunch();
              app.exit(0);
            }, 6000);
          } catch (e) {
            dialog.showErrorBox('Error', 'Failed to install updates');
          }
```

This code is not correct.

```
setImmediate(() => {
  autoUpdater.quitAndInstall();
})
```

is enough — you need to wrap quitAndInstall in setImmediate if called from dialog. And no need to call relaunch/exit.

Also, please use latest released version — number of possible issues are fixed now.

**Closed by develar** 2018-11-08 08:33 UTC

**Comment by steffanhalv** [comment] 2018-11-11 13:59
@bannik Have you tried this?

`sudo chown $USER ~/Caches/com.appname.AppName.ShipIt`

Replace appname domain with yours.
This fixed it for me as it gives access to the update folder for current user.

I would be happy if anyone had the same issue as me, so we can find a way to solve it.

**Comment by AMoreaux** [comment] 2018-11-11 14:07
I wrap the quitAndInstall in a setTimeout of 3500ms. It’s dirty but it works for me.

**Comment by FanShiDe** [comment] 2018-11-12 01:58
> I wrap the quitAndInstall in a setTimeout of 3500ms. It’s dirty but it works for me.

@AMoreaux I think it is just working on sometimes, it is unstable

**Comment by zoe0316** [comment] 2019-08-09 09:17
> ```
> try {
>             autoUpdater.quitAndInstall();
>             setTimeout(() => {
>               app.relaunch();
>               app.exit(0);
>             }, 6000);
>           } catch (e) {
>             dialog.showErrorBox('Error', 'Failed to install updates');
>           }
> ```
> 
> This code is not correct.
> 
> ```
> setImmediate(() => {
>   autoUpdater.quitAndInstall();
> })
> ```
> 
> is enough — you need to wrap quitAndInstall in setImmediate if called from dialog. And no need to call relaunch/exit.
> 
> Also, please use latest released versions of electron-updater/electron-builder/electron — number of possible issues are fixed now.

it works!

**Comment by ednew2018** [comment] 2019-09-26 06:10
I just quit using autoupdater.quitAndInstall

**Comment by spcBackToLife** [comment] 2020-04-15 09:06
I still doesn't work in electron-updater@4.2.5

**Comment by perf2711** [comment] 2020-05-19 06:29
If anyone is still stumbling with this issue (at least on Windows), check if you're not setting `closable: false` on options passed to `new BrowserWindow(opts)`.

**Comment by DaveLomber** [comment] 2020-11-09 15:48
Same issue

this simply does not work with `"electron-updater": "^4.3.4"`

  ```
     setImmediate(() => {
        autoUpdater.quitAndInstall();
      });
  ```

it hides the app but does not close, so I can click on it and still use same ver. macOS

**Comment by lilong7676** [comment] 2021-02-04 02:55
still doesn't work in electron-updater@4.3.5 on macos 10.15.7

**Comment by Z4RV15** [comment] 2021-02-05 11:16
@lilong7676 
Even I m facing the same issue. Did u get any work arounds?

Tried to call app.relaunch() in 'before-quit' event, but it re-launches the old instance of the app.

**Comment by lilong7676** [comment] 2021-02-05 11:21
> @lilong7676 
> 
> Even I m facing the same issue. Did u get any work arounds?
> 
> 
> 
> Tried to call app.relaunch() in 'before-quit' event, but it re-launches the old instance of the app.

downgrade to electron 11.1.1 works for me

**Comment by Z4RV15** [comment] 2021-02-05 11:34
> > @lilong7676
> > Even I m facing the same issue. Did u get any work arounds?
> > Tried to call app.relaunch() in 'before-quit' event, but it re-launches the old instance of the app.
> 
> downgrade to electron 11.1.1 works for me

Using electron v7.1.2 still not working.
Can't change the electron version, any other solution?

**Comment by DaveLomber** [comment] 2021-02-05 11:44
In my case I just fu**ed up with 

```
win.on('close', event => {

}
```

I prevent it to close the app properly  by calling `event.preventDefault();`

so in the end it was a mistake with my code rather than Electron

**Comment by jeffcrouse** [comment] 2021-02-25 00:20
I'm using electron ^9.1.1, electron-builder ^22.7.0, electron-updater ^4.3.5, and my app isn't restarting after an update on OSX. It works fine on Windows.

I've removed all exit handlers app.on('window-all-closed') and app.on('before-quit') just in case they were messing with shutdown, but no luck. I should also mention that it had been working, but just stopped working recently. Not sure what happened.  The code I'm using is

```
  autoUpdater.on('update-downloaded', () => {
    autoUpdater.quitAndInstall(true, true);
  });
```

Are there any new solutions/suggestions?  Thanks!

**Comment by hussa6** [comment] 2021-12-18 01:29
Why was this issue closed? Any fixes found?
