### ISSUE TITLE
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB

### ISSUE THREAD

**Issue by connectian1** [electron-userland/electron-builder#5836] opened 2021-04-27 16:05 UTC
* **Electron-builder Version**:  22.10.5
* Electron-updater Version: 4.3.5
* **Electron Version**: 12.0.4
* Target: Windows

I am using Github repo but both with private or public, I always get the same error:

Download block maps (old: xxx, new: xxx)
Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB.

My understanding is that it is skipping on downloading the block maps (only 80kb) and it is trying to download the exe (85MB).
I am stuck and don't know why this is happening.
Does anyone please know why or any workaround you are using to go on? 
I have seen this error multiple times in here, but never a solution.

**Comment by mitmelon** [comment] 2021-04-27 19:30
Am having same issue too  the downloading url=https://github.com/electron/electron/releases/download/v
2.0.5/electron-v12.0.5-win32-x64.zip size=83 MB parts=8 is not downloading.

I tried the download url directly on browser https://github.com/electron/electron/releases/download/v
2.0.5/electron-v12.0.5-win32-x64.zip but this url does not exist... Nothing is found on the link to download. Thats why the error is comming up...

This is a bug which should be corrected.

**Comment by connectian1** [comment] 2021-04-29 08:12
Can anybody help here??? At least acnowledge this issue, since it is blocking.

**Comment by mmaietta** [comment] 2021-05-09 05:24
Since it's referring to the 50mb max size limit, we've increased the limit to help reduce one of the bug vectors and see if we can catch any cascading issues, such as specifically re: blockmaps.
Closing for now with the merged PR, it's released in v22.11.5.
Please reopen if it reproduces and can provide more logs. Thanks!

**Closed by mmaietta** 2021-05-09 05:24 UTC

**Comment by Mgonand** [comment] 2021-06-03 18:51
Hi @mmaietta , I think I can throw some light here with my own error.
I have this versions:
```
"electron-updater": "^4.3.9",
"electron-builder": "^22.11.5",
```
Well, my error its pretty much the same as the author but I'm not having the "Maximum allowed size is 50 MB" anymore, instead I have this: `Error: Cannot parse blockmap "https://api.github.com/repos/BinPar/SintesisDesktopAPP/releases/assets/38021935.blockmap", error: Error: incorrect header check, raw data:` and the raw data of the buffer looks like the data of the installer (.exe) instead of blockmap.
I think the error comes from here:
https://github.com/electron-userland/electron-builder/blob/dc359de5019807a014c62468385dfb14bbb5bd83/packages/electron-updater/src/NsisUpdater.ts#L154-L159

As you can see in the link that asset is not pointing to the blockmap, its pointing to the .exe

Probably, in some case scenarios the updater is not reading the release correctly (github API change maybe?), I don't know for sure.

Hope this helps since I'm having a hard time here with the auto update. 

For the record: If I download the .blockmap from the github web and try to do `zlib.gunzipSync` it works fine and the JSON data its there.

**Comment by Mgonand** [comment] 2021-06-04 15:59
I figured out what is going on in my case.
I have this config:
```json

  "build": {
    ...
    "publish": [
      {
        "provider": "github",
        "owner": "BinPar",
        "repo": "SintesisDesktopAPP",
        "token": "github token",
        "private": false,
        "releaseType": "release",
        "publishAutoUpdate": true
      }
    ]
  }
```

I just need the token for the upload part but this code here ignores that private is `false` and creates a PrivateGitHubProvider:
https://github.com/electron-userland/electron-builder/blob/dc359de5019807a014c62468385dfb14bbb5bd83/packages/electron-updater/src/providerFactory.ts#L29-L38

This lead me to two questions:
Is this the intentional behavior? I think should be better to change that if to something like:
```js
if (token == null || githubOptions.private === false) {
```
Why is not working with a private github repository if the token has the correct permissions?

If someone land here with this kind of problem, the solution is to remove the "token" property from your "publish" configuration and use the environment variable GH_TOKEN or GITHUB_TOKEN.

Last thought: A new error grows when everything seems to be right (#5940):
```
Cannot download differentially, fallback to full download: Error: sha512 checksum mismatch
```
