### ISSUE TITLE
Packaging Electron v5 with sandbox (linux)

### ISSUE THREAD

**Issue by thomasnordquist** [electron-userland/electron-builder#3872] opened 2019-05-03 12:21 UTC
With electron 5 the sandbox is enabled by default. The sandbox requires elevated rights to run.
This can be achieved if the kernel has `kernel.unprivileged_userns_clone` enabled or a SUID flag is set on `chrome-sandbox`.

If `unprivileged_userns_clone` is disabled (default for Arch) the SUID-flag is required.

To disable / enable said kernel feature:
```
sudo sysctl kernel.unprivileged_userns_clone=0
```

Snaps cannot use the SUID flag (automatic app review) and seem to prevent access to the kernel feature.

One can disable the sandbox by running electron with the `--no-sandbox` argument.

As a workaround, I currently use an after-pack hook to wrap the electron binary and append the `--no-sandbox` argument, which seemed to be to be the only way to add the sandbox argument. (`app.commandLine.appendSwitch` does not work since electron has already launched)
https://github.com/thomasnordquist/MQTT-Explorer/blob/master/scripts/afterPack.ts

Electron issue concerning this: https://github.com/electron/electron/issues/17972

**Comment by burtonator** [comment] 2019-05-11 15:12
Can't the old behavior be resolved by specifying ```sandbox: false``` in the browser window constructor?

Seems like it could be a viable workaround. I've disabled our snaps for now but would be nice to have a workaround.

**Comment by burtonator** [comment] 2019-05-11 19:39
sandbox: false doesn't seem to fix thigns. I still get:

"Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
Trace/breakpoint trap (core dumped)
"

**Comment by burtonator** [comment] 2019-05-11 20:08
This might be possible if we pass --no-sandbox to the electron command line but I can't figure out how to set this in electron-builder.

**Comment by thomasnordquist** [comment] 2019-05-12 12:11
To my knowledge, as of now, one can not disable the sandbox/sandbox-helper with an electron builder configuration.

@burtonator see the initial comment for the workaround I chose to use for snaps and AppImage builds, (afterPack hook/electron wrapper script).
I believe there is still a lot to do for different parties (electron, snapcraft) until the sandbox feature will be available for snaps in snapcraft.

An electron-builder build-option to disable/configure the sandbox would be better, but until the situation is resolved I'll use the workaround.

**Comment by burtonator** [comment] 2019-05-14 20:59
I implemented a hack where I renamed the main script to myapp.bin and then added the --no-sandbox argument manually and it worked fine.  Not pretty but at least we have code pushed!

**Comment by vladimiry** [comment] 2019-05-25 09:54
@p3x-robot this is probably OS related as I don't have such issue with Xfce nor with Ubuntu 19.04, you can try the app yourself https://github.com/vladimiry/ElectronMail/releases (AppImage / Snap packages).

**Comment by vladimiry** [comment] 2019-05-25 10:16
@p3x-robot what is that panel at the bottom (how do I enable it)?

**Comment by vladimiry** [comment] 2019-05-25 10:30
> linux mint applet panel 

Which edition of Linux Mint (Cinnamon, Mate, Xfce)?

**Comment by vladimiry** [comment] 2019-05-25 10:33
I don't believe it depends on the no-sandbox option but is related to the OS/panel setup and the way bash/sh script preloader used. Going to reproduce the issue first.

**Comment by vladimiry** [comment] 2019-05-25 10:39
Try running the AppImage without sh/bash preloader but with --no-sandbox  argument, mens don't hack the AppImage imag in any way. I think there will be no duplicated icon issue. So I still don't think there is a bug.

**Comment by vladimiry** [comment] 2019-05-25 10:45
> but they want to not want to play with arguments, just click the menu and it works

Sure they do and it's right to expect the app works flawlessly.

> the issue is the same with Snap ...

Sure it's as the same preloader-like sh/bash script is used.

I think it's just a matter to tweak a little the preloader-like sh/bash script but there is a need to reproduce the issue first. So let's keep trying the different options and get here only having some progress.

**Comment by vladimiry** [comment] 2019-05-25 10:49
> I hope and some time it will be in-built solution from the electron or electron-builder.

First of all the working in major cases solution needs to be worked out which is not the case yet.

**Comment by vladimiry** [comment] 2019-05-25 10:53
Good for you. But just take into the account that it's open-source stuff, so you can't expect someone has to resolve your issues, sometimes you have to contribute too.

**Comment by vladimiry** [comment] 2019-05-25 11:36
@p3x-robot the issue you described remains unreproducible (you can see there is no icons duplication on fresh Linux Mint Cinnamon):

![mint](https://user-images.githubusercontent.com/1560781/58368775-58e77b80-7efa-11e9-9b32-c32ba304a3ba.png)

**Comment by vladimiry** [comment] 2019-05-25 11:37
@p3x-robot the issue you described remains unreproducible (you can see there is no icons duplication on fresh Linux Mint Cinnamon):

![mint](https://user-images.githubusercontent.com/1560781/58368807-98ae6300-7efa-11e9-8b7b-f5090a32c94b.png)

**Comment by vladimiry** [comment] 2019-05-25 12:00
I missed adding it to a panel, could not imagine that windows-like workflow came to Linux Mint. It's, in my opinion, a narrow use case and if you intend to support it you need to learn how the taskbar panel used in Linux Mint detects if the app is already running and then apply the knowledge to tweaking the preload-like bash/sh script.

**Comment by vladimiry** [comment] 2019-05-25 12:25
There is nothing wrong here it's just open-source how it's, so you take it as given if not ready to contribute.

**Comment by vladimiry** [comment] 2019-05-25 18:22
@p3x-robot I don't believe it's supported, see https://github.com/electron-userland/electron-builder/issues/2562

**Comment by vladimiry** [comment] 2019-06-04 13:11
Of course they did as reverting is the easiest thing you can do :smile:

**Comment by vladimiry** [comment] 2019-06-04 13:18
>  the solution you provided is giving 2 icons on the panel...

Including repackaging the Snap package as written here https://github.com/electron/electron/issues/17972#issuecomment-498149481 instead of using loaded sh script (you just do `unsquashfs`, then modify the files and the then pack it back running `snapcraft pack`)?

**Comment by thomasnordquist** [comment] 2019-06-04 13:25
I think the main issue with the double icon is, that the wrapper-script itself will be presented by the task bar.
The wrapper-script then forks another process (the electron app) which also gets the icon.

There may be a different way to fork the process in which there is only one process but the electron process is still attached to the tty.

**Comment by vladimiry** [comment] 2019-06-04 13:28
@p3x-robot I believe it's generally reasonable to expect that bumping a major version may break something as breaking changes is a normal thing to happen for a major version update.  I see no point in continuing the discussion as it goes nowhere. If you need to solve the issue I'd recommend you to tweak the preload script as written before or repackage the Snap build instead (not using the preload script at all).

**Comment by develar** [comment] 2019-06-11 22:20
I am on Snapcraft Summit. Confirmed that `--no-sandbox` is the only viable solution, that in the same time doesn't make your app more insecure (as app is already is running in snapd sandbox). Yes, if you run some fully untrusted content, as Brave browser does, then, you need to ask Canonical to add you to trusted vendor. It is clear that not everyone can be trusted vendor. 

It is not artificial restriction — problem is that snapd cannot grant `allow-sandbox` permission to any app, because in this case app can go out of own sandbox (imposed by snapd) and do some bad things on a user machine.

So, upcoming electron-builder release will fully support Electron 5 by default. Existing version already supports ability to specify `allow-sandbox`.

**Comment by vladimiry** [comment] 2019-06-11 22:27
@develar if I'm not wrong Snap doesn't allow publishing packages that have files with SUID permiission bit set but it looks like the bit is going to be set for all the Linux packages https://github.com/develar/electron-builder/blob/a36123cb9e760b55bf79fe13b93d04306c9cd4b3/packages/app-builder-lib/src/electron/ElectronFramework.ts#L66

**Comment by christianbundy** [comment] 2019-06-11 22:28
Yeah, I'd be curious to hear how this affects the AppImage build target.

**Comment by develar** [comment] 2019-06-11 22:30
@vladimiry This line of code is already removed (in my fork of this repo I do developing and only then push to master) ;)

**Comment by vladimiry** [comment] 2019-06-14 06:38
Not only AppImage, but other Linux packages are also affected, those that need SUID bit to be set.

**Comment by vladimiry** [comment] 2019-06-14 06:45
I just highlighted the issue. Let's not overreact. There are known workarounds that tackle the issue.

**Comment by vladimiry** [comment] 2019-06-14 06:49
@p3x-robot I asked you before, did you try repackaging it? Here is the [prototype](https://github.com/vladimiry/ElectronMail/blob/8bfff6ed61c782486c85122d5160af0fca45a05e/scripts/electron-builder/build-appimage.ts) if needed.

**Comment by vladimiry** [comment] 2019-06-14 07:15
Nope, there are dependencies involved, the binary name is taken from the package.json, etc. But that should not be a problem to convert it to a raw JS code. So it's a code snippet.

**Comment by jwheare** [comment] 2019-07-29 09:36
@develar please can you reopen this issue so it can be resolved for AppImage/deb/etc or would you prefer a new issue is opened? Happy to do so if needed.

**Comment by thomasnordquist** [comment] 2019-07-31 18:08
@p3x-robot for the electron project this is not a bug, but a security feature.

The electron wrapper script is no longer required to ship the application via the snap-store (with a recent `electron-builder` version).

For other Linux distribution channels, one must simply set the `suid` (`chmod u+s`) flag and set the file owner to `root`. See https://github.com/electron/electron/issues/17972#issuecomment-487369441

I never tried it with AppImage builds, I am uncertain if AppImage will work (it would be very scary if no password is required to mount AppImage and AppImage could execute a script as root).

**Comment by vladimiry** [comment] 2019-07-31 18:24
> well snap works

Because snap target got --no-sandbox argument [hardcoded](https://github.com/electron-userland/electron-builder/blob/ff242ab865f65987da4d95183a99c6fbaa7d3b78/packages/app-builder-lib/src/targets/snap.ts#L184) build time. So it doesn't depend on electron version, should work with electron v5 too. I guess one day --no-sandbox hardcoding might happen with appimage packaging process too (right now I have to unpack the prepared package, tweak it and pack back).

**Comment by vladimiry** [comment] 2019-07-31 18:29
Not exactly the same hack, but enhanced. You could try the recent release to check it out https://github.com/vladimiry/ElectronMail/releases

**Comment by vladimiry** [comment] 2019-07-31 18:36
@p3x-robot My opinion is that it's a packagin tools issue, ie should be handed here.

> could you tell me where this code is?

I simply hardcode the --no-sandbox argument in the original AppRun script rather than creating a new loader script, full script is [here](https://github.com/vladimiry/ElectronMail/blob/71c785c162f1b44cd5b3014272b6196c48e5caf1/scripts/electron-builder/build-appimage.ts).

**Comment by vladimiry** [comment] 2019-07-31 18:47
> what you solution does actually

> I simply hardcode the --no-sandbox argument in the original AppRun script rather than creating a new loader script

**Comment by vladimiry** [comment] 2019-07-31 18:51
AppRun script is in the appimage package which needs to be unpacked first ... all that tuff is in the script I referenced.

**Comment by vladimiry** [comment] 2019-07-31 20:53
@p3x-robot you got it right.

**Comment by vladimiry** [comment] 2019-07-31 21:09
@p3x-robot this is why the script triggers package creating [pragmatically](https://github.com/vladimiry/ElectronMail/blob/71c785c162f1b44cd5b3014272b6196c48e5caf1/scripts/electron-builder/build-appimage.ts#L25-L33) rather than via CLI. So the script builds the package first and then does repackaging. I guess you could also run the process using `electron-builder --linux appimage && node ./scripts/your-repackaging-script.js` scripting syntax.

**Comment by vladimiry** [comment] 2019-07-31 21:56
I stopped publishing the packages to GitHub by electron-builder for a list of reasons. There might be some hook/event in between building the package and uploading it, but I'm not aware of it.

**Closed** 2019-10-30 08:39 UTC
Labels: feature, snap

**Comment by christianbundy** [comment] 2019-11-28 17:45
@develar I think this issue should be re-opened. It's great that #4364 resolves this for the `.deb` distribution, but this problem remains unsolved on AppImage (and maybe Snap?).

**Comment by vladimiry** [comment] 2019-11-28 18:10
> (and maybe Snap?).

The Snap case was handled months ago, ref https://github.com/electron-userland/electron-builder/blame/fc311995c196f1063ceb2d0bb0af61beac6038e8/packages/app-builder-lib/src/targets/snap.ts#L188

**Comment by christianbundy** [comment] 2019-11-29 05:21
Thanks. (Snap won't install on my machine, so I haven't been able to test.) It sounds like the problem is now just limited to AppImage installations.
