### ISSUE TITLE
Problem building multiple mac targets: TypeError: pattern.startsWith is not a function

### ISSUE THREAD

**Issue by paulingalls** [electron-userland/electron-builder#3012] opened 2018-06-14 00:33 UTC
Electron Builder:
* **2.15.3**: 

Electron 2.0.2

Target:
* **dmg,mas**: 

I'm running into a problem when I try to build for both dmg,zip and mas.  

Basically
    "target": ["dmg", "zip"] // works
    "target": ["mas"] // works
    "target": ["mas", "dmg", "zip"] // shows the error below

Let me know if you need more info...

```
  TypeError: pattern.startsWith is not a function
    at FileMatcher.normalizePattern (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/fileMatcher.ts:42:17)
    at FileMatcher.patterns.map.it (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/fileMatcher.ts:37:54)
    at Array.map (<anonymous>)
    at new FileMatcher (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/fileMatcher.ts:37:39)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/util/AppFileCopierHelper.ts:123:21
    at Generator.next (<anonymous>)
From previous event:
    at _bluebirdLst.default.mapSeries (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/util/AppFileCopierHelper.ts:120:16)
From previous event:
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/util/AppFileCopierHelper.ts:120:32
    at Generator.next (<anonymous>)
From previous event:
    at copyNodeModules (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/out/util/AppFileCopierHelper.js:319:18)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/platformPackager.ts:261:42
    at Generator.next (<anonymous>)
From previous event:
    at then (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/platformPackager.ts:257:14)
From previous event:
    at _computeFileSets (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/platformPackager.ts:258:10)
    at MacPackager.copyAppFiles (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/platformPackager.ts:280:27)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/platformPackager.ts:214:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at MacPackager.doPack (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/platformPackager.ts:162:151)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/macPackager.ts:107:20
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/macPackager.ts:79:95)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/packager.ts:373:24
    at Generator.next (<anonymous>)
    at xfs.stat (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/packager.ts:341:39)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/packager.ts:317:52
    at Generator.next (<anonymous>)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/graceful-fs/graceful-fs.js:99:16
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/packager.ts:294:133)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/packager.ts:290:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Packager.build (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/packager.ts:248:14)
    at /Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/src/index.ts:51:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder-lib/out/index.js:220:17)
    at build (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder/src/builder.ts:234:10)
    at then (/Users/paulingalls/src/fanzo/desktop/ripl-electron/node_modules/electron-builder/src/cli/cli.ts:46:19)
    at <anonymous>
```

**Comment by popod** [comment] 2018-06-18 15:05
Can you provide the `build` section of your `package.json` please. This works for me with electron-builder 2.15.1.

**Comment by paulingalls** [comment] 2018-06-19 17:53
Here is a cauterized version:

```
"build": {
    "appId": "com.appId",
    "productName": "Name",
    "copyright": "Copyright ©2018 ",
    "files": [
      "app/**/*",
      "node_modules/**/*",
      "package.json"
    ],
    "directories": {
      "buildResources": "resources"
    },
    "mac": {
      "category": "public.app-category.business",
      "type": "distribution",
      "target": ["dmg", "zip"]
    },
    "mas": {
      "provisioningProfile": "resources/prod.provisionprofile",
      "entitlements": "resources/entitlements.mas.plist",
      "entitlementsInherit": "resources/entitlements.mas.inherit.plist",
      "type": "distribution"
    },
    "win": {
      "publisherName": "Ripl",
      "target": [
        {
          "target": "nsis-web",
          "arch": [
            "x64",
            "ia32"
          ]
        },
        {
          "target": "appx",
          "arch": [
            "x64",
            "ia32"
          ]
        }
      ]
    },
    "publish": {
      "provider": "s3",
      "bucket": "bucket",
      "region": "us-east-1",
      "path": "path"
    }
  },
```

**Comment by Aarbel** [comment] 2019-09-17 21:04
Any news about this problem ?

**Comment by MartinBarker** [comment] 2021-03-21 06:36
same issue

**Comment by mmaietta** [comment] 2021-03-21 17:30
@MartinBarker, with latest v22.10.5?

**Comment by mifi** [comment] 2021-03-25 14:14
Downgrade to v22.10.4 worked for me

**Comment by mifi** [comment] 2021-03-26 03:55
I added a `console.log(from, to, patterns)` before this line: https://github.com/electron-userland/electron-builder/blob/c0ae89c004ea546ae6e0a73ec0f04e038169197c/packages/app-builder-lib/src/fileMatcher.ts#L53

It resulted in many lines like this:
```
.../lossless-cut .../lossless-cut/dist/mac/Electron.app/Contents/Resources/app/node_modules [
  '**/*',
  'build/**/*',
  'build/**/*',
  '!node_modules/ffmpeg-ffprobe-static/ffmpeg',
  '!node_modules/ffmpeg-ffprobe-static/ffprobe'
]
```

Then right before `pattern.startsWith is not a function` came this line:

```
.../lossless-cut/node_modules/agent-base .../lossless-cut/dist/mas/Electron.app/Contents/Resources/app/node_modules/agent-base/node_modules [
  '**/*',
  'build/**/*',
  'build/**/*',
  '!node_modules/ffmpeg-ffprobe-static/ffmpeg',
  '!node_modules/ffmpeg-ffprobe-static/ffprobe',
  [
    '**/*',
    'build/**/*',
    'build/**/*',
    '!node_modules/ffmpeg-ffprobe-static/ffmpeg',
    '!node_modules/ffmpeg-ffprobe-static/ffprobe'
  ]
]
```

This leads me to believe there is a bug somewhere lower in the call stack where instead of combining two arrays, some code is instead adding the second array as an item in the base array. But only when multiple targets are running...

**Comment by mifi** [comment] 2021-03-26 03:58
Seems like this is an old bug. Happened it 2019 also: https://github.com/electron-userland/electron-builder/issues/4204#issuecomment-527185417

Maybe it was just hidden all along and just now started to crash the build in the latest version

**Comment by gaodeng** [comment] 2021-03-26 05:30
I've run into this problem before. I can't quite remember the root cause of the problem right now. But I'll submit a PR later if needed

**Comment by gaodeng** [comment] 2021-03-26 16:05
PR https://github.com/electron-userland/electron-builder/pull/5739 should fix this bug for good

**Comment by buu700** [comment] 2021-05-09 14:36
This is the error I'm getting on macOS (Big Sur 11.3.1, arm64) with Node 14.16.1:

```
TypeError: pattern.startsWith is not a function
    at FileMatcher.normalizePattern (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/fileMatcher.ts:59:17)
    at /Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/fileMatcher.ts:53:54
    at Array.map (<anonymous>)
    at new FileMatcher (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/fileMatcher.ts:53:39)
    at computeNodeModuleFileSets (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/util/appFileCopier.ts:197:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/platformPackager.ts:306:36
    at async Promise.all (index 0)
    at AsyncTaskManager.awaitTasks (/Users/buu700/cyph/prod/app/cordova-build/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
    at MacPackager.doPack (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/platformPackager.ts:219:5)
    at MacPackager.doPack (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/macPackager.ts:103:9)
    at MacPackager.pack (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/macPackager.ts:158:9)
    at Packager.doBuild (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/packager.ts:434:9)
    at executeFinally (/Users/buu700/cyph/prod/app/cordova-build/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/packager.ts:369:31)
    at Packager.build (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/packager.ts:333:12)
    at executeFinally (/Users/buu700/cyph/prod/app/cordova-build/node_modules/builder-util/src/promise.ts:12:14)
```

It looks like the immediate issue is that an empty array is being passed in to `normalizePattern` rather than a string.

**Comment by mmaietta** [comment] 2021-05-09 17:08
Thanks for verifying that @buu700.
I've approved and merged the PR, it'll make our next release.

**Closed** 2021-05-09 17:08 UTC

**Comment by gurpreetsingh41333** [comment] 2021-05-20 21:47
> patch-package

can you please add the steps on how you resolved this issue?

**Comment by gurpreetsingh41333** [comment] 2021-05-20 21:48
> This is the error I'm getting on macOS (Big Sur 11.3.1, arm64) with Node 14.16.1:
> 
> ```
> TypeError: pattern.startsWith is not a function
>     at FileMatcher.normalizePattern (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/fileMatcher.ts:59:17)
>     at /Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/fileMatcher.ts:53:54
>     at Array.map (<anonymous>)
>     at new FileMatcher (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/fileMatcher.ts:53:39)
>     at computeNodeModuleFileSets (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/util/appFileCopier.ts:197:21)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at /Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/platformPackager.ts:306:36
>     at async Promise.all (index 0)
>     at AsyncTaskManager.awaitTasks (/Users/buu700/cyph/prod/app/cordova-build/node_modules/builder-util/src/asyncTaskManager.ts:65:25)
>     at MacPackager.doPack (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/platformPackager.ts:219:5)
>     at MacPackager.doPack (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/macPackager.ts:103:9)
>     at MacPackager.pack (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/macPackager.ts:158:9)
>     at Packager.doBuild (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/packager.ts:434:9)
>     at executeFinally (/Users/buu700/cyph/prod/app/cordova-build/node_modules/builder-util/src/promise.ts:12:14)
>     at Packager._build (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/packager.ts:369:31)
>     at Packager.build (/Users/buu700/cyph/prod/app/cordova-build/node_modules/app-builder-lib/src/packager.ts:333:12)
>     at executeFinally (/Users/buu700/cyph/prod/app/cordova-build/node_modules/builder-util/src/promise.ts:12:14)
> ```
> 
> It looks like the immediate issue is that an empty array is being passed in to `normalizePattern` rather than a string.
> 
> Edit: Applying #5739 as a patch with `patch-package` worked for me. Thanks @gaodeng!

can you please add the steps on how you resolved this issue?

**Comment by buu700** [comment] 2021-05-21 04:19
Sure, just use [`patch-package`](https://www.npmjs.com/package/patch-package) with the attached patch.

[builder-util+22.10.5.patch](https://github.com/electron-userland/electron-builder/files/6520005/builder-util%2B22.10.5.patch.txt)
