### ISSUE TITLE
Electron 7.1.3 broke github releases.  Possible to change latest.yml manually

### ISSUE THREAD

**Issue by burtonator** [electron-userland/electron-builder#4543] opened 2019-12-18 16:39 UTC
* **Version**: 

    "electron-builder": "~21.2.0",

    "electron-updater": "~4.2.0",

* **Target**: 
macos, windows hosted on github.

Releases on Electron > 7.1.2 no longer work and give this error:

```
Error: Redirect was cancelled at SimpleURLLoaderWrapper. (electron/js2c/browser_init.js:2561:23) at SimpleURLLoaderWrapper.emit (events.js:203:13)
```

I suspect redirects are broken as it does fetch ONE URL but not the others.

I'd like to change the latest.yml file so it can fetch exact URLs but the 'url' is custom built by concat of the base + URL plus the download URL.

So I get this a URL like:

a+b 

rather than just 

b (it's already absolute)

that alone might be a bug and warrant fixing but I think if I can get latest.yml to specify a full URL I'll be good.

Is there documentation to the latest.yml format?

```
Downloading update from https://firebasestorage.googleapis.com/v0/b/polar-32b0f.appspot.com/o/download%2FPolar-Bookshelf-1.80.3-mac.zip?alt=media&token=5329f924-c99f-480e-85b2-41d832636736, https://firebasestorage.googleapis.com/v0/b/polar-32b0f.appspot.com/o/download%2FPolar-Bookshelf-1.80.3.dmg?alt=media&token=4ae0573f-e3d3-488b-87f8-587b53858ba9
Downloading update from https://firebasestorage.googleapis.com/v0/b/polar-32b0f.appspot.com/o/download%2FPolar-Bookshelf-1.80.3-mac.zip?alt=media&token=5329f924-c99f-480e-85b2-41d832636736, https://firebasestorage.googleapis.com/v0/b/polar-32b0f.appspot.com/o/download%2FPolar-Bookshelf-1.80.3.dmg?alt=media&token=4ae0573f-e3d3-488b-87f8-587b53858ba9
updater cache dir: /Users/burton/Library/Application Support/Caches/polar-bookshelf-updater
No cached update info available
Error: Error: Cannot download "https://github.com/burtonator/polar-bookshelf/releases/download/v1.80.3/https://firebasestorage.googleapis.com/v0/b/polar-32b0f.appspot.com/o/download%2FPolar-Bookshelf-1.80.3-mac.zip?alt=media&token=5329f924-c99f-480e-85b2-41d832636736", status 404: Not Found
    at ClientRequest.<anonymous> (/Applications/Polar Bookshelf.app/Contents/Resources/app.asar/node_modules/builder-util-runtime/out/httpExecutor.js:278:26)
    at ClientRequest.emit (events.js:203:13)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:2527:12)
    at SimpleURLLoaderWrapper.emit (events.js:203:13)
(electron) 'getName function' is deprecated and will be removed. Please use 'name property' instead.
[error] [1.70.4] Error handling updates: Error: Cannot download "https://github.com/burtonator/polar-bookshelf/releases/download/v1.80.3/https://firebasestorage.googleapis.com/v0/b/polar-32b0f.appspot.com/o/download%2FPolar-Bookshelf-1.80.3-mac.zip?alt=media&token=5329f924-c99f-480e-85b2-41d832636736", status 404: Not Found
```

**Comment by burtonator** [comment] 2019-12-19 20:54
I think the bug is here:

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-updater/src/electronHttpExecutor.ts#L27

We have a thread on this going here:

https://github.com/electron/electron/issues/21566

I suspect maybe Electron >7.1.2 started properly handling redirects? 

Is there a reason electron-updater isn't following redirect URLs? This will break a LOT of hosting platforms.

**Comment by marcoancona** [comment] 2019-12-20 11:36
Also connected to #4505 (which is not solved)

**Comment by s00d** [comment] 2020-01-13 15:08
electron 7.1.8 worked!

**Comment by lutzroeder** [comment] 2020-02-01 01:04
Duplicate of #4505

**Closed** 2020-04-08 03:43 UTC
Labels: backlog
