### ISSUE TITLE
.exe - installer doesn't copy directories with extra resources during installation

### ISSUE THREAD

**Issue by d9k** [electron-userland/electron-builder#252] opened 2016-03-17 17:56 UTC
Hi! Thanks for providing extraResources enhancement (https://github.com/loopline-systems/electron-builder/issues/230)
But I have an issue: installer doesn't copy directories with extra resources to target path during installation.

package.json:
```
  "build": {
    "dir": "app",
	"win": {
		"extraResources": [
			"./*.dll",
			"libs"
         ]
//.....
```

After running builder there is "libs" folder at the non-archived distribution at `dist\MyApp-win32-x64`
but when I execute installer package located at `dist\win-x64\MyApp-%VERSION%.exe` it doesn't copy `lib` folder to the `%AppData%\Local\MyApp\app-%VERSION%\`.

**Comment by develar** [comment] 2016-03-18 12:50
Please ask about it in the [windows-installer](https://github.com/electronjs/windows-installer/issues). I have no clue why.

**Comment by develar** [comment] 2016-03-23 10:34
Duplicate of #230

**Closed by develar** 2016-03-23 10:34 UTC
Labels: windows
