### ISSUE TITLE
Build snap packages for Linux

### ISSUE THREAD

**Issue by nmabhinandan** [electron-userland/electron-builder#509] opened 2016-06-16 06:36 UTC
Snaps are universal Linux packages which work on any distribution or device. Snaps are faster to install, easier to create, safer to run, and they update automatically and transactionally so your app is always fresh and never broken.

Snap packages are supported by all major Linux distributions and integrate well with desktop environments. 
https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/

Although snap packages are relatively easy to build, there is an excellent tool to package and publish snaps called snapcraft.
http://snapcraft.io

**Comment by develar** [comment] 2016-06-16 08:05
Are you affiliated with Snap or just user?

**Comment by nmabhinandan** [comment] 2016-06-16 09:12
I'm a "just user".  😒

**Comment by kunkinkan** [comment] 2016-06-16 11:44
Here's a tutorial on how to snap electron-based apps, may be helpful to build a script; 

http://www.linuxuk.org/post/20160518_snapping_electron_based_applications_simplenote/

**Comment by develar** [comment] 2016-06-21 05:56
Moved to backlog to keep issue list clear.

**Comment by develar** [comment] 2016-08-16 12:55
@nmabhinandan What do you currently — AppImage or deb? Are you still "dream" about snap?

**Comment by develar** [comment] 2016-08-16 12:56
I decided to support Snap. Will be fixed soon.

**Comment by probonopd** [comment] 2016-09-13 20:56
What advantage do you see with snap over AppImage?

**Comment by develar** [comment] 2016-09-14 05:27
if question to me:
* snap store ubuntu
* auto updates without any effort (including update server (I know, that bintray can be used))
* relatively easy setup (for me, "make executable" before laugh, is not good) — no need to know what AppImage file is.

**Comment by develar** [comment] 2016-09-14 05:37
BTW, we use AppImage to distribute [JetBrains Toolbox app](https://confluence.jetbrains.com/display/ToolboxApp/JetBrains+Toolbox+App+-+Early+Access+Program) for Linux, but image packed into `tar.gz` archive to avoid "make executable before launch" (I know, that you don't like it :)).

**Comment by probonopd** [comment] 2016-09-14 07:03
Thanks @develar, let me know if you have ideas how to improve in these areas. Yes, I met @kropp recently :-)

**Comment by peteruithoven** [comment] 2016-11-13 15:58
@develar I've asked on the snapcraft mailinglist about building snaps on other platforms than Linux. 

Not sure if it's interesting, but this is an article on someone creating a snap for an electron app: http://www.linuxuk.org/post/20160518_snapping_electron_based_applications_simplenote/

**Comment by markshuttle** [comment] 2016-11-14 13:12
We'd be very happy to help making it really easy for Electron apps to be snapped, on any Linux platform (and possibly under the Windows Subsystem for Linux in future versions of Windows). The thread on the snapcraft list is a good start, will follow up there.

**Comment by peteruithoven** [comment] 2016-11-14 13:20
Not sure how to link properly to a thread in a mailinglist archive, but this is the start:
https://lists.ubuntu.com/archives/snapcraft/2016-November/001614.html

**Comment by develar** [comment] 2016-11-14 13:28
One working day is required to implement snaps support in the electron-builder. We already provides Docker image (https://github.com/electron-userland/electron-builder/wiki/Docker), so, docker aspect (multi-platform build) is not a problem or time-consuming task. You can ask me to add snaps to electron-builder Docker images.

Currently, this task is postponed (auto-updates is my current goal).

You can expect snaps support by end of this year. To speed up, you can or make donation, or make PR.

Also, don't forget to answer here — why AppImage is not suitable for you.

**Comment by peteruithoven** [comment] 2016-11-14 14:35
I don't like AppImages because it requires a manual action to update, or a per application solution. With applications installed as snap their all updated with the general updates. This is because snaps come from a repository / channel and AppImages don't.

**Comment by markshuttle** [comment] 2016-11-14 15:13
Yes, the auto-update of snaps is the heart of the CI / daily build magic
too :)

Building the snap in a docker image should work fine - just use Ubuntu
16.04 and a current snapcraft. I don't think you would be able to test
it inside a docker process, but you could build it and push it to the
cloud and then devices will auto-update. If it's one days work let me
make that donation :)

Do you have a standard recommended CI, like Travis? Because the real win
is integrating snap builds with the auto-update mechanism for developers
to run trunk of the app.

Mark

**Comment by develar** [comment] 2016-11-14 15:18
> Do you have a standard recommended CI, like Travis?

Travis and Circle CI is supported explicitly. I recommend to use Travis to build macOS and Circle CI to build Linux. electron-builder uses Docker on Circle CI to test (https://github.com/electron-userland/electron-builder/blob/master/circle.yml#L17).

**Comment by markshuttle** [comment] 2016-11-14 15:28
OK, if Circle CI has good support for secure secrets on their side, then
we can probably also hook up CI builds to the store, so developers can
run them if they want, automagically.

Mark

**Comment by probonopd** [comment] 2016-11-14 22:16
> I don't like AppImages because it requires a manual action to update, or a per application solution. With applications installed as snap their all updated with the general updates. This is because snaps come from a repository / channel and AppImages don't. 

Don't think it can be much easier than this:

![](https://cloud.githubusercontent.com/assets/2480569/19410850/0390fe9c-92f6-11e6-9882-3ca6d360a190.jpg)

This empowers the end user to decide what to update, and when.

**Comment by 3v1n0** [comment] 2016-11-16 12:54
@peteruithoven that's a step-by-step guide that refers to some old infos though...

Now electron apps can run confined and with proper desktop integration.
See this example for more infos: https://github.com/3v1n0/electron-quick-start-snap

**Comment by develar** [comment] 2016-11-16 12:57
@3v1n0 Yes. Currently you can set target to `dir` to get only unpacked linux directory. And then pack it using another tools.

**Comment by develar** [comment] 2016-11-17 18:41
Work started. Please do not send PR for now.

**Comment by develar** [comment] 2016-11-18 09:22
Initially supported:

* Doesn't work on macOS yet. But electron-builder automatically uses `docker`, so, you will not notice that snap requires Linux.
* No desktop integration. To investigate. i.e. your app is not added to menu.
* electron-download fixed — you can run build in the Linux VM in the macOS directory (Parallels Desktop). So, you can open terminal in the Linux VM and build your app. Until macOS Docker is not fully supported. 

Issue is not closed because it is very raw. Snap is not so straightforward and well documented as AppImage.

Not yet pushed.

**Comment by sergiusens** [comment] 2016-11-18 11:56
@develar hello there

To get desktop files you currently have to do something similar to https://github.com/snapcore/snapcraft/tree/master/demos/qt5-text-editor

In the upcoming snapcraft you will also be able to do something like this:

```yaml
apps:
    my-app:
        command: my-command
        desktop: <path-in-snap-to-desktop>
```

I am guessing that since you generate everything on the fly you can go with the former just fine.

**Comment by sergiusens** [comment] 2016-11-18 11:57
@develar your feedback is welcome so any specifics to make your life easier, just say so!

**Comment by develar** [comment] 2016-11-18 12:12
Please try http://stackoverflow.com/a/38989441/1910191

**Comment by sergiusens** [comment] 2016-11-18 12:15
@develar is this related to snaps at all? Sorry I am missing context and should of mentioned "life easier related to creating a snap"

**Comment by develar** [comment] 2016-11-18 12:19
@sergiusens I am sorry, comment related to another issue. Thanks for your comments, I will try.

**Comment by develar** [comment] 2016-11-19 07:48
@sergiusens `desktop-glib-only` is currently used. I have read https://developer.ubuntu.com/en/blog/2016/07/06/announcing-new-snap-desktop-launchers/ 

No luck — no app in the menu (Ubuntu/Xubuntu). Should I create `.desktop` file as part of the app?

Generated `snapcraft.yaml` https://gist.github.com/develar/88bc3e8e225e30a43a654e3653b0d9ec
Built on Xubuntu, because on Ubuntu doesn't work (snapcraft version `2.22.1` on both VM) (I will post internal error trace later).

When app is integrated — on `sudo snap install --force-dangerous` or on first launch? Or does it work only if installed from ubuntu store? Is Xubuntu supported or only Ubunuu?

**Comment by develar** [comment] 2016-11-19 11:37
@sergiusens Thanks a lot for #919! I will try. https://github.com/snapcore/snapcraft/blob/master/docs/metadata.md is much more better then http://snapcraft.io/docs/ (e.g., no more question about package icon — "relative to the icon inside the snap").

**Comment by develar** [comment] 2016-11-19 12:36
Ok, I have no idea how to build snap with a desktop integration and package icon. Also, it seems unreleased snapcraft is required to add icon to package (https://github.com/snapcore/snapcraft/commit/4a4435cbe9cee4ac0d2225b0d37d897af1c927c1). As @sergiusens is here, I don't want to waste my time anymore and will wait some advice how to make it working.

**Comment by peteruithoven** [comment] 2016-11-23 12:36
@develar I would post a question on the snapcraft mailing list, it's quite active. 
I could also also try to ask it for you, if you prefer that.

**Comment by sergiusens** [comment] 2016-11-23 12:56
@peteruithoven no need, I will bring in the necessary folk into play; I plan on looking at this today as I carved out some time for this.

**Comment by sergiusens** [comment] 2016-11-23 12:59
@develar the deprecated message is harmless and should just work

**Comment by sergiusens** [comment] 2016-11-23 13:03
@develar how can I setup an environment to play around with this?

**Comment by develar** [comment] 2016-11-24 16:25
@sergiusens You can just provide me minimum snaps app that has desktop integration — i.e. menu entries for app is created on install. And shed light on "When app is integrated — on sudo snap install --force-dangerous or on first launch? Or does it work only if installed from ubuntu store".

If you say — this example definitely has package icon / entry in the menu for app / icon — I will continue to digging what's wrong on my side. Is Xubuntu supported or I have to use only Ubuntu?

But if you want to help me and try electron-builder — 
* install git lfs — https://git-lfs.github.com
* `git lfs clone https://github.com/electron-userland/electron-builder.git`
* `cd electron-builder` and `npm install`
* uncomment line `test.ifNotCi("snap" ...` in the `test/src/linux/linuxPackagerTest.ts`.
* `npm run compile`

and then you can run test:

`TEST_APP_TMP_DIR=/tmp/electron-builder-test ./node_modules/.bin/jest -t "snap" linuxPackagerTest` 

`npm run compile` to recompile sources.

Currently I am on vacation, I haven't attempted again to investigate or try snaps examples to see — does it works or not. Thanks for you help.

**Comment by develar** [comment] 2016-12-02 19:35
Sorry. I am still not ready to waste my time and investigate why snaps doesn't work. But in any case I hope to fix it this year, as promised.

**Comment by develar** [comment] 2016-12-24 10:32
Another "nice" feature of snapcraft — if it is spawned, it can request `sudo` password and build process hangs...

**Comment by develar** [comment] 2016-12-24 10:55
Issue is closed as fixed.

All stopper issues were fixed by new snapcraft release (and one issue on electron-builder side). Only `2.24+` snapcraft version must be used. electron-builder doesn't check it. Please always ensure that you use latest version.

Known issues:

1. macOS not supported. You have to use our docker image explicitly for now.
2. Right after launch app icon replaced to unknown. Yeah... to investigate why correctly looking snap doesn't work. Maybe someone will help to fix it.

**Closed by develar** 2016-12-24 10:55 UTC
Labels: feature, linux

**Comment by develar** [comment] 2016-12-24 16:01
snap package size can be reduced from 68MB to 46MB using [ubuntu-app-platform](https://insights.ubuntu.com/2016/11/17/how-to-create-snap-packages-on-qt-applications/) but it is buggy and not reliable. (https://bugs.launchpad.net/snappy/+bug/1652369)

> cannot mount /snap/ubuntu-app-platform/19 at /snap/snap-electron-builder-test/x4/ubuntu-app-platform with options bind,ro. errmsg: No such file or directory

**Comment by patricksebastien** [comment] 2016-12-24 16:29
Will try electron-builder for snapping my app very soon, thank you very much for this!

Questions:
1. Snap package can be uploaded to the Ubuntu Store?
2. Platform supported is only desktop or it will run on mobile / tablet?

Thanks

**Comment by develar** [comment] 2016-12-24 16:35
> Snap package can be uploaded to the Ubuntu Store?

Yes. And you can configure [some options](https://github.com/electron-userland/electron-builder/wiki/Options#SnapOptions). Defaults options are equals to official snapcraft options and, so, snap can be published to Ubuntu Store as is.

> Platform supported is only desktop or it will run on mobile / tablet?

Well... I don't know ;) At least, not restricted.

**Comment by develar** [comment] 2016-12-26 17:52
You can build snap on macOS (just install [docker for mac](https://docs.docker.com/engine/installation/mac/#/docker-for-mac)). **Do not use Docker Toolbox**. Only Docker for Mac is supported and will work. (Well, there is not yet reported snap bug that leads to inability to use mapped volumes, but using Docker for Mac in any case is very important).

**Comment by develar** [comment] 2016-12-27 07:55
> Right after launch app icon replaced to unknown

Issue on electron-builder side identified and fix will be published soon.

**Comment by develar** [comment] 2016-12-27 13:39
Snap desktop integration doesn't work correctly for Elementary OS (https://github.com/ubuntu/snapcraft-desktop-helpers/issues/32).

AppImage correctly integrated into  Elementary OS, but app doesn't start (electron-builder issue, will be fixed soon).

**Comment by patricksebastien** [comment] 2017-02-08 18:46
I have snap my first electron application, thank you very much for your work on this! I have a problem with the sound, the issue is [here](https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1598309/). Someone told me to add pulseaudio as a [stage-packages](https://gist.github.com/Ads20000/8bab9cea68dd75e2d2c31334a09d292f).

How to modify/customize the snap.yaml generated by electron-builder?
Thanks

**Comment by develar** [comment] 2017-02-08 19:04
@patricksebastien https://github.com/electron-userland/electron-builder/wiki/Options#SnapOptions-stagePackages Actual defaults: https://github.com/electron-userland/electron-builder/blob/ade922c4d72fab3af87bee40d14e8d506b933800/packages/electron-builder/src/targets/snap.ts#L87

**Comment by patricksebastien** [comment] 2017-02-09 15:03
@develar Thank you, sounds is working! Should it be the actual defaults?
`["libnotify4", "libappindicator1", "libxtst6", "libnss3", "libxss1", "fontconfig-config", "gconf2", "libasound2", "pulseaudio"]`

**Comment by develar** [comment] 2017-02-09 15:23
@patricksebastien 80.6 vs 85.1 ... well, I guess 5 MB is ok ((sound doesn't work -> googling -> find option in the electron-builder -> enable it) * user count). Will be added to default packages.

**Comment by patricksebastien** [comment] 2017-02-09 15:53
Sorry, I need to use the webcam. How to add plugs: in snap.yaml? Didn't find this option in the documentation.

**Comment by develar** [comment] 2017-02-09 15:58
@patricksebastien Please file issue. Will be fixed soon if filed.
