### ISSUE TITLE
Error while creating delta nupkg for Windows: System.DllNotFoundException: msdelta.dl

### ISSUE THREAD

**Issue by atietje** [electron-userland/electron-builder#294] opened 2016-04-05 11:43 UTC
I added to my development package.json:

    "build": {
        "win": {
          "remoteReleases": "https://github.com/my-username/my-repo"
        }
    }

When I run `./node_modules/.bin/build --appDir build/ --dist --platform win32 --arch x64` I get the error:

    Packaging app for platform win32 x64 using electron v0.37.4
    System.DllNotFoundException: msdelta.dll at (wrapper managed-to-native)
        DeltaCompressionDotNet.MsDelta.NativeMethods:CreateDelta (DeltaCompressionDotNet.MsDelta.FileTypeSet,long,long,string,string,string,string,DeltaCompressionDotNet.MsDelta.DeltaInput,intptr,DeltaCompressionDotNet.MsDelta.HashAlgId,string)

I'm building for Windows on OS X El Capitan.

In addition to that:

* Can I use a private Github repo for this? Where do I have to put credentials?
* Can I use a [Nuts](https://nuts.gitbook.com/) URL for remoteReleases?

**Comment by develar** [comment] 2016-04-05 12:01
It is reported as https://github.com/electron/windows-installer/issues/61 Unlikely that it will be addressed there soon, but, as you use electron-builder, it will be fixed by me. I will check.

> Can I use a private Github repo for this? Where do I have to put credentials?

`When pointing to GitHub, use the URL to the repository root page, else point to an existing remote Releases folder`

Set `remoteToken` (see https://github.com/electron/windows-installer). In the development package.json: `build: {win: {remoteToken: yourToken }} `.

> Can I use a Nuts URL for remoteReleases?

Yes. See https://github.com/Squirrel/Squirrel.Windows/blob/9de260cb6b614234511d57723738f1be2ed25476/src/SyncReleases/Program.cs#L52

**Comment by atietje** [comment] 2016-04-05 15:33
Adding `remoteToken` for Github did the job, thanks!

For Nuts it worked when I use

    "remoteReleases": "https://MY-NUTS.herokuapp.com/update/win32/0.3.5"

Seems I have to bump the version in this URL on every release, because there seems to be no `latest`

`System.DllNotFoundException: msdelta.dll`is still there. Thanks for investigating!

**Comment by develar** [comment] 2016-04-05 15:35
> Seems I have to bump the version in this URL on every release, because there seems to be no latest

Please ask about in the Nuts issue tracker (mention this issue, I am also interested).

**Comment by develar** [comment] 2016-04-05 18:04
Reproduced. In any case you can build production-ready win app only on Windows (because code signing is not supported https://github.com/electron-userland/electron-builder/blob/master/docs/multi-platform-build.md#multi-platform-build) but will be fixed anyway.

**Closed** 2016-04-14 11:26 UTC
