### ISSUE TITLE
latest-mac.yml doesn't take into account artifactName configuration for .zip build

### ISSUE THREAD

**Issue by IGassmann** [electron-userland/electron-builder#2706] opened 2018-03-16 17:32 UTC
The generated `latest-mac.yml` file doesn't use the configured name format for the macOS zip build.

**Comment by develar** [comment] 2018-03-16 17:37
As far I remember, it was checked and cannot reproduce. I will check again (probably there are also tests for it).

**Comment by IGassmann** [comment] 2018-03-16 18:14
Just happened with version `20.5.1`. `artifactName` was set to `${productName}_${version}.${ext}`. Mac target was not defined.

**Comment by develar** [comment] 2018-03-18 16:55
I cannot reproduce.


latest-mac.yml:
```
version: 1.1.0
files:
  - url: Test App ßW_1.1.0_mac.zip
    sha512: zwhWkajsM/GBjbsM8GBEeTEFgjvrbi844IvubH46FZ+mAA1Dppa8Kd4+OumtHNmi7b8DAi9vUvgk0SaxlPWYpw==
path: Test App ßW_1.1.0_mac.zip
sha512: zwhWkajsM/GBjbsM8GBEeTEFgjvrbi844IvubH46FZ+mAA1Dppa8Kd4+OumtHNmi7b8DAi9vUvgk0SaxlPWYpw==
releaseDate: '2018-03-18T16:53:49.990Z'
```

```
artifactName: "${productName}_${version}_${os}.${ext}",
```

```
Test App ßW_1.1.0_mac.zip
```

**Comment by IGassmann** [comment] 2018-03-19 16:01
Wasn't able to reproduce it either with a minimum configuration.

**Comment by IGassmann** [comment] 2018-03-23 17:45
So I was finally able to reproduce the error in a minimal configuration. It seems to happen only with a configured S3 publisher. If you check out the branch [`electron-builder` on the repository IGassmann/electron-builder](https://github.com/IGassmann/electron-playground/tree/electron-builder) you can test it on a macOS environment by running `yarn build`. You'll notice that the produced `.zip` file don't have the suffix `-mac`, but on the file `latest-mac.yml` it has it.

**Comment by IGassmann** [comment] 2018-03-23 17:50
Here's the interesting line of a Travis job that ran the code: https://travis-ci.org/IGassmann/electron-playground/jobs/357485512 .  As you can see, `electron-builder` produces two different file names for GitHub and S3.

**Comment by IGassmann** [comment] 2018-04-24 16:44
@seanyesmunt @nikooo777

**Comment by tzarebczan** [comment] 2018-06-16 00:53
@develar this is still an issue for us. We need to keep renaming the url in both the yml and json file.

**Comment by tzarebczan** [comment] 2018-06-28 04:19
@develar pulled this our of Igors logs:
```
 uploading       file=ElectronPlayground_1.0.0.zip provider=S3
  â€¢ uploading       file=electron-playground-1.0.0-mac.zip provider=GitHub
2018-03-23T17:05:44.146Z electron-builder Request: {
  "hostname": "uploads.github.com",
  "path": "/repos/IGassmann/electron-playground/releases/10154073/assets?name=electron-playground-1.0.0-mac.zip",
```

Narrowed it down to: https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/targets/ArchiveTarget.ts#L46

Specifically, it's an issue with the URL on both the yml and json file. 
```

{
  "version": "0.22.0-rc.15",
  "releaseDate": "2018-06-25T19:58:48.236Z",
  "url": "https://s3.amazonaws.com/build.lbry.io/app/release/LBRY-0.22.0-rc.15-mac.zip"
} 
```
- should be: LBRY_0.22.0-rc.15.zip (underscore and remove mac)


```
version: 0.22.0-rc.11
files:
  - url: LBRY-0.22.0-rc.11-mac.zip
 
```
- should be: LBRY_0.22.0-rc.15.zip (underscore and remove mac)

**Comment by tzarebczan** [comment] 2018-07-18 14:58
@develar tried on electron updater 2.23.3 and builder 20.22.0 and it's half fixed. The yml file is correct, but the json file still shows the incorrect artifact name, see below. I just found that the json file is no longer used...any idea why it's still created? 

json:
```
{
  "version": "0.1.0-rc.2",
  "releaseDate": "2018-07-17T21:05:50.532Z",
  "url": "https://s3.amazonaws.com/build.lbry.io/app/release/LBRY-0.1.0-rc.2-mac.zip"
}
```

yml:
```
version: 0.1.0-rc.2
files:
  - url: LBRY_0.1.0-rc.2.zip
    sha512: G8jrOlT/ouWzK9/L48/T45GAm0zbj6hW6g8f67uQAZkVn4X16BfWx/7QDF4hdJuKv/l4N+uT+2akjnyjRIbR7w==
  - &ref_0
    url: LBRY_0.1.0-rc.2.dmg
    sha512: c2aRD+aQ37xJu5h28EXQBBiI/eEbm5kLV9O3IFx2qHqYM49gUcaD6emMgciwYYMgDPnwLgzix757KBwfxxaZXA==
    size: 86916200
  - *ref_0
path: LBRY_0.1.0-rc.2.zip
sha512: G8jrOlT/ouWzK9/L48/T45GAm0zbj6hW6g8f67uQAZkVn4X16BfWx/7QDF4hdJuKv/l4N+uT+2akjnyjRIbR7w==
releaseDate: '2018-07-17T21:05:58.590Z'
```

**Comment by develar** [comment] 2018-07-18 15:15
> .any idea why it's still created?

To be compatible with electron-updater 1.x

See `electronUpdaterCompatibility` (https://www.electron.build/configuration/mac/)

**Comment by tzarebczan** [comment] 2018-07-18 15:20
Thanks! I think you can now close this issue.

**Comment by mlynch** [comment] 2018-10-25 16:33
Can confirm this is still happening in 20.28.4, when using a github repo.

<img width="951" alt="screen shot 2018-10-25 at 11 31 11 am" src="https://user-images.githubusercontent.com/11214/47515899-a78c4480-d849-11e8-834d-9f26be8fbbb3.png">

Here's my build config, notice how the artifact name has been specified a few times, yet for some reason the build/package script is still using the `name` field in `package.json`

```json
  "build": {
    "appId": "com.ionicframework.studio",
    "productName": "Ionic Studio",
    "artifactName": "Ionic Studio ${version}.${ext}",
    "directories": {
      "buildResources": "resources"
    },
    "files": [
      "!src",
      "!dist",
      "!embedded.provisionprofile",
      "!sentry-symbols.js",
      "!resources",
      "!stencil.config.js",
      "!test"
    ],
    "extraFiles": [
      "node_modules/**/*"
    ],
    "win": {
      "artifactName": "Ionic Studio ${version}.${ext}",
      "target": [
        "nsis",
        "zip"
      ]
    },
    "mac": {
      "artifactName": "Ionic Studio ${version}.${ext}",
      "category": "public.app-category.productivity",
      "entitlements": "resources/entitlements.mac.plist",
      "icon": "resources/icon.png",
      "target": [
        "dmg",
        "pkg",
        "zip"
      ],
      "provisioningProfile": "embedded.provisionprofile"
    },
    "publish": {
      "provider": "github",
      "repo": "...",
      "owner": "..."
    }
  },
```

**Closed** 2019-07-09 01:29 UTC
Labels: backlog, deployment, electron-updater
