### ISSUE TITLE
Position hidden folders in DMG correctly

### ISSUE THREAD

**Issue by jakubzitny** [electron-userland/electron-builder#1160] opened 2017-01-23 12:41 UTC
* **Version**: latest
* **Target**: mac, linux, win

This is quite low priority request, but anyway, some users have hidden folders turned on by default on a mac. In this case, several hidden files that are present in `electron-builder` generated DMG can interfere with the main files and background that are positioned in config.

The hidden files on a mac can be turned on with:
```
defaults write com.apple.finder AppleShowAllFiles YES
killall Finder
```

By default, `electron-builder` adds:
- `.fseventsd/`
- `.background/`
- `.VolumeIcon.icns`
Icons in general can be positioned in [DMG.contents](https://github.com/electron-userland/electron-builder/wiki/Options#DmgOptions) config. It can look in YAML like this:
```
...
dmg:
  background: "..."
  icon: "...."
  iconSize: 138
  contents:
    - x: 410
      y: 255
      type: link
      path: "/Applications"
    - x: 186
      y: 255
      type: file
    - x: 186
      y: 765
      type: position
      path: ".VolumeIcon.icns"
    - x: 1000
      y: 3000
      type: position
      path: ".background"
...
```

Now, this does work for all visible (non-hidden) files and folders correctly. The positioning also works for the `.VolumeIcon.icns` file. It does not work for the hidden folders though.

We used to have this solved in appdmg by having the same `contents` in the appdmg config with all hidden files and folders outside of the viewing area. It worked, but it does not work in `electron-builder`. I think it might have something to do with `electron-buider` [manipulating](https://github.com/electron-userland/electron-builder/blob/88682e826c36d5032df6fe42c45aa60f9739da35/packages/electron-builder/src/targets/dmg.ts) with `.background` manually after the `contents` config is loaded. Also I have no idea why and how the `.fseventsd` is geting there.

I think you might have an idea why this is happening @develar, I am open to help with a PR if you point me in the right direction.

**Comment by develar** [comment] 2017-01-24 09:09
>  I am open to help with a PR if you point me in the right direction.

Please see https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder/src/targets/dmg.ts#L127

**Comment by timfish** [comment] 2017-04-12 11:03
duplicate of #1121 ?

**Comment by develar** [comment] 2017-04-12 11:05
Duplicates #1121

**Closed by develar** 2017-04-12 11:05 UTC
Labels: mac

**Comment by withintheruins14** [comment] 2017-06-02 14:38
When using path in the dmg contents section, where is the path relative to? I am having issues bringing files into the dmg. Thanks! 😄

**Comment by develar** [comment] 2017-06-02 14:50
@withintheruins14 Please file issue and provide example (path relative to root of volume).

**Comment by CydeSwype** [comment] 2018-01-17 22:32
For anyone else wondering about the relative path, it's relative to the top level of the application so if you have your main.js under app/src/main.js and you want to reference another file in the DMG, you can use "path":"./app/images/other-file.pdf"
