### ISSUE TITLE
Failed to build for nsis-web --win --ia32

### ISSUE THREAD

**Issue by rightroad** [electron-userland/electron-builder#4725] opened 2020-02-29 09:06 UTC
**builder:** "electron-builder": "^22.3.2" (lastest)
**updater:**  "electron-updater": "^4.2.2" (lastest)
**electron:** "electron": "^8.0.2" (lastest)
**target:** "nsis-web"
**target-arch:** "x64", "ia32"

**Error:**
```
`yarn dist
yarn run v1.7.0
$ electron-builder
  • electron-builder  version=22.3.2 os=10.0.18362
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist\builder-effective-config.yaml
  • packaging       platform=win32 arch=x64 electron=8.0.2 appOutDir=dist\win-unpacked
  • packaging       platform=win32 arch=ia32 electron=8.0.2 appOutDir=dist\win-ia32-unpacked
  • building        target=nsis-web file=dist\nsis-web\MyApp Web Setup 0.1.0.exe archs=x64, ia32 oneClick=false perMachine=true
  • building embedded block map  file=dist\nsis-web\myapp-0.1.0-ia32.nsis.7z
  • building embedded block map  file=dist\nsis-web\myapp-0.1.0-x64.nsis.7z
  ⨯ C:\Users\USERNAME\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE`
```

**Error Output:**
```
!insertmacro: macro "_If" requires 4 parameter(s), passed 6!
Error in macro downloadApplicationFiles on macroline 19
Error in macro installApplicationFiles on macroline 63
!include: error in script: "installSection.nsh" on line 60
Error in script "<stdin>" on line 161 -- aborting creation process
  stackTrace=
Error: C:\Users\USERNAME\AppData\Local\electron-builder\Cache\nsis\nsis-3.0.4.1\Bin\makensis.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
...
```

**package.json**
```
{
    "postinstall": "electron-builder install-app-deps",
    "build": {
        "appId": "com.myapp.app",
        "productName": "MyApp",
        "asar": true,
        "publish": [{
            "provider": "github",
            "owner": "account",
            "repo": "repo"
        }],
        "win": {
            "icon": "build/icon.ico",
            "target": [{
                "target": "nsis-web",
                "arch": [
                    "x64",
                    "ia32"
                ]
            }]
        },
        "nsisWeb": {
            "oneClick": false,
            "perMachine": true,
            "allowElevation": true,
            "allowToChangeInstallationDirectory": true,
            "runAfterFinish": true,
            "unicode": true,
            "installerIcon": "build/icon.ico",
            "differentialPackage": true
        }
    },
    "scripts": {
        "start": "electron .",
        "pack": "electron-builder --dir",
        "dist": "electron-builder"
    },
    "devDependencies": {
        "electron": "^8.0.2",
        "electron-builder": "^22.3.2"
    },
    "dependencies": {
        "electron-updater": "^4.2.2"
    }
}
```

**Comment by rightroad** [comment] 2020-02-29 09:22
**NOTE:** this issue only occurs with the ia32 build for me.

**Comment by rightroad** [comment] 2020-02-29 09:37
Well that's weird but I was able to fix this by building for both architectures separately (building for x64 only, copying the dist output elsewhere then building again for ia32)

**Comment by rightroad** [comment] 2020-02-29 10:20
Another weird behavior.. the output exe changes in file size everytime I build the project (without changing the code).. I just move the output content somewhere else and rebuild.. the problem is that the size jumps from 50mb to 500mb!

**Comment by kzimny** [comment] 2020-03-03 09:48
The issue is already fixed in v.22.3.6.

**Comment by GitNomster** [comment] 2020-03-05 05:15
Too bad that win build on mac still doesn't work.

**Comment by onelsonic** [comment] 2020-03-06 21:19
this is working fine on windows with version 
**version : "electron-builder": "^22.4.0"**

**Closed** 2020-05-13 03:20 UTC
Labels: backlog

**Comment by brennomarques** [comment] 2020-05-22 23:26
I have this problem and not solve it, when I generate the build. What can it be?
++++++++++++++++++++++++++++++++++++++++++++++++++++

![image](https://user-images.githubusercontent.com/39415053/82715613-541eea00-9c6a-11ea-961e-bc251a9bcd5c.png)

**Comment by dvimoreira** [comment] 2021-02-26 17:05
> I have this problem and not solve it, when I generate the build. What can it be?
> ++++++++++++++++++++++++++++++++++++++++++++++++++++
> 
> ![image](https://user-images.githubusercontent.com/39415053/82715613-541eea00-9c6a-11ea-961e-bc251a9bcd5c.png)

You managed to solve it, can you help me?

**Comment by brennomarques** [comment] 2021-02-26 18:43
Yes, I decided as follows ...
As I am using Vue CLI Plugin Electron Builder, I left all the settings outside of .json in a file called vue.config.js, the default vue that electron recognizes.

Staying like this ...

```
module.exports = {
    pluginOptions: {
        electronBuilder: {
            builderOptions: {
                appId: "Assistente",
                productName: "Assistente",
                artifactName: "Assistente.${ext}",
                copyright: "Copyright © 2020 company name",
                publish: [{
                    provider: "generic",
                    url: "where are you going to get the artifacts......"
                }],
                linux: {
                    target: "AppImage",
                    synopsis: "Assistente",
                    description: "O Assistente.......",
                    executableName: "teste",
                    category: "Utility",
                },
                mac: {
                    category: "public.app-category.productivity",
                    target: [
                        "dmg",
                        "zip"
                    ],
                    bundleVersion: "46",
                    type: "distribution",
                },
                win: {
                    certificateSubjectName: ' name certification type A3',
                    "target": [{
                        "target": "nsis",
                        "arch": [
                            "x64",
                            "ia32"
                        ]
                    }],                   
                }
            }
        }
    }
}
```
I'm using "certificateSubjectName" if the certificate is of type p12 you must create the environment variable.

Documentation: https://www.electron.build/
