### ISSUE TITLE
build.publish wiki removal?

### ISSUE THREAD

**Issue by mattlyons0** [electron-userland/electron-builder#1080] opened 2017-01-04 05:50 UTC
Is there any reason all the build.publish documentation was removed from the wiki page recently?

See [diff](https://github.com/electron-userland/electron-builder/wiki/Options/_compare/b7f8358efe7cfd7b28170f1cf3f7282db83f8b84...a473c82078fb5ed1576643e7a76b559f0d1acc41#diff-2125f4734b7fa3ff5d3f1f81100375cd) between the two commits.

They were removed in revision `a473c82`of the `Options` page of the wiki. Without this documentation a lot of the NSIS autoupdate docs have broken links. I was following https://github.com/electron-userland/electron-builder/wiki/Auto-Update and step 2 (Configure Publish) didn't make complete sense to me until I found the old docs.

**Comment by develar** [comment] 2017-01-04 13:42
Confirmed. Yeah, because electron-builder-http module was extracted.

**Comment by mattlyons0** [comment] 2017-01-04 15:04
Has it been moved somewhere else? Looking at the electron-builder-http module on NPM it points to this repo.

**Comment by develar** [comment] 2017-01-04 15:09
@mattlyons0 I just need to fix docs generator config. Will be fixed soon.

**Closed** 2017-01-04 19:11 UTC
Labels: bug, readme improvement
