### ISSUE TITLE
NSIS installer doesn't work on Windows 10.

### ISSUE THREAD

**Issue by tylerlong** [electron-userland/electron-builder#2134] opened 2017-09-30 05:17 UTC
* **electron-builder 19.32.2**

* **electron-updater 2.10.1**

I built the installers without any issue on macOS.   The mac zip and dmg files both work like a charm. 

However, NSIS installer doesn't work on Windows 10.  Nothing pops up after clicking the installer.  

I tried the portable installer and it worked.

I tried the NSIS installer on Windows 7, it crashed at the end of the installation. But the app had been installed successfully and I could use the installed app without problem.

So the problem is I cannot start the NSIS installer widzard at all on Windows 10. Here is the error messages copied from event viewer:

```
Faulting application name: swagger-app Setup 0.1.2 (7).exe, version: 0.1.2.0, time stamp: 0x597fcc70
Faulting module name: System.dll, version: 0.0.0.0, time stamp: 0x597fcc59
Exception code: 0xc0000005
Fault offset: 0x000024ef
Faulting process id: 0x1d74
Faulting application start time: 0x01d339aa6fd80d2f
Faulting application path: C:\Users\tyler\Downloads\swagger-app Setup 0.1.2 (7).exe
Faulting module path: C:\Users\tyler\AppData\Local\Temp\nsd116C.tmp\System.dll
Report Id: eaf6eac8-08f9-47b2-9f1a-c71a20f3c94d
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 109171390464, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 108218031351

Problem signature:
P1: swagger-app Setup 0.1.2 (7).exe
P2: 0.1.2.0
P3: 597fcc70
P4: System.dll
P5: 0.0.0.0
P6: 597fcc59
P7: c0000005
P8: 000024ef
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER137E.tmp.WERInternalMetadata.xml
\\?\C:\Users\tyler\AppData\Local\Temp\WER216A.tmp.appcompat.txt
minidump.mdmp

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_swagger-app Setu_b5a54f9623e13ab132f9ff1cff60c7f64abe2d9d_930674b1_cab_96f42b6b

Analysis symbol: 
Rechecking for solution: 0
Report Id: eaf6eac8-08f9-47b2-9f1a-c71a20f3c94d
Report Status: 8
Hashed bucket: 34bf17e5a40047dadbbcce4144376124
```

Here are the built files: https://github.com/tylerlong/swagger-app/releases

You can also read the source code.

**Comment by develar** [comment] 2017-09-30 05:24
Please try to disable MS Defender.

Please try to install your app using terminal on Windows (not a joke).

**Comment by tylerlong** [comment] 2017-09-30 05:34
@develar  my friend also built an electron app about a month ago(with an old version of electron-builder of course). On the same Windows 10 I could install it successfully.  So I don' think the Windows 10 or its anti-virus software is the root cause.

**Comment by develar** [comment] 2017-09-30 05:35
@tylerlong Yes, in the recent versions NSIS was updated from NSIS 3.0.0 to NSIS 3.02.1 

I just want to understand what's happening and that's why ask you.

**Comment by develar** [comment] 2017-09-30 05:41
BTW, your release works for me, but in any case I confirm that I am aware of this issue on Windows 10.

**Comment by tylerlong** [comment] 2017-09-30 05:53
I just tried disabling the anti-virus software and installing from command line. It didn't work.  I could see the mouse became a spinner for a short time then nothing popped up.

@develar  there are two releases. One is NSIS installer and the other is portable exe. The portable one does work while the NSIS installers doesn't.

**Comment by develar** [comment] 2017-09-30 05:55
I have tried setup. Ok — it is some Windows 10 issue and I need clean Windows 10 to check, working on it. Don't worry — this issue will be fixed ASAP.

**Comment by develar** [comment] 2017-09-30 05:58
@tylerlong Could you please try my test app https://drive.google.com/file/d/0Bz3JwZ-jqfROZ0VSY0JMdlVFZGc/view?usp=sharing to install?

**Comment by tylerlong** [comment] 2017-09-30 06:11
Thank you for your quick response. I just tested **my** setup installer on **another** windows 10 computer and it didn't work.

I am going to try **yours**. Stay tuned.

**Comment by tylerlong** [comment] 2017-09-30 06:14
Yours didn't work either. Same issue.

```
Faulting application name: Onshape Setup 0.5.15.exe, version: 0.5.15.0, time stamp: 0x597fcc70
Faulting module name: System.dll, version: 0.0.0.0, time stamp: 0x597fcc59
Exception code: 0xc0000005
Fault offset: 0x000024ef
Faulting process id: 0x4fc
Faulting application start time: 0x01d339b3262c548e
Faulting application path: C:\Users\tyler\Downloads\Onshape Setup 0.5.15.exe
Faulting module path: C:\Users\tyler\AppData\Local\Temp\nskA429.tmp\System.dll
Report Id: 4c01c0f4-5531-40aa-a454-efa42844df38
Faulting package full name: 
Faulting package-relative application ID: 
```

```
Fault bucket 109171444889, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: Onshape Setup 0.5.15.exe
P2: 0.5.15.0
P3: 597fcc70
P4: System.dll
P5: 0.0.0.0
P6: 597fcc59
P7: c0000005
P8: 000024ef
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERA5BE.tmp.WERInternalMetadata.xml
\\?\C:\Users\tyler\AppData\Local\Temp\WERB8DA.tmp.appcompat.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WERB939.tmp.mdmp
\\?\C:\Users\tyler\AppData\Local\Temp\WERB998.tmp.WERDataCollectionFailure.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Onshape Setup 0._d5f0329446c7bcd09169c5532e09dc56bbe092_b9cfed65_10ffb9a4

Analysis symbol: 
Rechecking for solution: 0
Report Id: 4c01c0f4-5531-40aa-a454-efa42844df38
Report Status: 4104
Hashed bucket: 3806fd61a13ff25c2035d8565b61d9be
```

**Comment by develar** [comment] 2017-09-30 06:16
Cool! Please check https://drive.google.com/file/d/0Bz3JwZ-jqfROYk04RmE0OHZqV0k/view?usp=sharing

**Comment by tylerlong** [comment] 2017-09-30 06:27
Same issue for `Onshape Setup 0.5.15 ZIP.exe`

**Comment by develar** [comment] 2017-09-30 06:29
Issue reproduced on clean Windows 10 machine.

**Comment by develar** [comment] 2017-09-30 07:06
Upstream bug — reverted to NSIS 3.01.

**Closed** 2017-09-30 07:37 UTC
