### ISSUE TITLE
download-progress and update-downloaded events not firing with Electron 12

### ISSUE THREAD

**Issue by NGrey5** [electron-userland/electron-builder#5800] opened 2021-04-14 17:43 UTC
electron-builder:
22.10.5

electron-updater:
4.3.8

Electron:
12.0.4

Target:
NSIS

Settings: 

nsis:
  oneClick: true
  artifactName: "${productName}Setup.${ext}"
win:
  icon: "assets/icons/icon.ico"
  publisherName: "ngrey"
  certificateFile: null
  certificatePassword: null
  verifyUpdateCodeSignature: false
  publish:
    provider: "github"
    owner: "ngrey5"
    private: true
    repo: "repo-name"

Using electron-updater and the autoUpdater, it seems that with Electron 12 the 'download-progress' and 'update-downloaded' events are not firing. It works as expected using versions less than Electron 12.

Any help would be appreciated!

**Comment by mmaietta** [comment] 2021-04-15 15:44
I don't have an electron-updater or windows device to test this with.
Any help in debugging his further would be greatly appreciated. Can you check if any logs are being spat out or double-check that the electron 12 update callbacks haven't changed?

The code for adding the progress handler seems pretty straightforward, so I'm not sure where to look next.

**Comment by NGrey5** [comment] 2021-04-15 18:05
I'll try as best I can to help!

Below are the logs. After I check for the update, it says that it's downloading, but no event is emitted. I don't believe that the electron 12 callbacks have changed at all.

You'll see in the logs that I get a "Cannot download differentially, fallback to full download" error. I've been getting that for some time even before using electron 12. I know that's another issue I've been following for awhile.

```
[2021-04-15 12:46:50.844] [info]  Checking for update
[2021-04-15 12:46:52.333] [info]  Found version 0.0.3 (url: GPDBSetup.exe)
[2021-04-15 12:46:52.334] [info]  Downloading update from GPDBSetup.exe
[2021-04-15 12:46:52.338] [info]  Download block maps (old: "https://api.github.com/repos/NGrey5/update-test/releases/assets/34953211.blockmap", new: https://api.github.com/repos/NGrey5/update-test/releases/assets/34953211.blockmap)
[2021-04-15 12:46:52.569] [error] Cannot download differentially, fallback to full download: Error: Maximum allowed size is 50 MB
    at Object.responseHandler (C:\Users\Nick\AppData\Local\Programs\GPDB\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:241:26)
    at ClientRequest.<anonymous> (C:\Users\Nick\AppData\Local\Programs\GPDB\resources\app.asar\node_modules\builder-util-runtime\out\httpExecutor.js:303:17)
    at ClientRequest.emit (events.js:315:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:105:6777)
    at SimpleURLLoaderWrapper.emit (events.js:315:20)
```

I followed the PR you referenced as well. Looks like they fixed the issue, but maybe something with version 12 messed it up again?

Let me know if you need anything else!

**Comment by mmaietta** [comment] 2021-06-13 16:02
Hmmm, can you please try updating to electron 22.11.x and test with node 14?
That would have cleared up the "Maximum allowed size" error message. Other PRs have been merged that add fixes related to block maps also would be in some of the more recent releases IIRC. Another PR also added a new location for the `update-downloaded` event to be emitted (albeit I think might be creating another bug atm)

**Comment by sumigrev** [comment] 2021-07-19 20:49
* **Electron-Builder Version**: `22.11.7` (Electron-Updater is at `4.3.9`)


* **Node Version**: `v14.17.2`



* **Electron Version**: `13.1.6`
* **Electron Type (current, beta, nightly)**: current



* **Target**: `NSIS`



I'm also having a similar issue where the `download-progress` and `error` errors aren't firing. Any help is appreciated.

Our same event-handling code was working previously with Electron `9.4.4`, Electron-Builder `22.9.1`, and Electron-Updater `4.3.5`, but we recently decided to upgrade to the latest Electron version.

**Comment by sumigrev** [comment] 2021-07-19 23:13
I noticed that this particular issue seems to occur when the differential downloader fallbacks to a full download (the logs show the error: `Cannot download differentially, fallback to full download: ...`, which is expected in our use case). This means that the issue is probably with the full download process, right?

**Closed** 2022-04-17 19:14 UTC
Labels: help wanted, backlog
