### ISSUE TITLE
Using with electron-prebuilt-compile

### ISSUE THREAD

**Issue by hacdias** [electron-userland/electron-builder#3344] opened 2018-09-25 08:54 UTC
* **Version**: 20.28.7 

* **Target**: Windows

Early this year I opened an issue regarding electron-prebuilt-compile (#2361) and, although the issue at that time was fixed, I'm still having some issues.

`package.json`:

```json
{
  "name": "ipfs-desktop",
  "private": true,
  "version": "1.0.0",
  "productName": "IPFS Desktop",
  "description": "IPFS Native Application",
  "main": "src/index.js",
  "scripts": {
    "start": "electron .",
    "lint": "standard",
    "pack": "electron-builder --dir",
    "dist": "electron-builder"
  },
  // ...
  "build": {
    "appId": "io.ipfs.desktop",
    "mac": {
      "category": "public.app-category.utilities"
    }
  },
  "devDependencies": {
    "electron-builder": "^20.28.4",
    "electron-prebuilt-compile": "^3.0.0",
    "pre-commit": "^1.2.2",
    "standard": "^12.0.1"
  },
  "dependencies": {
    "fs-extra": "^7.0.0",
    "ipfs-css": "^0.10.0",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "tachyons": "^4.11.1"
  }
}
```

If I run `npm run dist` and then I try to execute the binary file, I get this:

![image](https://user-images.githubusercontent.com/5447088/46003647-f1e2a000-c0a8-11e8-8220-4809f60430e4.png)

Am I missing some step?

**Comment by Megajin** [comment] 2018-09-28 16:27
It is hard to track down your problem like this.
But seeing the error message I'm guessing that your `index.js` is getting bundled wrong.
This can happen if you use `babel` and mix up configurations.

To make things easier:
1. Try to look for mixed configurations like a `.babelrc`.
2. Use a linter like `eslint` and check your file if there is a `SyntaxError`
3. generate a new project with a simple index file written in ES5/6/7 (whatever you use) and compile it with `electron-compile` to see if that is the cause.

**Comment by simonpai** [comment] 2018-10-25 12:16
AFAICS, the original poster got around by ditching electron-prebuilt-compile and setting up babel instead (with using babel-register in development and pointing to compiled js folder for production). I ran into the same issue and resolved by following what he did. Just sharing the information in case someone else needs it.

See his commit [here](https://github.com/ipfs-shipyard/ipfs-desktop/commit/88d1628378ae1935bc400f3089d6c14489c84c92).

**Comment by JuanDavidLopez95** [comment] 2019-03-19 14:36
I get this same issue when  `"electronVersion": "electron-prebuilt-compile"` is omitted from the electron-builder build configuration of package.json. 

However, when `"electronVersion": "electron-prebuilt-compile"` is included, I get the following error:

`cannot resolve https://github.com/electron/electron/releases/download/velectron-prebuilt-compile/electron-velectron-prebuilt-compile-win32-x64.zip: status code 404`

Here is a screenshot of my output:

![image](https://user-images.githubusercontent.com/10659877/54318194-b8441980-45a2-11e9-8053-c7981970897d.png)

I thought initially that this was an issue with my wi-fi connection, but I am able to replicate this issue on two different computers connected to different networks, so i doubt it is an internet connectivity problem.

I initially posted this as an issue [https://github.com/electron-userland/electron-prebuilt-compile/issues/78](#78) on the electron-prebuilt-compile github; i am posting here as well as it is also related to electron-builder.

**Comment by Megajin** [comment] 2019-03-20 10:21
@JuanDavidLopez95 it has nothing to do with your network or your computer.
The site can't be resolved since it is down. Furthermore your issue has nothing to do with `electron-builder` since it appears only when using `electron-prebuilt-compile`.

For my own projects I never use  `electron-prebuilt-compile`. Here are my steps how to prepare my project for a build or a release:

1. Clear release directory
2. Run bundler for electron files in my case `parcel-bundler`: [https://github.com/parcel-bundler/parcel](Parcel Repo)
3. Run bundler for client files like react, again I use parcel for this.
4. I run a script called postinstall which will use `install-app-deps` to make all dependencies available in my prelease folder. It is important to keep the files in a flat tree to keep things simple which will avoid problems.
5. Run `electron-builder`

Here is the given part of my `package.json`:
```JSON
"build": "npm run build:clear && npm run build:electron && npm run build:react && npm run postinstall && npm run dist && npm run copy",
"build:clear": "rm -rf dist/build/",
"build:react": "npx parcel build ./src/index.html --target electron --out-dir dist/build --cache-dir dist/build/.react-cache --public-url ./",
"build:electron": "npx parcel build ./src/electronIndex.js --target electron --out-dir dist/build --cache-dir dist/build/.electron-cache --public-url ./",
"dist": "npx electron-builder",
"postinstall": "electron-builder install-app-deps",
```

Just in case someone needs it here is my `.babelrc`:
```JSON
{
  "presets": ["@babel/preset-react"],
  "plugins": [
  "@babel/plugin-transform-runtime"
  ]
}
```

I hope this will help you.

Regards,
Megajin

**Closed** 2019-07-08 19:29 UTC
Labels: backlog
