### ISSUE TITLE
Prepackaged app resources gets mangled by mksquashfs when packaging for AppImage

### ISSUE THREAD

**Issue by ascendancyy** [electron-userland/electron-builder#2996] opened 2018-06-08 08:40 UTC
* **Version**: 20.15.1

* **Target**: AppImage

My setup involves building with a prepackaged app (from electron-packager). What seems to happen is an app-update.yml file gets written to the AppImage staging directory. `staging/resources/app-update.yml`

https://github.com/electron-userland/electron-builder/blob/master/packages/electron-builder-lib/src/targets/AppImageTarget.ts#L76

When `mksquashfs` is run the debug logs show:
`Source directory entry resources already used! - trying resources_1`

So the final directory would look something like:  
resources/
└── app-update.yml
resources_1
└── app.asar
└── electron.asar

Which means when running the AppImage nothing happens.

**Comment by peterdanis** [comment] 2018-06-17 15:46
Duplicate of https://github.com/electron-userland/electron-builder/issues/2958

**Closed** 2018-06-17 23:08 UTC
