### ISSUE TITLE
failed to create universal mac build after update electron to v18.0.0

### ISSUE THREAD

**Issue by ocavue** [electron-userland/electron-builder#6751] opened 2022-03-29 17:37 UTC
* **Electron-Builder Version**: 22.14.13

* **Node Version**: 16

* **Electron Version**: 18.0.0
* **Electron Type (current, beta, nightly)**: current

* **Target**: mac

After updating electron from v17.3.0 to v18.0.0, `electron-builder` raises the following error when I try to build a universal mac build: 

```
• electron-builder  version=[22](https://github.com/ocavue/rino/runs/5741400411?check_suite_focus=true#step:6:22).14.13 os=20.6.0
  • loaded configuration  file=/Users/runner/work/rino/rino/packages/electron/electron-builder.js
  • packaging       platform=darwin arch=x64 electron=18.0.0 appOutDir=dist/mac-universal--x64
  • downloading     url=https://github.com/electron/electron/releases/download/v18.0.0/electron-v18.0.0-darwin-x64.zip size=82 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v18.0.0/electron-v18.0.0-darwin-x64.zip duration=1.089s
  • packaging       platform=darwin arch=arm64 electron=18.0.0 appOutDir=dist/mac-universal--arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v18.0.0/electron-v18.0.0-darwin-arm64.zip size=84 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v18.0.0/electron-v18.0.0-darwin-arm64.zip duration=1.307s
  • packaging       platform=darwin arch=universal electron=18.0.0 appOutDir=dist/mac-universal
  ⨯ Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/MainMenu.nib/keyedobjects-101300.nib" did not  failedTask=build stackTrace=Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/MainMenu.nib/keyedobjects-101300.nib" did not
    at exports.makeUniversalApp (/Users/runner/work/rino/rino/node_modules/.pnpm/@electron+universal@1.0.5/node_modules/@electron/universal/src/index.ts:107:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MacPackager.doPack (/Users/runner/work/rino/rino/node_modules/.pnpm/app-builder-lib@22.14.13/node_modules/app-builder-lib/src/macPackager.ts:1[25](https://github.com/ocavue/rino/runs/5741400411?check_suite_focus=true#step:6:25):9)
    at MacPackager.pack (/Users/runner/work/rino/rino/node_modules/.pnpm/app-builder-lib@22.14.13/node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/runner/work/rino/rino/node_modules/.pnpm/app-builder-lib@22.14.13/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/runner/work/rino/rino/node_modules/.pnpm/builder-util@22.14.13/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/runner/work/rino/rino/node_modules/.pnpm/app-builder-lib@22.14.13/node_modules/app-builder-lib/src/packager.ts:376:[31](https://github.com/ocavue/rino/runs/5741400411?check_suite_focus=true#step:6:31))
    at Packager.build (/Users/runner/work/rino/rino/node_modules/.pnpm/app-builder-lib@22.14.13/node_modules/app-builder-lib/src/packager.ts:[33](https://github.com/ocavue/rino/runs/5741400411?check_suite_focus=true#step:6:33)7:12)
    at Object.executeFinally (/Users/runner/work/rino/rino/node_modules/.pnpm/builder-util@22.14.13/node_modules/builder-util/src/promise.ts:12:14)
```

According to https://github.com/electron/electron/issues/33267, we need to update `@electron/universal` to v1.2.1 to fix this issue.

**Comment by ocavue** [comment] 2022-03-29 17:42
Related PR: https://github.com/electron-userland/electron-builder/issues/6751

**Comment by bjbk** [comment] 2022-03-31 22:59
I reverted to v17

**Comment by ArmelChesnais** [comment] 2022-03-31 23:39
@mayfield if you're using yarn, you can use resolutions in your package.json:
```
  "resolutions": {
    "@electron/universal": "^1.2.1"
  },
 ```
 And install that package in your own devDependencies
 ```
 "devDependencies": {
    [...]
    "@electron/universal": "^1.2.1",
    [...]
 ```
This will force all dependencies to use that version.
You will have to remove it once it's been addressed by electron-builder to avoid any weird behaviours in the future, but this should help in the meantime as a temporary band-aid.

**Comment by bjbk** [comment] 2022-04-01 00:02
@ArmelChesnais Thanks for this reminder!  I was able to upgrade to v18 and now universal build is successful. ✨ 
`App · [SUCCESS] electron-builder built the app`

**Comment by mmaietta** [comment] 2022-04-09 16:36
Released in latest 23.0.4

**Closed by mmaietta** 2022-04-09 16:36 UTC

**Comment by mayfield** [comment] 2022-04-16 19:28
Not sure if this is related but wanted to drop it here.  I upgraded all the things and my build is now proceeding past the menu nib file, but is then failing on my sqlite3 dep.  This of course worked properly before the switch to electron 18 upgrade (all the associated upgrades required for it).

Here is the exact output, which fails on a SHA of a Makefile in sqlite..

```
> electron-builder build -p never

  • electron-builder  version=23.0.4 os=21.4.0
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=cap@0.2.1, sqlite3@5.0.3 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=18.0.3 appOutDir=dist/mac-universal--x64
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • rebuilding native dependencies  dependencies=cap@0.2.1, sqlite3@5.0.3 platform=darwin arch=arm64
  • packaging       platform=darwin arch=arm64 electron=18.0.3 appOutDir=dist/mac-universal--arm64
  • asar usage is disabled — this is strongly not recommended  solution=enable asar and use asarUnpack to unpack files that must be externally available
  • packaging       platform=darwin arch=universal electron=18.0.3 appOutDir=dist/mac-universal
  ⨯ Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Makefile" did not  failedTask=build stackTrace=Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Resources/app/node_modules/sqlite3/build-tmp-napi-v6/Makefile" did not
    at exports.makeUniversalApp (/Users/mayfield/project/sauce4zwift/node_modules/@electron/universal/src/index.ts:123:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at MacPackager.doPack (/Users/mayfield/project/sauce4zwift/node_modules/app-builder-lib/src/macPackager.ts:125:9)
    at MacPackager.pack (/Users/mayfield/project/sauce4zwift/node_modules/app-builder-lib/src/macPackager.ts:179:7)
    at Packager.doBuild (/Users/mayfield/project/sauce4zwift/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/mayfield/project/sauce4zwift/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/mayfield/project/sauce4zwift/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/mayfield/project/sauce4zwift/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/mayfield/project/sauce4zwift/node_modules/builder-util/src/promise.ts:12:14)
make: *** [build] Error 1
```

**Comment by mayfield** [comment] 2022-04-16 19:38
I can confirm the file in question is actually a build artifact of sqlite.  It looks like a parallel process generates those paths so the output is non deterministic.  Maybe this issue existed on prior builds but I was just getting lucky.  In general is there a user configurable way to inform the universal build process what files are shared and which ones should be treated as arch specific?

```patch
--- /Users/mayfield/tmp/Makefile	2022-04-16 13:31:29.000000000 -0600
+++ /Users/mayfield/tmp/Makefile2	2022-04-16 13:31:34.000000000 -0600
@@ -347,7 +347,7 @@
 
 quiet_cmd_regen_makefile = ACTION Regenerating $@
 cmd_regen_makefile = cd $(srcdir); /usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py -fmake --ignore-environment "-Dlibrary=shared_library" "-Dvisibility=default" "-Dnode_root_dir=/Users/mayfield/.electron-gyp/18.0.3" "-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp" "-Dnode_lib_file=/Users/mayfield/.electron-gyp/18.0.3/<(target_arch)/node.lib" "-Dmodule_root_dir=/Users/mayfield/project/sauce4zwift/node_modules/sqlite3" "-Dnode_engine=v8" "--depth=." "-Goutput_dir=." "--generator-output=build" -I/Users/mayfield/project/sauce4zwift/node_modules/sqlite3/build/config.gypi -I/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi -I/Users/mayfield/.electron-gyp/18.0.3/include/node/common.gypi "--toplevel-dir=." binding.gyp
-Makefile: $(srcdir)/node_modules/node-addon-api/node_api.gyp $(srcdir)/binding.gyp $(srcdir)/../../../../../../usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi $(srcdir)/../../../../.electron-gyp/18.0.3/include/node/common.gypi $(srcdir)/deps/common-sqlite.gypi $(srcdir)/build/config.gypi $(srcdir)/deps/sqlite3.gyp
+Makefile: $(srcdir)/../../../../../../usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi $(srcdir)/binding.gyp $(srcdir)/build/config.gypi $(srcdir)/deps/common-sqlite.gypi $(srcdir)/../../../../.electron-gyp/18.0.3/include/node/common.gypi $(srcdir)/node_modules/node-addon-api/node_api.gyp $(srcdir)/deps/sqlite3.gyp
 	$(call do_cmd,regen_makefile)
 
 # "all" is a concatenation of the "all" targets from all the included
```
