### ISSUE TITLE
Unable to build AppImage on Windows (service.electron.build)

### ISSUE THREAD

**Issue by CodeDead** [electron-userland/electron-builder#4318] opened 2019-10-13 16:57 UTC
* **Version**: 21.2.0

* **Target**: linux AppImage

* **Description**:
Building a Linux AppImage on a **Windows** device has been unavailable for the past couple of months thanks to an outage. More information below.

> error=Get https://service.electron.build/find-build-agent?no-cache=1eq6jtp: dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by CodeDead** [comment] 2019-12-16 21:30
This is still relevant and has not been addressed yet.

> cannot get, wait  error=Get https://service.electron.build/find-build-agent?no-cache=1evftno: dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
> attempt=1
> waitTime=4


> Get https://service.electron.build/find-build-agent?no-cache=1evftno: dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by matvelloso** [comment] 2019-12-17 20:59
FYI I seem to be stuck with the same error...

**Comment by kavil** [comment] 2019-12-18 09:04
same error...

**Comment by rowalski** [comment] 2020-01-09 14:52
i am getting this same error trying to build for debian...

**Comment by mastastealth** [comment] 2020-02-01 20:32
Same error here on Win 7, just trying a simple `--linux` build.

**Comment by ThummalaJanardhanReddy** [comment] 2020-02-10 12:23
Is there any fix or work around for this.

**Comment by CodeDead** [comment] 2020-02-10 14:15
> Is there any fix or work around for this.

Building directly on a linux system. You can also build windows images on linux using Wine.

**Comment by seannowotny** [comment] 2020-02-10 17:02
Has anyone had luck with the Windows Linux Subsystem?

**Comment by AstroGD** [comment] 2020-04-01 14:56
Same issue here. Trying to build linux package for snap using `electron-builder --linux snap`

**Comment by o5k** [comment] 2020-05-11 13:26
Why is this still not addressed after half a year???

**Comment by CodeDead** [comment] 2020-05-11 13:49
@o5k It's a free service after all, and you can still create Linux builds on a Linux host (and Windows builds using wine on Linux).

**Comment by shickk** [comment] 2020-06-23 07:40
Same error.  Any updates?

**Comment by gamernitro999** [comment] 2020-07-05 12:47
I have the same error with deb and appImage I go to the site and this site is down

**Comment by kurone-kito** [comment] 2020-07-12 07:41
I have the same error on Windows 10.
Curiously, if I try the same project on macOS, it doesn't reproduce.

**Comment by CodeDead** [comment] 2020-07-12 16:27
> I have the same error on Windows 10.
> Curiously, if I try the same project on macOS, it doesn't reproduce.

Electron builder supports building Windows binaries on non-Windows machines. See: 
https://www.electron.build/multi-platform-build

This is also a work-around for this problem. You can use a Linux/macOS build machine to provide both the platform's own binaries and Windows binaries.

**Comment by o5k** [comment] 2020-09-10 19:44
still relevant

**Comment by fairking** [comment] 2020-09-17 14:56
"electron": "^10.1.2",
    "electron-builder": "^22.8.1",

Got same error today. Trying to build on windows 10 with `electron-builder --linux snap`.
The error:
```
cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1fm6tp0": dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                      attempt=0
                      waitTime=2
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1fm6tp0": dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                      attempt=1
                      waitTime=4
  • cannot get, wait  error=Get "https://service.electron.build/find-build-agent?no-cache=1fm6tp0": dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
                      attempt=2
                      waitTime=6
  ⨯ Get "https://service.electron.build/find-build-agent?no-cache=1fm6tp0": dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  ⨯ C:\Code\electron-cgi-calculator-demo\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE  stackTrace=
                                                                                                                                                      Error: C:\Code\electron-cgi-calculator-demo\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code ERR_ELECTRON_BUILDER_CANNOT_EXECUTE
                                                                                                                                                          at ChildProcess.childProcess.once.code (C:\Code\electron-cgi-calculator-demo\node_modules\builder-util\src\util.ts:243:14)
                                                                                                                                                          at Object.onceWrapper (events.js:286:20)
                                                                                                                                                          at ChildProcess.emit (events.js:198:13)
                                                                                                                                                          at maybeClose (internal/child_process.js:982:16)
                                                                                                                                                          at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
                                                                                                                                                      From previous event:
                                                                                                                                                          at runCallback (timers.js:705:18)
                                                                                                                                                          at tryOnImmediate (timers.js:676:5)
                                                                                                                                                          at processImmediate (timers.js:658:5)
                                                                                                                                                      From previous event:
                                                                                                                                                          at RemoteBuilder.build (C:\Code\electron-cgi-calculator-demo\node_modules\app-builder-lib\src\remoteBuilder\RemoteBuilder.ts:52:28)
                                                                                                                                                          at RemoteTarget.finishBuild (C:\Code\electron-cgi-calculator-demo\node_modules\app-builder-lib\src\linuxPackager.ts:99:30)
```

**Comment by Darkseal** [comment] 2020-10-06 06:51
Unfortunately the https://service.electron.build has been down since months and it doesn't seem that such issue will be fixed anytime soon, as we can see from the amount of (mostly open) GitHub issues that have been opened from users that are trying to deal with such problem in the past months.

Here's a viable alternative to build a redistributable Linux package on a Windows 10 environment: I'll try to explain it using a step-by-step approach in order to make it as easy as possible for those who don't know Docker well.

* Install Docker from [here](https://docs.docker.com/get-docker/)
* Download the [electronuserland/builder](https://hub.docker.com/r/electronuserland/builder/) Docker image with the following console command:
`docker pull electronuserland/builder`
* From the Electron project's root folder (such as `C:\MyApp`), type the following command-line command to run the container and map the Electron project's root folder to the /project virtual path:
`docker run -rm -ti -v C:\MyApp\:/project -w /project electronuserland/builder`
* From inside the container, type the following commands to upgrade the Electron project's Yarn packages, globally install the electron-builder package and build the Linux redistributable package:
```
cd /project
yarn upgrade
yarn global add electron-builder
electron-builder -l
```

If everything went smooth, you should be able to locate your `MyApp.deb` file (or `rpm`, `AppImage`, or anything you've configured within the electron-builder's `package.json` file) inside the Electron project's `/dist/` folder.

For further info about this whole procedure and a bit of background, check out [this post](https://www.ryadel.com/en/electron-build-linux-package-from-windows/) on my blog.

**Comment by JasonkayZK** [comment] 2020-11-08 09:00
> Unfortunately the https://service.electron.build has been down since months and it doesn't seem that such issue will be fixed anytime soon, as we can see from the amount of (mostly open) GitHub issues that have been opened from users that are trying to deal with such problem in the past months.
> 
> Here's a viable alternative to build a redistributable Linux package on a Windows 10 environment: I'll try to explain it using a step-by-step approach in order to make it as easy as possible for those who don't know Docker well.
> 
> * Install Docker from [here](https://docs.docker.com/get-docker/)
> * Download the [electronuserland/builder](https://hub.docker.com/r/electronuserland/builder/) Docker image with the following console command:
>   `docker pull electronuserland/builder`
> * From the Electron project's root folder (such as `C:\MyApp`), type the following command-line command to run the container and map the Electron project's root folder to the /project virtual path:
>   `docker run -rm -ti -v C:\MyApp\:/project -w /project electronuserland/builder`
> * From inside the container, type the following commands to upgrade the Electron project's Yarn packages, globally install the electron-builder package and build the Linux redistributable package:
> 
> ```
> cd /project
> yarn upgrade
> yarn global add electron-builder
> electron-builder -l
> ```
> 
> If everything went smooth, you should be able to locate your `MyApp.deb` file (or `rpm`, `AppImage`, or anything you've configured within the electron-builder's `package.json` file) inside the Electron project's `/dist/` folder.
> 
> For further info about this whole procedure and a bit of background, check out [this post](https://www.ryadel.com/en/electron-build-linux-package-from-windows/) on my blog.

It works，but the command should be:
`docker run --rm -ti -v C:\MyApp\:/project -w /project electronuserland/builder`
The `-rm` flag should be `--rm`

**Comment by CodeDead** [comment] 2021-01-09 23:08
This is still relevant.

**Comment by snaildos** [comment] 2021-02-01 06:44
This is pathetic? Electron is used everywhere, and now we can't even build linux images?
That's funny.
Seriously.
What in the world is actually going on here?

**Comment by CodeDead** [comment] 2021-02-02 18:29
Multiple workarounds have already been discussed here @snaildos . This is still a free service and one should not expect free things to last or remain free and accessible for everyone for eternity.

You're free to host your own build service for the world to use, of course.

**Comment by snaildos** [comment] 2021-02-03 02:50
Alright. So if I where too host my own build service, how do I change the electron-builder default build server URL?

**Comment by newalphamedia** [comment] 2021-04-09 02:33
I'd like to know how to host my own service and change the build server URL also.

**Comment by snaildos** [comment] 2021-04-09 03:08
Not worth it tbh, just get bare metal Linux machine and install wine. Run builds etc on there. :)

**Comment by mmaietta** [comment] 2021-04-10 15:43
The only reference to that URL in this repo that I can find in the code is this:
```
<env name="BUILD_AGENT_HOST" value="service.electron.build" />
```
There's this repo+readme with info on how to host your own service: https://github.com/electron-userland/electron-build-service/blob/master/self-hosted.md

If you can point me as to where this build server URL needs to be configured in this repo such that you're able to use your own build service, I can happily take a look at having that configurable (if not, just a local patch file for the interim)

Also related, if you're ever interested in submitting a quick fix or collaborate on a larger feature, here are easy instructions for setting up a local dev env:
https://github.com/electron-userland/electron-builder/blob/master/CONTRIBUTING.md#to-setup-a-local-dev-environment

For context, I think there are only a couple of maintainers active on this project, so I'd happily accept contributions 🙂

**Comment by rzfzr** [comment] 2021-04-29 13:59
No luck with @Darkseal and @JasonkayZK solution, it creates the project dir but with no contents, any ideas?

**Comment by JasonkayZK** [comment] 2021-05-09 11:57
> No luck with @Darkseal and @JasonkayZK solution, it creates the project dir but with no contents, any ideas?

**No better ideas yet!** :disappointed: 

I tried to use virtual machine such as Ubuntu or MacOS mirror in VMWare to build and test for multiple-platform. It works!
Maybe you can try different environment in GIthub-Actions. :smile:

**Comment by sleeyax** [comment] 2021-07-09 13:00
Still relevant :/

> Is this still relevant? If so, what is blocking it? Is there anything you can do to help move it forward?
> 
> This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

Still relevant :/

**Comment by mmaietta** [comment] 2021-07-09 18:21
Still relevant and still no plans for restarting the service. The service is dead. Closing this

**Closed by mmaietta** 2021-07-09 18:21 UTC
